### ISSUE TITLE
Duplicate check of iBlockState in isWater intended?

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/Structurize#105]
The following line executes the same check twice:
https://github.com/ldtteam/Structurize/blob/f6855760989fe2b8771cc5e893d1905ec40e4de1/src/main/java/com/ldtteam/structurize/util/BlockUtils.java#L128

Is this intended or should the 2nd check be for flowing water?

**Comment by Raycoms** [comment]
Yes, was supposed to be flowing water =D

**Comment by Raycoms** [comment]
I made it a more generic check now.
