### ISSUE TITLE
The game crashed whilst initializing game 

### ISSUE THREAD

**Issue by Gisssmo** [ldtteam/Structurize#106]
Hi all

Im new to github but I encounted a little problem also sorry for my bad grammar English is not my first language. Today I installed some mods for Forge version 1.15.2 and I found the mod called Minecolonies and structurize that look really good and I would like to try. But when I placed all in the mods folder and run Forge I got this error msg The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraft/world/IEnviromentBlockReader
I did not see anybody on here having similar problem so I decided to ask you guys and girls for help.
I added the crash report as well and the mod list
Bioms-O-plenty 1.15.2
Bookshelf 1.15.2
cfm-7.0.0pre15-mc.1.15.1
DoggyTalents 1.15.2.3
DungeonCrawl 1.14.4-1.6.3
EnchantmentDescription 1.15.2
Falling-Tree-mod 1.15.2
Hwyla forge 1.14.4
jei-1.15.2-6.0.0.2
minecolonies 0.10.773-Beta
structurize 0.10.284 -Beta
SwordBlockingCombat-v1.3.1-1.14.4
u-team_core1.15.2
Useful-backpacks-mod-1.15.2
valhesia_structures-1.14.4
xaeros_minimap_fp20.5.2_forge_1.15.2

[crash-2020-03-19_16.49.04-client.txt](https://github.com/ldtteam/Structurize/files/4355560/crash-2020-03-19_16.49.04-client.txt)

**Comment by Raycoms** [comment]
Can you please upload the crahslog as a gist or pastebin?

**Comment by Nightenom** [comment]
instance of MinecraftForge/MinecraftForge#6719
