### ISSUE TITLE
World crashes upon initialization when adding Structurize and Minecolonies to mods

### ISSUE THREAD

**Issue by calpluca** [ldtteam/Structurize#108]
### Structurize version

Version: structurize-0.10.285-BETA.jar
              minecolonies-0.11.785-BETA-universal.jar

### Expected behavior

- 

### Actual behaviour

-  I was simply trying to use Minecolonies (0.11.785-BETA-universal.jar) and Structurize (above mentioned version) on a server I have on McProHosting (1GB RAM with 3 people on it). I have a bunch of others mods installed and they seems to work fine, but if I add Minecolonies and Structurize, the world fails to initialize. 

Upon crashing, **when trying the mods in singleplayer** Minecraft Luancher says:
 _The game crashed whilst exception in server tick loop_
_Error: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter_

Below there's a pastebin of the server crash report, hoping it will be useful. 

I am using **Forge 31.1.16** both on the server and in my singleplayer launcher, **Minecraft version is 1.15.2** 

https://pastebin.com/wdqQQGGS

### Steps to reproduce the problem

1. paste mods versions above mentioned
2. start a world (singleplayer) or start a server
3. crash :(
4. ... Profit

**Comment by someaddons** [comment]
try using the most recent alpha of both mods isntead

**Comment by Nightenom** [comment]
java version 11.0.5 by Oracle Corporation
welp, forge is java8 only

**Comment by calpluca** [comment]
> java version 11.0.5 by Oracle Corporation
> welp, forge is java8 only

But, forge runs just fine on both the server and the singleplayer? I am sorry, I am no programmer, just asking what could I do to make it work.

**Comment by someaddons** [comment]
install java 8  https://adoptopenjdk.net/

**Comment by calpluca** [comment]
> install java 8 https://adoptopenjdk.net/

Thank you. Can I do that on a server I am renting from mcprohosting.com?

**Comment by someaddons** [comment]
I wouldnt know, depends on the host
