### ISSUE TITLE
Server crash with only Structurize mod

### ISSUE THREAD

**Issue by jrjespersen** [ldtteam/Structurize#115]
### Structurize version
Version: 0.10.294-ALPHA (Also tried 0.10.282-RELEASE)
MC Version: 1.15.2
Forge Version: 31.1.36

### Expected behavior
World to load successfully (new world, not loading existing)

### Actual behaviour
Crash (see attachments)
[crash-2020-04-07_08.53.12-server.txt](https://github.com/ldtteam/Structurize/files/4444415/crash-2020-04-07_08.53.12-server.txt)
<img width="879" alt="Screen Shot 2020-04-07 at 8 57 41 AM" src="https://user-images.githubusercontent.com/8258524/78671886-e1ba9c00-78ad-11ea-8010-2aa695c902f6.png">

### Steps to reproduce the problem
1) Create new vanilla server directory
2) Install Forge
3) Copy Structurize to mods folder
4) Start server

**Comment by Nightenom** [comment]
forge and minecraft supports only java 8

**Comment by jrjespersen** [comment]
Thanks, first Java 11 compatibility issue I've encountered. Thanks for pointing that out. Love the mod!
