### ISSUE TITLE
Multiblock - Right-click doesn't set origin direction

### ISSUE THREAD

**Issue by RolanDecoy** [ldtteam/Structurize#116]
Versions:
  Minecraft 1.15.2
  Structurize 0.10.285-BETA
  MineColonies 0.11.802-BETA-universal

Expected behaviour:
In the Multiblock interface, the left mouse button should set the direction blocks would be 'shoved' to and the right mouse button would set the direction blocks would be pulled from when a redstone signal is added / block is powered, according to the wiki-page on the subject (https://wiki.minecolonies.com/source/items/multiblock).

Expected result:
The direction clicked should turn green when using the left mouse button and red using the right mouse button. If not selected, horizontal buttons should turn blue and the vertical buttons should turn yellow / orange. The block itself should also respect these directions for in- and output and ignore the sides not selected.

Actual behaviour:
The left mouse button properly triggers the buttons (all of them) and the block respects the settings when confirmed. The right button does not function at all and the setting remains at, what I assume is the default state of down '-'. The block respects that setting as well, I just can't change it. Putting blocks below the Multiblock pulls them in properly and losing the redstone signal it places them back properly. It is merely the function of the right mouse button that seems to be ignored.

Setting the input (green) to down (-) in an attempt to override will save the changes but the Multiblock will not respond to a redstone signal at all, as if there was a block blocking its path even if there's nothing there (air block?).

Reproduction:
Place Multiblock, place some specific block type (say Oak Planks) east of it and a different specific type (say Cobblestone) below it (so you can see in an instance which one is being pulled in). Open the interface, set the output (left mouse button) to anything but down or east. (Try and) set the input (right mouse button) to anything but down or east. Add a redstone signal to see the results and observe wich specific block is being pulled from where and where it is going. The direction where it's going should be correct, but the direction it is being pulled from should always be down (say Cobblestone) if at all (see override in Actual behaviour).

**Comment by ravenbuilder934** [comment]
This works for me. If I remember correctly you also need to have blocks where you're trying to set it to pull from

**Comment by ravenbuilder934** [comment]
Closed as stale + not reproduced
