### ISSUE TITLE
Structurize encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by NiickNICHEN** [ldtteam/Structurize#118]
I need Structurize for Minecolonies, I tried 0-10.285-BETA, I tried 0.10.284-BETA, 0.10.282-RELEASE and 0.10.297-ALPHA, and i always got this error.
 
I have the Forge 31.1.41 on 1.15.2 minecraft version.

When the loading bar ends is when the error occurs.

[latest.log](https://github.com/ldtteam/Structurize/files/4457754/latest.log)

**Comment by Nightenom** [comment]
Please try this version, also if you can test build tool preview and provide some screenshots I would be glad
<https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Structurize_Branches_Build/36551:id/build/libs/structurize-0.10.211-PERSONAL.jar>

**Comment by Nightenom** [comment]
Closed in favor of #112
