### ISSUE TITLE
Structurize encountered an error during the sided_setup event phase : null

### ISSUE THREAD

**Issue by theoklm** [ldtteam/Structurize#120]
structurize-0.10.282-RELEASE in minecraft 1.15.2

Structurize and minecolonies worked fine with forge-31.1.39 and a bunch of other mods installed such as quark or traverse generation until I installed optifine and optiforge (to make optifine compatible with forge in this version). I think I tried all the possibilities to combine the differents version of structurize and optiforge, alpha, beta, all releases even the one you gived there (structurize 0.10.211 personnal)

So this is the only issue I had so far with this install, looks like there is a conflict between sructurize and optiforge or optifine, I send you my lastest.log, thanks you for taking care of these fantastic mod, I'm really looking forward to start a new survival game with minecolonies when you will have fixed this issue. ^^

[latest.log](https://github.com/ldtteam/Structurize/files/4466232/latest.log)

**Comment by Nightenom** [comment]
I need log from the personal build, it's the only version which might possibly work with optifine, please note few things: it's the first try to make it work (in 1.15), optifine is not ready for either 1.15 or forge (especially not ready for using in dev environment), optifine is closed source and we are having hard times when trying to make it compatible with structurize
I'm not able to help right now, I will get back to this at Wednesday morning (gmt +1)

**Comment by Nightenom** [comment]
Closed in favor of #112
