### ISSUE TITLE
LoaderExceptionModCrash server crash at boot with Optifine

### ISSUE THREAD

**Issue by LemADEC** [ldtteam/Structurize#13]
As reported here https://github.com/ldtteam/minecolonies/issues/3269, the OptifineCompat module is trying to load client side classes on a server, causing crashes.

**Comment by marchermans** [comment]
Remove optifine from your server side mods list, you can leave it in on the client side.

**Comment by kreezxil** [comment]
optifine is never a serverside mod, ever.
