### ISSUE TITLE
Not compatible with Optifine pre15

### ISSUE THREAD

**Issue by Residentj3553** [ldtteam/Structurize#130]
### Structurize version
Version: structurize-0.10.311
Launcher error:
"Structurize (structurize) encountered an Error during the sided_setup event phase"

- Not compatible with OptiFine_1.15.2_HD_U_G1_pre15

Almost positive it's on Optifine's end as it works fine without it but just letting you know.

**Comment by Raycoms** [comment]
I used the newest optifine 1.15 and it worked perfectly fine

**Comment by Nightenom** [comment]
@Residentj3553 please also post latest.log/crash log using pastebin site or similar next time

**Comment by Residentj3553** [comment]
Just used the latest Structurize version .313 and it works beautifully! Thanks!
