### ISSUE TITLE
Request: Colored Paper Walls

### ISSUE THREAD

**Issue by kedamono** [ldtteam/Structurize#132]
A request to have the ability to color each of the paper wall types by using a single paper wall block and any of the dyes in Structurize. 

This is primarily for cosmetic reasons, as many of us builders would like to have the option to add them to our builds for various aesthetic reasons.

**Comment by PowerSchill** [comment]
Would this include the timber frames or just the paper walls?

**Comment by kedamono** [comment]
Right now, it's just the paper walls that we're requesting.

**Comment by Nightenom** [comment]
Is this fine in DO now?
