### ISSUE TITLE
DatatypeConverter crashing the game while loading world

### ISSUE THREAD

**Issue by official-markus-maurer** [ldtteam/Structurize#135]
### Expected behavior
Getting into the world

### Actual behaviour
I am using JAVA 11 which is already supported by forges code. Not like 14+ etc.
While loading the world the game crashes with the error:

The game crashed whilst exception in server tick loop
Error: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### Steps to reproduce the problem

1. Be in world selection menu
2. Load a world
3. Somehow always crashes at 8% loading it
4. ... sad

### Logs:
Debug Log: https://pastebin.com/spCXensK
Latest Log: https://pastebin.com/PQcBEWkT
Crash Log: https://pastebin.com/fhTRyk9A
P.S. great work you guys are doing on Minecolonies. JAVA 11 uses way less RAM because of the Garbage Collector thats why i think its cool to have.

**Comment by ToMe25** [comment]
i wouldn't say it helps fix the issue, but it helps keep the issue trackers sorted.

**Comment by official-markus-maurer** [comment]
Gotta add that this also happens on windows 10, so it ain't some linux stuff

**Comment by ToMe25** [comment]
according to what i could find its because the used class is part of a module, no longer the base java as of java 9, so it should happen everywhere.

**Comment by Nightenom** [comment]
You're right ToMe25, several libs were removed from base "JRE" in java 9.
@RyuuSlayer, please use java 8, even though this crash should be relatively easy to fix, it's not forge who is blocking usage of java 9+. I may try later to make structurize more careless about java version, but no guarantees it will work

**Comment by Raycoms** [comment]
It might make sense to fix this already so that we're already compatible for the future for future java versions (if minecraft bumps up the java version one day)

**Comment by Strohtaler** [comment]
`DataTypeConverter` as part of package `javax.xml.bind` aka. JAXB was removed in Java 11, not just moved to another module ([Release Notes](https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#JDK-8190378))

**Comment by Gerflargle** [comment]
just adding in a note, with the last release of Forge (31.2) on May 15th, the Forge team did add in "preliminary support for Java 13+", so this kind of issue will likely increase in frequency as people try it out. 
Reference: 
https://www.minecraftforge.net/forum/topic/85620-forge-312-minecraft-1152/
