### ISSUE TITLE
Suggestion - Overlay for research tree

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/Structurize#146]
### Minecolonies version

Minecolonies version 0.11.933-ALPHA
Minecraft version 1.15.2
Forge version 3.11.77

### Expected behavior
Would it be possible to have a tooltip for the research tree resources. For ex, in the screenshot, I have no idea of what is the symbol. I though it was cooked pork but it does not.

Another possibility could be to have the 3 first letters of the object

Another one could be: on clicking on the research button (which must not be disabled anymore), a chat saying the item + quantity missing

![2020-05-12_09 02 53](https://user-images.githubusercontent.com/63854770/81661132-f7d2f380-943b-11ea-990e-f115dc4b3636.png)

**Comment by Raycoms** [comment]
This is actually a structurize issue for the GUI handling
