### ISSUE TITLE
Structurize cannot be detected by Forge

### ISSUE THREAD

**Issue by Gaiboru** [ldtteam/Structurize#151]
### Structurize version 

Version: 0.10.312 BETA, 0.10.313-RELEASE

### Expected behavior
The game should be running Minecolonies and Structurize 

### Actual behaviour
Without Minecolonies :
   The game loads normally but there is no Structurize in the mod tab of the game

With Minecolonies:
The minecraft screen shows this error even though Structurize is also placed in mod folder 
![image](https://user-images.githubusercontent.com/66151482/83318267-3c90c400-a25d-11ea-97d4-37d8610c5d45.png)

This is the fml-client-log
[fml-client-latest.log](https://github.com/ldtteam/Structurize/files/4705017/fml-client-latest.log)

### Steps to reproduce the problem
I used structurize of either version and minecolonies 0.11.804-RELEASE-universal

If you need any more details you can ask me again

**Comment by Raycoms** [comment]
Please use the latest alpha

**Comment by Raycoms** [comment]
of both
