### ISSUE TITLE
Modded blocks not using proper rotation

### ISSUE THREAD

**Issue by OuroborosBoy** [ldtteam/Structurize#156]
### Structurize version

Version: structurize-1.12.2-0.10.277-RELEASE.jar

### Expected behavior

- Schematics utilizing blocks from mods should be placed with the proper rotation compared to the rest of the structure the way vanilla blocks do. 

### Actual behaviour
-Structures with modded blocks will always place those blocks oriented based on compass direction. 

-When placing a structure with the building tool that uses modded blocks with rotation (Thaumcraft's Greatwood Logs, for example), those blocks will always have the same rotation no matter the direction that the structure as a whole faces. The blocks keep their rotation based on the compass direction rather than their rotation relative to the structure. This seems to be true for all kinds of modded blocks; Special furnaces, modded signs, chairs, tables, anything modded that can be placed facing different directions. 

-Side-note: Vanilla Armor Stands also seem to place incorrectly, but I can't tell what kind of logic is being used for their orientation... I haven't noticed it happening with any other vanilla block/tile entity, though. 

### Steps to reproduce the problem

1. Build a structure that uses modded blocks that can face different directions. I used Thaumcraft 6's Greatwood Logs as an example. ![2020-06-06_20 14 17](https://user-images.githubusercontent.com/36125235/83957230-448bcd80-a834-11ea-844b-7ab3bf1adc33.png)
2. Create a schematic of the structure using the scan tool.
![2020-06-06_20 14 41](https://user-images.githubusercontent.com/36125235/83957237-54a3ad00-a834-11ea-9863-e082d2da9d28.png)
3. Place a copy of the structure facing a different direction from the original using the Building Tool.
![2020-06-06_20 15 32](https://user-images.githubusercontent.com/36125235/83957238-5e2d1500-a834-11ea-8d82-8d5188684668.png)![2020-06-06_20 15 39](https://user-images.githubusercontent.com/36125235/83957240-61c09c00-a834-11ea-9dbb-e315176cd8e4.png)
4. ... Profit

![2020-06-06_20 17 06](https://user-images.githubusercontent.com/36125235/83957253-7e5cd400-a834-11ea-906c-b195ae2533de.png)
![2020-06-06_20 17 24](https://user-images.githubusercontent.com/36125235/83957255-83218800-a834-11ea-9ede-834526e15b82.png)
![2020-06-06_20 17 44](https://user-images.githubusercontent.com/36125235/83957264-95032b00-a834-11ea-820c-f523f6a1b381.png)

Expected behavior with vanilla logs: 
![2020-06-06_20 32 45](https://user-images.githubusercontent.com/36125235/83957361-dba55500-a835-11ea-974c-d2e2cf2385b7.png)
![2020-06-06_20 32 51](https://user-images.githubusercontent.com/36125235/83957362-dcd68200-a835-11ea-9479-82b5fced40a4.png)

**Comment by Raycoms** [comment]
This seems like a mod issue for me. We just place the blockstate. It seems thaumcraft might be doing something weird with their logs

**Comment by Nightenom** [comment]
1.12 is no longer maintained, if this issue persists in 1.15 or 1.16 feel free reopen
