### ISSUE TITLE
Could Not Serialize (Badly Compressed Packet)

### ISSUE THREAD

**Issue by CHead2000** [ldtteam/Structurize#157]
### Structurize version

Version: 0.10.321-ALPHA

### Expected behavior
Join server without being disconnected.

### Actual behaviour
Unable to join server. Disconnected immediately due to a Badly Compressed Packet.
I'm not sure if the issue is on my end or not, but hopefully you can interpret the logs and let me know. I thought Structurize might be causing this because the last line on the server log before I'm disconnected says something like "Could not Serialize....structurize....will not be sent to client!" Meanwhile, on my client log, the last line is something like "Removed colony views," so I feel like structurize/minecolonies may be causing this issue.

Server Log:
[latest.log](https://github.com/ldtteam/Structurize/files/4747832/latest.log)

Client Log:
[latest.log](https://github.com/ldtteam/Structurize/files/4747837/latest.log)

![2020-06-08_10 56 44](https://user-images.githubusercontent.com/65131882/84066412-e0801b00-a993-11ea-9880-72a60f8fabdc.png)

### Steps to reproduce the problem

1. Attempt to join brand new superflat world on server

**Comment by Raycoms** [comment]
Can't see anything in the log regarding to this, neither anything useful on client or server side. Do you have a particular big colony or so?

**Comment by CHead2000** [comment]
> Can't see anything in the log regarding to this, neither anything useful on client or server side. Do you have a particular big colony or so?

The world is brand new, so there are no colonies. So is the problem likely unrelated to Structurize/Minecolonies, then?

**Comment by Raycoms** [comment]
Most likely then.

**Comment by Nightenom** [comment]
Thanks for the log btw, looks like I have to fix optifine compatibility (but that won't solve your issue)
