### ISSUE TITLE
[1.15.2] Server crash when using block on the multi-piston

### ISSUE THREAD

**Issue by ocram9** [ldtteam/Structurize#162]
### Versions:
- structurize-0.10.322-ALPHA
- Minecraft 1.15.2
- Forge 31.2.19

### Description:
When using a full block on the multi-piston (fences and iron bars work fine) the server crashes and the block gets duplicated. 

- Crashlog: https://gist.github.com/ocram9/8b489fe0cab575c1a9c61d1cdb610010

### Steps to reproduce the problem:
1. Place a full block on the multi-piston (I tested it with a grass block and a spruce log).
2. Power the multi-piston and then unpower it.
3. Server crashes, when the server is restarted the block is duplicated.

**Comment by Raycoms** [comment]
Will be fixed in next release 323. (Already fixed in last PR)
