### ISSUE TITLE
Unable to start on server:

### ISSUE THREAD

**Issue by elijahalemard** [ldtteam/Structurize#163]
Minecraft 1.15.2 Release
Forge 1.15.2 
Latest alpha of both mine colonies and structurize.

### Expected behavior
Server to launch as it does without structurize or mine colonies. 

### Actual behaviour
14.06 01:33:51 [Multicraft] Starting server!
14.06 01:33:51 [Multicraft] Loaded config for "Custom JAR (Place "custom.jar" in base directory)"
14.06 01:33:51 [Multicraft] Updating eula.txt file
14.06 01:33:53 [Server] INFO 2020-06-14 02:33:53,181 main WARN Advanced terminal features are not available in this environment
14.06 01:33:53 [Server] INFO [32m[02:33:53] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 31.2.0, --fml.mcpVersion, 20200515.085601, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, nogui]
14.06 01:33:53 [Server] INFO [m[32m[02:33:53] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_211 by Oracle Corporation
14.06 01:33:53 [Server] INFO [m[32m[02:33:53] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
14.06 01:33:54 [Server] INFO [mInit CreativeCore coremods ...
14.06 01:33:55 [Server] INFO [32m[02:33:55] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
14.06 01:33:56 [Server] INFO [m[RandomPatches Entity Transformer]: Patching method: func_189511_e (func_189511_e)
14.06 01:33:56 [Server] INFO [RandomPatches Entity Transformer]: Patching method: func_70020_e (func_70020_e)
14.06 01:33:59 [Server] INFO [Endergetic Expansion]: Patching EndGatewayTileEntity#createExitPortal
14.06 01:34:00 [Server] INFO [RandomPatches CompoundNBT Transformer]: Transforming class: net/minecraft/nbt/CompoundNBT
14.06 01:34:00 [Server] INFO [RandomPatches CompoundNBT Transformer]: Patching method: equals (equals)
14.06 01:34:01 [Server] INFO [RandomPatches BoatEntity Transformer]: Patching method: func_70071_h_ (func_70071_h_)
14.06 01:34:01 [Server] INFO [Endergetic Expansion]: Patching EnderCrystalEntity#tick
14.06 01:34:09 [Server] INFO [33m[02:34:09] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
14.06 01:34:09 [Server] INFO [m[33m[02:34:09] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
14.06 01:34:09 [Server] INFO [m[33m[02:34:09] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
14.06 01:34:09 [Server] INFO [m[33m[02:34:09] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
14.06 01:34:09 [Server] INFO [m[33m[02:34:09] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
14.06 01:34:09 [Server] INFO [m[32m[02:34:09] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.15.2
14.06 01:34:09 [Server] INFO [m[RandomPatches PacketBuffer Transformer]: Transforming class: net/minecraft/network/PacketBuffer
14.06 01:34:09 [Server] INFO [RandomPatches PacketBuffer Transformer]: Patching method: func_150793_b (func_150793_b)
14.06 01:34:09 [Server] INFO [32m[02:34:09] [Server thread/INFO] [ne.mi.co.Co.vampirism/COREMODLOG]: Vampirism is hacking Forge ModList#getAllScanData to implement PR https://github.com/MinecraftForge/MinecraftForge/pull/6370
14.06 01:34:10 [Server] INFO [m[1;31m[02:34:10] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to load class com.ldtteam.structurize.Structurize
14.06 01:34:10 [Server] INFO java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
14.06 01:34:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:251) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$buildMods$27(ModLoader.java:231) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:233) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$19(ModLoader.java:189) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) [?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) [?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) [?:?] {re:classloading,pl:accesstransformer:B}
14.06 01:34:10 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 01:34:10 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO ... 32 more
14.06 01:34:10 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {}
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO ... 32 more
14.06 01:34:10 [Server] INFO [m[1;31m[02:34:10] [Server thread/FATAL] [ne.mi.fm.ja.FMLJavaModLanguageProvider/LOADING]: Unable to load FMLModContainer, wut?
14.06 01:34:10 [Server] INFO java.lang.reflect.InvocationTargetException: null
14.06 01:34:10 [Server] INFO at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
14.06 01:34:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:251) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$buildMods$27(ModLoader.java:231) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:233) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$19(ModLoader.java:189) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) [?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) [?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) [?:?] {re:classloading,pl:accesstransformer:B}
14.06 01:34:10 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 01:34:10 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO Caused by: net.minecraftforge.fml.ModLoadingException: Structurize has class loading errors
14.06 01:34:10 [Server] INFO java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 28 more
14.06 01:34:10 [Server] INFO Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 28 more
14.06 01:34:10 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 28 more
14.06 01:34:10 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {}
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 28 more
14.06 01:34:10 [Server] INFO [m[1;31m[02:34:10] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
14.06 01:34:10 [Server] INFO java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:78) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:251) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$buildMods$27(ModLoader.java:231) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:233) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$19(ModLoader.java:189) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
14.06 01:34:10 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 01:34:10 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO Caused by: java.lang.reflect.InvocationTargetException
14.06 01:34:10 [Server] INFO at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
14.06 01:34:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 24 more
14.06 01:34:10 [Server] INFO Caused by: net.minecraftforge.fml.ModLoadingException: Structurize has class loading errors
14.06 01:34:10 [Server] INFO java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
14.06 01:34:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 24 more
14.06 01:34:10 [Server] INFO Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
14.06 01:34:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 24 more
14.06 01:34:10 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
14.06 01:34:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 24 more
14.06 01:34:10 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.DistExecutor$SafeSupplier
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {}
14.06 01:34:10 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at com.ldtteam.structurize.Structurize.<clinit>(Structurize.java:26) ~[?:0.10.322-ALPHA] {re:classloading}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?] {}
14.06 01:34:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
14.06 01:34:10 [Server] INFO ... 24 more
14.06 01:34:10 [Server] INFO [m[1;31m[02:34:10] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /./crash-reports/crash-2020-06-14_02.34.10-server.txt
14.06 01:34:10 [Server] INFO [m[32m[02:34:10] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
14.06 01:34:10 [Server] INFO [m[32m[02:34:10] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
14.06 01:34:10 [Server] INFO [m[1;31m[02:34:10] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
14.06 01:34:10 [Server] INFO java.lang.IllegalArgumentException: Can not hotload overworld. This must be loaded at all times by main Server.
14.06 01:34:10 [Server] INFO at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[server-1.15.2-extra.jar:?] {}
14.06 01:34:10 [Server] INFO at net.minecraftforge.common.DimensionManager.initWorld(DimensionManager.java:229) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:198) ~[?:?] {re:classloading}
14.06 01:34:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 01:34:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 01:34:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 01:34:10 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:550) ~[?:?] {re:classloading,pl:accesstransformer:B}
14.06 01:34:10 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:676) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
14.06 01:34:10 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
14.06 01:34:11 [Server] INFO [m
14.06 01:34:11 [Multicraft] Server shut down (starting)
14.06 01:34:11 [Multicraft] Restarting crashed server in 10 seconds
14.06 01:34:11 [Multicraft] Server stopped

**Comment by ravenbuilder934** [comment]
What is your specific version of forge? Minecolonies 958 requires 31.2.8 or above to work, otherwise it crashes.

**Comment by someaddons** [comment]
he's using 31.2.0 thats why it doesnt work
