### ISSUE TITLE
Cactus Door duplicates on breaking

### ISSUE THREAD

**Issue by Nachtflame** [ldtteam/Structurize#165]
Version: 
structurize-0.10.324-ALPHA
minecolonies-1.15.2-0.11.961-universal
forge-31.2.20

### Expected behavior
Only get one dropped item on breaking the door.

### Actual behaviour
Drops 2, visually looks like Top & Bottom both drop a door each

### Steps to reproduce the problem
1. Place Cactus Door
2. Break Cactus Door
3. Observe seperate dropped doors from Top & Bottom block spaces
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://pastebin.com/TM6rr9sV
- crashlog: no crash, just duping

**Comment by Asherslab** [comment]
@ShadowProtocol should be as simple as looking at the vanilla door loot tables and duplicating it in the data genned loot tables for the cactus doors.
most likely the issue is that the upper half shouldn't drop an item but does currently

**Comment by ShadowProtocol** [comment]
That's exactly what it is. But I am not familiar with the auto data generation process. I am assuming it is better to create a loot table for it in main/resources than to override the generated one?

**Comment by Asherslab** [comment]
you can't override the generated one. you simply need to write a new one for the door specifically, it's just code that generates a json
