### ISSUE TITLE
Can't set pos 1 and crash on scan tool menu with ESC

### ISSUE THREAD

**Issue by Snoopydude** [ldtteam/Structurize#171]
Version:  structurize-0.13.4-ALPHA

### Expected behavior
Left clicking the scan tool on a block should set the 1st position

### Actual behaviour
Left click tries to break the block and gives no message as to setting the 1st position.
Right click sets pos 2 and right click on air shows the 1st position as 0,0,0.
I've tried combining with ALT, SHIFT, and CTRL but nothing changes. 
Once the menu is up from right clicking on air the game will crash if you hit ESC instead of the red x

[crash-2020-07-02_10.31.07-client.txt](https://github.com/ldtteam/Structurize/files/4865143/crash-2020-07-02_10.31.07-client.txt)

UPDATE
I did some testing and have learned the issue has something to do with my location the first time I used the scan tool.  I have found out that if you use the tool near 0,0,0 the first time you can then use it anywhere you want to.  I was trying to use it at -2500, 70, 2400 ish and it wouldn't set the first position.  I moved to 0,75,0 and it worked correctly.  I then went back to -2500, 70, 2400 and it now works correctly.

**Comment by Nightenom** [comment]
Really weird error, it doesn't show us what's the root issue

**Comment by Nightenom** [comment]
Probably redownload mod and forge
