### ISSUE TITLE
Crashes on custom schematic placement

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/Structurize#183]
### Structurize version

Version:  0.13.19-ALPHA

### Expected behavior

I successfully place the schematic and it gets built by the builder.

- 

### Actual behaviour

- 

I scan an existing build in the world and save it. When I attempt to place it in the world my game crashes with a `java.lang.IllegalArgumentException: 60000 > 53977` error. The associated log file is [here](https://pastebin.com/r9heahUx). I can provide the schematic if needed. 

* **Update**: ~In a single player world it doesn't crash, just doesn't do anything.~ I got it to place, but only if I don't intersect with anything but air.

**Comment by Raycoms** [comment]
Does this happen with any other schematic?

**Comment by Nightenom** [comment]
Providing debug/entire log might be helpful

**Comment by PowerSchill** [comment]
I put into a single player world and rescanned it after making a few changes. It seems to work.

**Comment by Nightenom** [comment]
Close this if you can't reproduce it anymore

**Comment by PowerSchill** [comment]
Will do, wasn't sure if you wanted to still look at the code.
