### ISSUE TITLE
using builders wand crashes client but not server

### ISSUE THREAD

**Issue by LuckyFalkor** [ldtteam/Structurize#189]
### Structurize version
Version: 0.13.35-ALPHA

minecraft version 1.15.2
forge: 31.2.33
minecolonies: 0.13.86-ALPHA-universal
### Expected behavior

right click with builders wand and get the interface to set decorations or huts

### Actual behaviour

using builders wand crashes the client, but not the server

### Steps to reproduce the problem

1. right click with builders wand
2. client crash

1. right click with hut (any hut) block
2. select "use builders wand" (instead of "place building")
3. able to use the interface
4. hit escape to be able to look at the blueprint
5. client crash

tried above steps via single player new world, and did not crash the client.
seems to happen only when trying via multiplayer server.
reinstalled mods in question on server, same outcome.

crash log: https://gist.github.com/LuckyFalkor/0651e9a8da9533c9de4e7fa805c7b36e
latest log: https://gist.github.com/LuckyFalkor/85f8dadb6065cc31056f61ab572825f8

**Comment by Raycoms** [comment]
downgrade to previous version of structurize. The newest is not compatible yet. We'll release an update for that today.
