### ISSUE TITLE
having a blueprint out in the world with a stash/postbox crashes the server

### ISSUE THREAD

**Issue by LuckyFalkor** [ldtteam/Structurize#190]
Structurize version

Version: 0.13.35-ALPHA

minecraft version 1.15.2
forge: 31.2.33
minecolonies: 0.13.88-BETA-universal
Expected behavior

right click with builders wand and get the interface to set decorations or huts
Actual behaviour

having a stash/postbox and blueprint out in the world for too long crashes the server, watchdog eventually restarts the server.
many errors like this:
Server thread/ERROR

SchematicRequestMessage: file "schematics/acacia/postbox0" not found
SchematicRequestMessage: file "schematics/birch/stash0" not found
SchematicRequestMessage: file "schematics/birch/postbox0" not found

Steps to reproduce the problem
build a postbox or stash then
have a blueprint, any blueprint out in the world before setting it to build

NOTE: i had postboxes/stashes in my colony and another player in his colony did not.
the issue came up for me when placing a blueprint in the world and but did not affect the other player when he did the same.
THEN i got rid of my postboxes/stashes and the issue cleared up for me.  

tried above steps via single player new world, and did not crash the client.
seems to happen only when trying via multiplayer server.
reinstalled mods in question on server, same outcome.

server crash log: https://gist.github.com/LuckyFalkor/9b73f9e2fdcb38b612cd89ff916a0221

**Comment by Raycoms** [comment]
How did you reproduce it? I didn't get the "blueprint out in the world" part.

**Comment by LuckyFalkor** [comment]
i right click with the builder wand and select a blueprint like decoration-wall of some type.
while that GUI is up and i am able to reposition the blueprint is visible in the world (so i can see where i am placing it, etcetera).
it is during the time the blueprint is visible that i see all the errors if i have a postbox or/and stash in my colony.

**Comment by Raycoms** [comment]
Fixed in next version
