### ISSUE TITLE
Structurize-0.13.36-ALPHA in Valhelsia 3- 3.0.10 is breaking recipes

### ISSUE THREAD

**Issue by ProfMidnightX** [ldtteam/Structurize#191]
### Structurize version

Version: 0.13.36-ALPHA in Modpack Valhelsia 3- 3.0.10 

### Expected behavior

Botania flowers not turning into structurize blocks. Refined Storage raw processor crafting should be working.

### Actual behaviour

Getting wrong recipe crafts, some recipes don't work.
- 
I've installed the newest Valhelsia 3 update with structurize-0.13.36-ALPHA. In-game I can not turn botania flowers into petals (no petal recipe works) and some flowers turn into structurize blocks. Refined Storage raw processor crafting is also broken.

![image](https://user-images.githubusercontent.com/60618856/89234176-aaee5b80-d5eb-11ea-8773-a0bce71aaab0.png)

### Steps to reproduce the problem

1.  
Place any botania flower in the crafting table || Try to craft any Refined Storage raw processor
2. 
3. 
You sometimes get structurize blocks like in the image above. || Raw Processor crafting not working
4. ... Profit
**I've disabled structurize-0.13.36-ALPHA in the mods folder and everything is working as expected!**

**Comment by Raycoms** [comment]
That mod: polymorph

causes this.
