### ISSUE TITLE
Build Tool should warn player about missing survival capabilities

### ISSUE THREAD

**Issue by suduko666** [ldtteam/Structurize#193]
### Structurize version
mod = structurize-0.13.32-RELEASE.jar
mc = 1.16.1
forge = forge-32.0.33
### Expected behavior
build tool gui pops up and i can interface with it

### Actual behaviour
build tool gui flashes for a second then closes itself nothing i do changes that.

### Steps to reproduce the problem
attempt to use the build tool

**Comment by Raycoms** [comment]
Are you using optifine?

**Comment by suduko666** [comment]
no Structurize is the only mod

**Comment by Raycoms** [comment]
Then you need to be in creative mode to use it.

**Comment by Raycoms** [comment]
The only non creative way to build things with it is with Minecolonies

**Comment by suduko666** [comment]
so if ur not in creative the gui itself wont even stay open

**Comment by Raycoms** [comment]
yes

**Comment by suduko666** [comment]
ah thats unfortunate but alright th an error msg saying so would be awesome though so as to avoid this situation

**Comment by Raycoms** [comment]
I adjusted the issue name then,

**Comment by suduko666** [comment]
oh alright th
