### ISSUE TITLE
v0.13.35-ALPHA: using building tool freezes game (optifine)

### ISSUE THREAD

**Issue by boneskull** [ldtteam/Structurize#194]
### Structurize version

Version: v0.13.35-ALPHA

Also:
- OptiFine_1.15.2_HD_U_G1_pre30 (also occurs on pre23)
- MineColonies v0.13.93-ALPHA
- (see logs)

### Expected behavior

- Ability to view preview when right-clicking with building tool

### Actual behaviour

- The game "freezes" (does not crash; no crash log generated).  Many, many opengl errors.  Had to alt-F4 out.  Does not occur on v0.13.31-RELEASE

- `latest.log`: https://gist.github.com/boneskull/75b5349ac46d0b424588351d736d6d5b
- Screenshot: 
![Annotation 2020-08-05 223335](https://user-images.githubusercontent.com/924465/89494841-e44dd500-d76b-11ea-849f-2f5a811c1571.png)

### Steps to reproduce the problem

1. Install OptiFine (no OptiForge used)
1. Open a world with a colony using MineColonies v0.13.70-ALPHA and Structurize v0.13.31-RELEASE or create one
1. Assert that you can use the building tool and view a preview, such as it is
1. Save & quit
1. Update to latest MineColonies 0.13.93-ALPHA and the requisite Structurize v0.13.35-ALPHA
1. Re-open world
1. Attempt to use build tool
1. Freeze occurs

Notes:

- No files in the `structurize/cache`, `structurize/scans` or `structurize/schematics` folders.

This is interesting during startup:

```
[22:27:44] [modloading-worker-6/ERROR]: Optifine found. But could not access related methods.
java.lang.NoSuchMethodException: net.optifine.shaders.Shaders.nextEntity(net.minecraft.entity.Entity, net.minecraft.client.renderer.IRenderTypeBuffer)
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_51]
	at com.ldtteam.structurize.optifine.OptifineCompat.setupReflectedMethodReferences(OptifineCompat.java:126) ~[?:0.13.35-ALPHA]
	at com.ldtteam.structurize.optifine.OptifineCompat.intialize(OptifineCompat.java:63) [?:0.13.35-ALPHA]
	at com.ldtteam.structurize.event.LifecycleSubscriber.onClientInit(LifecycleSubscriber.java:61) [?:0.13.35-ALPHA]
	at net.minecraftforge.eventbus.ASMEventHandler_565_LifecycleSubscriber_onClientInit_FMLClientSetupEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) [?:31.2]
```

**Comment by boneskull** [comment]
If this was released in v0.13.19-ALPHA, it does not seem to have fixed the issue.  The "could not access related methods" log msg has been suppressed, however.

**Comment by boneskull** [comment]
latest log: https://gist.github.com/boneskull/ac6817cbf650412fa7a40d7c098355d8

**Comment by Nightenom** [comment]
Please provide shader you are using, couldn't reproduce using vanilla nor few shaders

**Comment by boneskull** [comment]
BSL v7.1.05p2

maybe it's an incompatible setting in there...

**Comment by boneskull** [comment]
`optionsshaders.txt`:

```
#Sat Aug 01 10:57:34 PDT 2020
shaderPack=BSL_v7.1.05p2.zip
antialiasingLevel=0
normalMapEnabled=false
specularMapEnabled=false
renderResMul=1.0
shadowResMul=0.70710677
handDepthMul=0.125
cloudShadow=false
oldHandLight=default
oldLighting=default
tweakBlockDamage=false
shadowClipFrustrum=true
TexMinFilB=0
TexMinFilN=0
TexMinFilS=0
TexMagFilB=0
TexMagFilN=0
TexMagFilS=0
```

`optionsof.txt`:

```
ofFogType:2
ofFogStart:0.8
ofMipmapType:0
ofOcclusionFancy:false
ofSmoothFps:false
ofSmoothWorld:false
ofAoLevel:1.0
ofClouds:0
ofCloudsHeight:0.0
ofTrees:0
ofDroppedItems:0
ofRain:0
ofAnimatedWater:0
ofAnimatedLava:0
ofAnimatedFire:true
ofAnimatedPortal:true
ofAnimatedRedstone:true
ofAnimatedExplosion:true
ofAnimatedFlame:true
ofAnimatedSmoke:true
ofVoidParticles:true
ofWaterParticles:true
ofPortalParticles:true
ofPotionParticles:true
ofFireworkParticles:true
ofDrippingWaterLava:true
ofAnimatedTerrain:true
ofAnimatedTextures:true
ofRainSplash:true
ofLagometer:false
ofShowFps:false
ofAutoSaveTicks:3600
ofBetterGrass:2
ofConnectedTextures:3
ofWeather:true
ofSky:true
ofStars:true
ofSunMoon:true
ofVignette:1
ofChunkUpdates:1
ofChunkUpdatesDynamic:false
ofTime:0
ofAaLevel:0
ofAfLevel:1
ofProfiler:false
ofBetterSnow:false
ofSwampColors:true
ofRandomEntities:true
ofCustomFonts:true
ofCustomColors:true
ofCustomItems:true
ofCustomSky:true
ofShowCapes:true
ofNaturalTextures:false
ofEmissiveTextures:false
ofLazyChunkLoading:false
ofRenderRegions:false
ofSmartAnimations:true
ofDynamicFov:true
ofAlternateBlocks:false
ofDynamicLights:1
ofScreenshotSize:1
ofCustomEntityModels:true
ofCustomGuis:true
ofShowGlErrors:false
ofFastMath:false
ofFastRender:false
ofTranslucentBlocks:0
ofChatBackground:0
ofChatShadow:true
ofUseVbo:true
key_of.key.zoom:key.keyboard.c
```

**Comment by boneskull** [comment]
thanks for looking at this!  really appreciate the work on these mods.

**Comment by Nightenom** [comment]
So, it looks like optifine/shader issue, please be aware of the announcement at curseforge page
<https://www.curseforge.com/minecraft/customization/bsl-shaders>

**Comment by boneskull** [comment]
hmm, okay, didn't realize that it had issues, thanks.  I'll switch shaders

**Comment by boneskull** [comment]
it happens with Sildurs Vibrant shaders too

**Comment by ravenbuilder934** [comment]
Might be optifine, not the specific shader

**Comment by Dokharus** [comment]
Same issue with SEUS Renewed 1.0.1 on Optifine HD_U_G1_pre30 with Structurize 0.13.39 on MC 1.15.2

**Comment by Nightenom** [comment]
All I gonna say is I have tried Nostalgia_v2.3, projectLUMA+-+v1.32, VPlus_v2.2a in 1.16/1.15 and they all worked.
So the others are probably optifine/shaders faults, very unlikely being something wrong on our end. Few of bugs I've encountered were problematic because of shader being tightened to vanilla things (thus unusable by mods)

**Comment by boneskull** [comment]
nostalgia doesn't work for me either. gonna try internal shaders / no shaders... I wonder what changed in that structurize alpha that's making it hit the bad code path though, since I was almost entirely issue-free before

**Comment by boneskull** [comment]
OK, so, it works with optifine but with shaders _off_.  @Dokharus What gpu do you have?  I have an RTX 2070 super, latest drivers...

**Comment by Nightenom** [comment]
Guys, try latest version, should be much better

**Comment by Nightenom** [comment]
But still, don't expect 1.14 shaders to work in 1.15, same applies to alpha releases

**Comment by boneskull** [comment]
it works!!  😍
