### ISSUE TITLE
Tooltips for the buttons in the build tool GUI

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/Structurize#201]
Suggestion from Discord

### Expected behavior
> I have a suggestion for structurize: 
> hover tooltips for the buttons in the build tool GUI
(https://discord.com/channels/139070364159311872/240841248750043137/726186538869850155)

#### Specifications
-

# Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Optionally add a comment with any insight and background you have that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Done somewhen in past
