### ISSUE TITLE
[Bridge fixed][Causes preview crash] ItemGolem requires ServerWorld for entity constructing, other entities may follow up

### ISSUE THREAD

**Issue by juliashepp** [ldtteam/Structurize#202]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- Structurize Version: 0.13.43-ALPHA
- MineColonies Version (if related bug):
- Related Mods and their Versions: Forge 32.0.108

## Expected behavior

When I right click the building tool on a solid block, the GUI should pop up.
## Actual behavior

When I right click the building tool on a solid block, the game immediately crashes and shows the error "The game crashed whilst loading entity nbt Error: java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld".

<img width="553" alt="Screen Shot 2020-08-09 at 5 00 13 PM" src="https://user-images.githubusercontent.com/69439347/89850718-bd164f80-db3f-11ea-9625-b68694314372.png">
## Steps to reproduce the issue

1. Stand in front of a solid block
2. Right click the block while holding the building tool
3. The game should immediately crash

### Logs

- latest.log:  https://gist.github.com/juliashepp/7560fb7d035b8c60c5cf00e768512338
- crashlog:  https://gist.github.com/juliashepp/d3af1a74961e327ef48a9f9ef69aa5bf

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Gonna leave this open since it's only temporary fix which will make IronGolem (problematic entity) not render in structure previews.
Please try 0.13.44-ALPHA, it should not crash anymore

**Comment by juliashepp** [comment]
> Gonna leave this open since it's only temporary fix which will make IronGolem (problematic entity) not render in structure previews.
> Please try 0.13.44-ALPHA, it should not crash anymore

thank you so much!!
