### ISSUE TITLE
tooltip not rendering correctly in scrolling list

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/Structurize#206]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 
- Structurize Version:
- MineColonies Version (if related bug):
- Related Mods and their Versions:

## Actual behavior

https://cdn.discordapp.com/attachments/572112548917280788/748798551798317086/unknown.png

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Super confused by this

**Comment by marchermans** [comment]
The cause of this is the Scissoring that is applied when rendering the list.
The tooltip is rendered during the draw phase of the list, whoes rendering area has a limit that is applied via scissoring. This causes the GPU to discard any vertex outside of the area which is defined by the scissoring settings of the list.

This can be easily fixed, by doing 3 things:
1) Store the current scissoring area, and disable the scissoring.
2) Set the zLevel to a high value
 --> Now draw the tooltip
3) Reset the zLevel, and enable scissoring again with the previous range.

**Comment by Raycoms** [comment]
We draw the tool tip after everything else and have a high z value already
