### ISSUE TITLE
GUI for build tool not showing up in survival

### ISSUE THREAD

**Issue by JayGame45** [ldtteam/Structurize#209]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- Structurize Version: 0.13.58
- MineColonies Version (if related bug):
- Related Mods and their Versions:

## Expected behavior
GUI for build tool use in survival

## Actual behavior
When trying to use build tool in survival the GUI opens and closes immediately

If you have any videos or images relating to the issue, please post them here as well.

## Steps to reproduce the issue

1. Set gamemode to survival if not already
2. Get build tool and try to use it
3. When trying to use the build tool the GUI should open and close immediately on the screen 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This is intentional, as there isn't anything you can do with the build tool in survival (unless you have MineColonies installed).
