### ISSUE TITLE
Vertical slabs do not rotate when using build tool

### ISSUE THREAD

**Issue by AkGamerRo** [ldtteam/Structurize#212]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- Structurize Version: structurize-0.13.44-ALPHA
- MineColonies Version (if related bug):
- Related Mods and their Versions: 
DoubleSlabs-1.16-3.3.3
Quark-r2.2-262

## Expected behavior

Vertical slabs should change orientation when rotating a structure, in order to keep it's design intact.

## Actual behavior

Vertical change positions while rotating a stucture while keeping their orientation, making them unusable for making structures that need to be replicated with structurise or Minecolonies(via builer).

video: https://youtu.be/FilJKyFjJSI

## Steps to reproduce the issue

1.  Make a structure containing vertical slabs and scan it using the scan tool
2.  Use the build tool to view and place rotated variants of the structure.
3.  Vertical slabs do not change orientation with the structure.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I'd first of all ask the creator of the vertical slabs about it. Because we just use rotate and mirror functions on them like we do on all kind of other vanilla blocks wher eit works fine?

**Comment by marchermans** [comment]
Yeah i checked, not a Structurize issue.
We invoke the rotate and mirror methods MC providers us....

Nothing we can do.
