### ISSUE TITLE
Selecting Random with shape tool causes CTD

### ISSUE THREAD

**Issue by WarpedFoxx** [ldtteam/Structurize#213]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- Structurize Version:structurize-0.13.64-ALPHA.jar
- MineColonies Version (if related bug):x
- Related Mods and their Versions:x

## Expected behavior
Not Entirely clear, expected it to randomly choose a shape from the list, or randomly scatter blocks in <x> by <x>

## Actual behavior
Selecting the random option in the shape tool instantly causes the game to hang, and shortly after (<15 seconds) the game crashes to desktop

## Steps to reproduce the issue

1. Open shape tool
2. Select Random shape
3. Crash to desktop

### Logs

- latest.log: https://gist.github.com/WarpedFoxx/cc3ea202cfd397faffc31b51d48ccb07
- crashlog: ^

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Weird, seems like it didn't inject the dependency as it should.

**Comment by Raycoms** [comment]
@OrionDevelopment apparently gradle broke?

**Comment by marchermans** [comment]
@Raycoms This is structurize, what is being injected here?
We would need todo shading.....

**Comment by Raycoms** [comment]
The Mathparser library

**Comment by marchermans** [comment]
For what are we using this library?
Also note Jar in Jar is not working for months now.....

**Comment by Raycoms** [comment]
Shape generation from equation

**Comment by marchermans** [comment]
..... Yeah that is not working.
You need to shade the library at the moment.
Aequivaleo also needs todo that for JGraphT.

Will get to it in the weekend.

**Comment by Raycoms** [comment]
kk, great

**Comment by marchermans** [comment]
Fixed in:
- 1.15.x: 0.13.70-ALPHA
- 1.16.x: 0.13.71-ALPHA
