### ISSUE TITLE
Placed orientation of some Timber frame blocks not correct

### ISSUE THREAD

**Issue by TheOrionsun** [ldtteam/Structurize#214]
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- Structurize Version: structurize-0.13.64-ALPHA.jar
- MineColonies Version (if related bug): Not loaded for testing....
- Related Mods and their Versions: None loaded for testing....

Note: Working with "Spruce Paper Timber Frames" and "Spruce Dark Oak Timber Frames" as a reference to see if more than just one block group (Paper or Dark Oak) is at issue.
 
## Expected behavior

When placing the "Side Framed Spruce Paper Timber Frame" block, it will be placed on its' side rather than on its' bottom. The Expected behavior would be that the block is placed in the world as the item image looks. In this case it shows the orientation of the block with spruce frames on the sides, and that one could click anywhere on the target block to place it and not just on the outside edge.

## Actual behavior

When placing the "Side Framed Spruce Paper Timber Frame" block, it will be placed on its' side rather than on its' bottom. The only way for it to place down correctly is to be standing level with the target block you want it to be placed it on and click on the very outside edge of that block closest to you. The first three blocks in this set place ok clicking anywhere on target block. Several blocks in this set also have the same issue.

## Steps to reproduce the issue

1.  Place "Side Framed Spruce Paper Timber Frame" block in the center of target block.
2.  Place "Side Framed Spruce Paper Timber Frame" block at very edge of target block.
3.  You should see what is happening....

### Logs  **"No Logs - Not a crash issue"**

- latest.log: 
- crash-log: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
* If someone has time could you please try to place a "Side Framed Spruce Paper Timber Frame" block and see if you have this issue.

Thank you,

**Comment by Nightenom** [comment]
Stale, probably fixed, if not please reopen
