### ISSUE TITLE
Entry-level task suggestions

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/Structurize#215]
Hi, this is a suggestion board for people wanting something to work on. 
If you pick one of these, please create a new issue and assign it to yourself.

If you have other ideas about additions, please contact us on our [Discord](https://discord.minecolonies.com).

- [ ] Add compat layer to translate `.schematic` to our `.blueprint` files.
- [x] Add new timberframe/shingle/paper wall variants for the new 1.16 blocks
- [x] Fix up paperwalls to have all types.
- [ ] ReplaceRandom option for scan tool replacement (instead of replace all)

**Comment by ravenbuilder934** [comment]
October is over, should this be closed?
