### ISSUE TITLE
Game crash when start up

### ISSUE THREAD

**Issue by pugsarepeople2** [ldtteam/Structurize#221]
### Prerequisites 

- x[ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- Structurize Version:Alpha 13.64
- MineColonies Version (if related bug): 13.257 Alpha
- Related Mods and their Versions: none

## Actual behavior
 Me and my friend found that this mod crashes HIS game everytime he starts it up. It only happens to me. I have the exact version and we both have tried all of the other versions for 1.15.2 but the same things happened. The crash report says this: The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game
Exit Code: -1

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
We need your logs

**Comment by Raycoms** [comment]
missing logs, closing
