### ISSUE TITLE
Pasting schematics doesn't copy the multiblock settings

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/Structurize#227]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- Structurize Version: 66 alpha
- MineColonies Version (if related bug): Non-related
- Related Mods and their Versions: Non-related

## Expected behavior
After changing the multiblock settings and copypasting the schematic the multiblocks are in, the settings in the copypasted version should be the same as in the original version.

## Actual behavior
The multiblock settings revert to the default. 

## Steps to reproduce the issue

1. Change the multiblock settings
2. Copypaste the multiblocks
3. Check the settings on the copypasted version of the multiblocks

### Logs

- latest.log: 
- crashlog: 

### Notes
I haven't tested if this happens when the builder builds a schematic with multiblocks

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Stale, probably fixed, if not please reopen
