### ISSUE TITLE
Bug report, 04/11/2020, crash when placing colony.

### ISSUE THREAD

**Issue by Gimmie053** [ldtteam/Structurize#228]
### Prerequisites 

- [ X ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.15.2
- Structurize Version: 0.13.94
- MineColonies Version (if related bug): 0.13.359
- Related Mods and their Versions: Not related to any other mods, I believe.

## Expected behavior
If the feature was working as intended the Supply camp would place as normal on the floor in whatever style chosen.

## Actual behavior
As soon as the supply camp is placed the game crashes.

As soon as the supply camp was placed down it'd bring up the dirt block background and say 'saving world' as if you were saving and quitting from singleplayer and then it'd crash from desktop.

The issue was fixed by restarting the server however for reference I'm making this bug report anyway.

## Steps to reproduce the issue

1. Get a supply camp (not tested with boat when this issue was active)
2. Try to place it down on the ground
3. Above mentioned issue ensues

### Logs

The below logs include the latest.log, crash log and the servers log. The most notable seemed to be that the server was giving an error that stated 'File jar resolve FAILED for: Schematics/wooden/builder1.blueprint'

Player in question is called 'mmggy'

https://gist.github.com/Gimmie053/2f3bd4940bb883b03b32d963ba2295a1

### Notes

None
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I have a feeling that something corrupted on serverstart here which stopped loading ALL schematics which then caused the above.
You said it was fixed when restarting the server? Can't you reproduce it anymore?

**Comment by ravenbuilder934** [comment]
Closed as stale (and fixed by a restart)
