### ISSUE TITLE
Not pasted my shema on server

### ISSUE THREAD

**Issue by Sanysvo** [ldtteam/Structurize#231]
### Prerequisites 

- [x] I am running the latest **RELEASE** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- Structurize Version: structurize-0.13.31-RELEASE.jar 
- MineColonies Version (if related bug):
- Related Mods and their Versions: Forge 31.2.33

## Expected behavior
I want paste my scanned building on server (i own this server and have creative)

## Actual behavior
I scanned and save building on my server and want copy it. But when i push Paste button in building tools nothing happens. 
In mod config on server i allow users shematics

## Steps to reproduce the issue

1. Scanned building on server
2. Save scan
3. Try paste it on server

### Logs

- latest.log: 
- crashlog: 

### Notes

---

**Comment by ravenbuilder934** [comment]
Try updating to the latest alpha and checking if it still occurs

**Comment by Sanysvo** [comment]
> Попробуйте выполнить обновление до последней альфа-версии и проверьте, происходит ли это по-прежнему

Why use last alpha if realese is newest?

**Comment by Raycoms** [comment]
No your release is extremely old
