### ISSUE TITLE
Build tool - Floor Plan

### ISSUE THREAD

**Issue by RangeCreed** [ldtteam/Structurize#248]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version:  0.9.13

## Is your feature request related to a problem?
 N/A

## Enhancement or Change description
 I would like to suggest adding another option into the build tool. This option would allow you to place a floorplan off the currently selected schematic using the construction tape. This would be placed exactly as it is currently but will not call the builder function. This can be manually destroyed or deleted like a normal structure via towncenter

### Notes or related things
 I know you can currently do workarounds for this exact thing but it requires many more steps. I did notice someone had started on a column under Asian builds for floorplans, but not only does this clutter the already overcluttered build menu but gives more workload everytime a new schematic is added.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
If I get you right, you want something like a town plan, which would be minecolonies addition rather than structurize

**Comment by RangeCreed** [comment]
Hey I wasn't too sure where to place this as I thought it would be a gui change for structurize ^^
