### ISSUE TITLE
Disconnected on join multiplayer server.

### ISSUE THREAD

**Issue by WaterMelwin** [ldtteam/Structurize#251]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version: 0.13.104 Alpha

## Problem description
Trying to play multiplayer on my server every time i try to join i get disconnected and console says Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@503ee031 (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!
In Minecraft says badly compressed packet size.

### Notes or related things
I have other mods installed but console says nothing to tell me if they are causing the problem.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by WaterMelwin** [comment]
https://pastebin.pl/view/f829b24a (server log) https://pastebin.pl/view/d85b7746 (client log)

**Comment by Raycoms** [comment]
```
com.ldtteam.structurize.commands.arguments.MultipleStringArgument@503ee031 (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!
```

this is certainly not related to the login problem. But I'll check the log for more info.

**Comment by Raycoms** [comment]
Nothing in the logs either pointing to us as the culprits.
Please make sure: The minecolonies + structurize versions are the same on both sides.
You can try to execute /mc colony requestsystem-reset-all from the commandline to see if that helps anything
