### ISSUE TITLE
Scanning Schematics Auto Fill Name

### ISSUE THREAD

**Issue by thaylar** [ldtteam/Structurize#254]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16
- Structurize Version: latest or older

## Is your feature request related to a problem?

- The auto-fill name of the last scanned schematic creates nested folders, possibly endlessly?  I only tested it three times.
- It just keeps throwing in the file structure every new scan as noted in image 2, where the schematic name gets cut off. By the fourth iteration the auto-fill feature hits the character limit throwing "scans/new" in every time.
- The auto-fill feature creates more work when scanning schematics as the file structure adds to the character limit of the name box without adding anything useful and _must_ be deleted anyways due to the above duplication bug.

## Enhancement or Change description

- Remove the auto-fill of the prior scanned schematic feature.
- At the least, remove the file structure from the auto-fill feature.
- if any feature would be useful, it would be to create a UI similar to the deco controller. Maybe the schematic name can be saved to the scan tool and then the user only needs to update the number associated with the file.

### Notes or related things
Don't know why this became a thing. Removing it would probably be the easiest and best option.

---
## Viewers
![Untitled](https://user-images.githubusercontent.com/59156985/103479948-bca07e80-4d96-11eb-83d7-ae9fafb45769.png)
![Untitled2](https://user-images.githubusercontent.com/59156985/103480146-23726780-4d98-11eb-996f-3daeb91d4717.png)

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
_Would be rather a bug issue_

I have seen this but haven't paid enough attention to it

**Comment by thaylar** [comment]
It may be a bug, but it's also a preference that scanning schematics was easier when it didn't save anything to the box.

**Comment by Nightenom** [comment]
Autofill removed
