### ISSUE TITLE
Replacing redstone ore with bedrock in a scan results in crash.

### ISSUE THREAD

**Issue by Moleculor** [ldtteam/Structurize#262]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version: 110

## Expected behavior
Don't crash.

## Actual behavior
Try to replace redstone ore with bedrock. Game crashes.

## Steps to reproduce the issue

Scan something that contains redstone ore.
Use the scan tool to replace the redstone ore with bedrock.

### Logs

- latest.log: https://gist.github.com/Moleculor/914c1ddf4f137e25bb2cd88587450b76
- crashlog: https://gist.github.com/Moleculor/29d2429695a0f373504d321fa91e8413

### Notes

Most of the logs are actually from v104, but I did replicate it in v110 and that crash log is also provided.

**Comment by Nightenom** [comment]
Duplicate #261, I'm aware of it but don't have time right now to fix it, fix should arrive in 7-10 days
