### ISSUE TITLE
1.16.5 Structurize not compatable

### ISSUE THREAD

**Issue by thepriz** [ldtteam/Structurize#265]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 Forge 36.0.1
- Structurize Version: 0.13.104-ALPHA
- MineColonies Version (if related bug): 0.13.570-ALPHA
- Related Mods and their Versions:

## Expected behavior

I would expect that Minecraft would actually startup.

## Actual behavior

Minecraft does not load and an error is displayed:
"Structurize (structurize) has failed to load correctly java.lang.RuntimeException: Missing some newest data versions. Please update."

I can't update because Minecolonies requires 0.13.104

## Steps to reproduce the issue

1. Upgrade to Forge 36.0.1
2. Start Minecraft
3. This error occurs

### Logs

- latest.log: https://gist.github.com/thepriz/047cc4cd029510e7c1c368739476d121.js
- crashlog:  https://gist.github.com/thepriz/dd2debd45923c70778dc2314bbfe9c18.js

### Notes

I tried to update to Strucurize 0.13.111 but Minecolonies requires 0.13.104

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Don't ask about updates for new vanillas.

**Comment by thepriz** [comment]
I wasn't asking about updates for new vanillas. As a software engineer by profession for over 20 years, I was reporting an issue with all the data I collected to try and help with troubleshooting.

Lesson Learned you don't want help...

**Comment by ravenbuilder934** [comment]
Well, this issue was caused when updating to a Minecraft version Structurize doesn't support
Asking for it fixed *is* asking for an update to a new vanilla version

**Comment by thepriz** [comment]
Interpret it how you want. I know this is an active project and understand it may not have been updated to the new version yet. I know that it most likely will be updated to the new version. I reviewed the issue I created and saw nowhere did I ask for an update, I assumed this would just happen in due course. This is a public issue tracker. I reported an issue, to help with being able to track down the issue for the update. That is what an issue tracker is for. Obviously, the programmers of this great project don't want the help so I won't contribute anymore time collecting the information and wasting my time trying to help.

**Comment by Raycoms** [comment]
We always appreciate input. However, since it's an active project we're
obviously aware of the new version and are working on it.

**Comment by imanairconditioner** [comment]
This is happening to me too. Minecolonies 0.13.437, Structurize 0.13.96 and Forge 36.1.0.

**Comment by ravenbuilder934** [comment]
*You* need to update to the latest alpha (or beta). the releases are months out of date
