### ISSUE TITLE
structurize-0.13.104-ALPHA-universal.jar not working in 1.16.5 so can't use minecolonies

### ISSUE THREAD

**Issue by FearAK** [ldtteam/Structurize#266]
Updated my game to 1.16.5 but can't use minecolonies since the structurize version you need doesn't work in 1.16.5 https://gyazo.com/4ba1addb3a1afd2606e3d52fe1212ff2

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/issues/6383

**Comment by FearAK** [comment]
So it's just not gonna work for 1.16.5 for a while?

**Comment by ravenbuilder934** [comment]
Few days, yeah

**Comment by FearAK** [comment]
Alright, thanks
