### ISSUE TITLE
Error: java.lang.ArrayIndexOutOfBoundsException: -176

### ISSUE THREAD

**Issue by Camreyn** [ldtteam/Structurize#268]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.

- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version: - structurize-0.13.104-ALPHA-universal
- MineColonies Version (if related bug): 2.4
- Related Mods and their Versions: Everything within the mod pack on curseforge, I can list those if absolutely necessary, no additions were made. 

## Expected behavior

Client would not crash upon entering server.

## Actual behavior

Client crashing when connecting to server with the following error: 

The game crashed whilst tesselating block model
Error: java.lang.ArrayIndexOutOfBoundsException: -176
Exit Code: -1

## Steps to reproduce the issue

I am unsure of what started it but I was placing blackstone near my immersive engineering blocks and that was it, nothing odd.  

### Logs

- latest.log: https://gist.github.com/TheEndOfYoRHa/9d0057c674aeb56eff982799538314be
- crashlog: https://gist.github.com/TheEndOfYoRHa/88c215743c816374cd16ec96e6d4bdda

### Notes
Not to sound desperate but this is the first time in a long time my SO and I found something we both enjoy together, and we are both facing this issue.  We really do not want to lose this world. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I can't see anything in the log pointing to this issue. Can you do a quick test and disable smooth lighting before joining the world?

**Comment by Camreyn** [comment]
It let me join the world after turning that off.  What would fix the lighting?

**Comment by Camreyn** [comment]
Turning it on while in the world crashes it immediately though, just thought I would add that.

**Comment by Raycoms** [comment]
okay, this is a problem with immersive engineering then and not with minecolonies or structurize. They will release an update soon for that. In the meanwhile you'd have to take down the immersive engineering posts (those cause that).
