### ISSUE TITLE
Crash on server/client start-up 1.16.5 (Structurize)

### ISSUE THREAD

**Issue by pirateorion** [ldtteam/Structurize#269]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- Structurize Version: structurize-0.13.100-RELEASE-universal
- MineColonies Version (if related bug): minecolonies-0.13.480-BETA-universal
- Related Mods and their Versions: Forge 1.16.5 - 36.0.1

## Expected behavior
Client/Server start up correctly

## Actual behavior
Crashes during start-up (see attached crash report)

## Steps to reproduce the issue

1. Install new minecraft instance with latest Forge
2. Install latest Strucurize and Minecolonies (or just Structurize)
3. Run server/client

### Logs

- latest.log/crashlog: https://gist.github.com/pirateorion/adbf187a4b5405d182e5d2340756245e

### Notes
None

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
100 is only for 1.16.4. You need to use structurize 113 and minecolonies 574 alphas (the alphas aren't any less stable than the releases)
