### ISSUE TITLE
Add a way for non-modders to add schematics to structurize

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/Structurize#276]
### Context 

- Minecraft Version: 1.16
- Structurize Version: recent

## Is your feature request related to a problem?

Resource pack makers can't add new schematics without making a mod for it

## Feature description

Add client config and use [StructureLoadingUtils.getOriginfolders()](https://github.com/ldtteam/Structurize/blob/7cf1a84c80ec3e72e00e8002ed3c4b1d3295deef/src/main/java/com/ldtteam/structurize/util/StructureLoadingUtils.java#L361).addAll(config.value)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
![image](https://user-images.githubusercontent.com/17338378/106366674-d5706580-633d-11eb-94aa-dd1e217fc30a.png)

**Comment by Raycoms** [comment]
resource pack makers could just add minecolonies:schematics/respacks

**Comment by Nightenom** [comment]
Remember that we don't scan for resource packs, we load from jar modFileDescriptor which afaik doesnt take resource packs in account

**Comment by Raycoms** [comment]
I had a player test this these days and it worked fine for them. Maybe someone has to double check it again.

**Comment by Moobien** [comment]
so would this work like detecting if the mods in the 'pack' are present and if yes enables the schematics/overrides and if not present does nothing?
