### ISSUE TITLE
Scan Tool postion 1 in survival

### ISSUE THREAD

**Issue by ErikderFreak** [ldtteam/Structurize#277]
### Prerequisites 

- [ x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version: structurize-0.13.113-ALPHA-universal
- MineColonies Version (if related bug): not related
- Related Mods and their Versions: not related

## Expected behavior

Leftclicking with the-scan tool should select the first block for coordinates.

## Actual behavior

Leftclicking actually does not trigger the block selection.
Breaking the block with the scan tools does (it immediatly gets replaced again)
In creative this is not a problem, in survival it is.
You need to break the block with the scan tool which takes time.

## Steps to reproduce the issue

1.  be in survival mode
2.  build something you wan't to scan
3.  leftclick the first position with scan-tool
4. nothing happens
5. hold leftclick with scan-tool until block is broken
6. you have marked your position 1

### Logs

- latest.log: 
- crashlog: 

### Notes
 This is not a big problem. Maybe even a note on the wiki that you have to break the block for it to work would be enough.
The real problem here is that people (including me) might get confused if it doesn't work in survival, because it only says "left-click" on the wiki page (and video from wiki page).

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
We know about it, will try to take a look but no promise, the problem is basically a vanilla limitation

**Comment by Nightenom** [comment]
Except for defaultly unbreakable blocks (like bedrock) it's now instant, the previously mentioned are completely unmarkable as first pos in survival
