### ISSUE TITLE
Structurize showing failed to load correctly during loading

### ISSUE THREAD

**Issue by Edison12300** [ldtteam/Structurize#279]
### Prerequisites 

- [ x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- Structurize Version:structurize-0.13.123-ALPHA

### Notes or related things

[latest.log](https://github.com/ldtteam/Structurize/files/5917122/latest.log)
![image](https://user-images.githubusercontent.com/71360570/106721133-3dc18e80-663f-11eb-990b-94104f8f0ec0.png)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Was gonna add a thumbs up to say I tested it too, and same thing, but I can't find the thumb - so I will type "thumbs up" instead =P
