### ISSUE TITLE
[1.16.4] CTD When Replacing Grass Blocks to Coarse Dirt

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/Structurize#290]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version: structurize-0.13.113-ALPHA-universal
- MineColonies Version (if related bug): minecolonies-0.13.610-ALPHA-universal
- Related Mods and their Versions:

Can't use the newer structurizes version since they are not supported by Minecolonies. :(

## Expected behavior

Not to crash

## Actual behavior

Crashed when attempting to replace Grass blocks with Coarse Dirt blocks

## Steps to reproduce the issue

Replace grass blocks with coarse dirt.

### Logs

- crashlog: https://gist.github.com/Sandriell/9ce2aecbfdd4e2fbc7f52e2dcd40fc04

### Notes

Seems to be related to trying to flag the new blocks with snow? None of the grass blocks were actually snowy though.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Fix was pushed few days ago but not available yet, you have to wait before we update minecolonies
