### ISSUE TITLE
Schematic save location changes

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/Structurize#291]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 113 alpha 
- MineColonies Version (if related bug): 581 alpha (this was on the schem server)
- Related Mods and their Versions: none

## Expected behavior
When saving a scan with the scan tool, it would save in the same folder each time.

## Actual behavior
Sometimes it saves in `structurize/scans`, and sometimes in `minecolonies/scans`. The folder location stays the same within one session, but changes over multiple sessions.

## Steps to reproduce the issue

1.  Scan sth with the scan tool and save it
2.  Log out and back in
3.  Save something else

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
same thing happens when you auto scan using command blocks

**Comment by Nightenom** [comment]
Probably problem of this [(code link)](https://github.com/ldtteam/Structurize/blob/1ed260a27c33f7c1e191e9fb66f0e7a8f44984a9/src/main/java/com/ldtteam/structurize/items/ItemScanTool.java#L263) as it's picking up the first regardless of the root folder
