### ISSUE TITLE
town hall outside colony?

### ISSUE THREAD

**Issue by firestorm2039** [ldtteam/Structurize#293]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- Structurize Version:

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

I AM RUNNING FORGE 1.16.4, everything else is 1.16.4 as well.

i placed supply camp on flat land (took me a while to fit this out), which then built itself, i made a town hall as i didnt know 1 appears in supply camp, so now i have 2 lol.
anyway i go to place the town hall on flat land, use build tool and all is fine, then i click green tick and it says it is outside the colony?
i have this next to the supply camp, (not so the build goes in to the camp though), i cant place anything else until i build the town hall.
could you tell me what i am doing wrong?

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/issues and fill out the template please
