### ISSUE TITLE
structurize-0.13.113-ALPHA-universal.jar version delayed.

### ISSUE THREAD

**Issue by AndrewTru** [ldtteam/Structurize#295]
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version: structurize-0.13.113-ALPHA-universal.jar
 
## Problem description
simple
minecolonies: minecolonies-0.13.633-ALPHA-universal.jar
expects: structureize version 0.13.115
finds 0.13.113
crashes.

### Notes or related things
I know some may have said this, but at the same time the curseforge program only finds 0.13.113
if 0.13.115 is a secret beta or even a dev tool...then the minecolonies mod has released a well...dev build in the alpha channel.
even going back to version 0.13.632 has the same bug.
don't know how far back I have to go before the version matches.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Do you mean 0.13.135? That version of MineColonies doesn't need 0.13.115

**Comment by ravenbuilder934** [comment]
And 115 absolutely does exist https://www.curseforge.com/minecraft/mc-mods/structurize/files/3180796

**Comment by AndrewTru** [comment]
oddly I can't boot into a test pack I made with all the updates that curse forge had.
it keeps saying the version isn't the same.

**Comment by ravenbuilder934** [comment]
so you can't boot with 633 of minecolonies and 135 of structurize?

**Comment by AndrewTru** [comment]
yes, somehow it checks for the mods and reports the 115 version.
but hasn't been auto-installed by curse forge.

**Comment by ravenbuilder934** [comment]
can you install 115 with the link I posted earlier?

**Comment by AndrewTru** [comment]
I think so.
have not done it yet.

**Comment by Raycoms** [comment]
This seems like a support issue, rather than a mod issue. I'll close this for now.

**Comment by AndrewTru** [comment]
due to changes.
it's now looking for 171 by the time of the test.
