### ISSUE TITLE
Framed Sandstone Blocks

### ISSUE THREAD

**Issue by Donut7163** [ldtteam/Structurize#299]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ X ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: Minecolonies Official Modpack 1.16.5 v1.2 Release

## Is your feature request related to a problem?

No
## Feature description

Framed sandstone blocks, to go along with all the other framed blocks.
### Notes or related things

haha spacewars style go brrrr

Spacewars needs a slight bit of a redesign.

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Available in 1.17+ in https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum/files/all, if not please open issue on DO repo, ty
