### ISSUE TITLE
Folder Missing

### ISSUE THREAD

**Issue by rustyred41** [ldtteam/Structurize#301]
I reset my Minecraft by deleting some folders inside, on of the few was structurize, and then I deleted the whole folder, now when I try to use my mods, the "structurize" folder is missing. (I'm using structurize 0.13.96 on Minecraft Forge 1.16.5)

1. Delete the "Structurize" folder

2. Delete the "Minecraft" folder
 
3. Download Forge back

4. Enter Minecraft

5. Exit Minecraft

6. Add Structurize into the mods folder

7. Start Minecraft

After you start Minecraft, you'll be prompted by an error

"structurize (Structurize) has failed to load correctly
Java.lang.RuntimeException: Missing some newest data versions. Please update"

When you check the %appdata%, the "Structurize" folder is missing

**Comment by ravenbuilder934** [comment]
that's because 96 is very out of date. use the latest alpha of minecolonies and 139 alpha of structurize
