### ISSUE TITLE
Reed Roofing Tiles

### ISSUE THREAD

**Issue by thaylar** [ldtteam/Structurize#305]
### Prerequisites 

- [ x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x ] I made sure that **this feature request is not a duplicate of any existing feature request.**

### Context 

- Minecraft Version: xx
- Structurize Version: xx

## Is your feature request related to a problem?

none

## Feature description

Roofing tiles similar to thatch but in a reed variant for use with the tropical style.  Could also be used for jungle and Asian.
Could be based on Sugar Cane or Bamboo, similar to thatch being based on wheat.
I imagine taking the sugar cane texture and overlapping it so that the reeds create a solid texture.  Apply that to the existing wood frames.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the feature request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Available in 1.17+ in https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum/files/all, if not please open issue on DO repo, ty
