### ISSUE TITLE
Shape Tool UI doesn't update block change

### ISSUE THREAD

**Issue by Asherslab** [ldtteam/Structurize#32]
When you change the Main or Fill blocks in the Shape Tool GUI the block underneath does not update until you close and open the GUI again, it would be better if the gui updated when changing the block

**Comment by ravenbuilder934** [comment]
This also occurs when using the scan tool GUI to replace blocks.

**Comment by Nightenom** [comment]
Stale, almost sure its fixed, if not please reopen
