### ISSUE TITLE
Minecolonies with Shaders 1.16.5

### ISSUE THREAD

**Issue by snipechan** [ldtteam/Structurize#324]
![2021-03-14_17 44 45](https://user-images.githubusercontent.com/73801763/111077307-7a12c500-84f0-11eb-85b4-220817bf499a.png)
Is there any way to fix this?  I'm using Optifine G7 for 1.16.5 and this happens on every shader

**Comment by Raycoms** [comment]
Internal shaders are currently not supported yes. General shaders are generally supported but they used to work fine in 1.16.5. if they're broken now, Optifine broke mod-compat and it's a "them issue".

**Comment by snipechan** [comment]
I've come to terms with this optifine glitch and just turn my shaders off, put buildings up and back on. :D

**Comment by Nightenom** [comment]
Have you tried restarting **entire** mc after you've changed the shader?

**Comment by snipechan** [comment]
Nope

**Comment by Nightenom** [comment]
Reopening for further investigation, also please send debug.log from session when you try opening building previews before + after shader change

**Comment by smmmadden** [comment]
well, it is very interesting that my Forge 36.0.55 with MineColonies 0.14.9-Alpha with Structurize 0.13.148-Alpha appear to **now** be working for **Internal Shader pack and ComplimentaryShaders_3.07.zip.**  Didn't see any Optifine G7 option for shaders, so couldnt provide a screen shot for them even though it is part of the modpack I created for this server.
First image is Internal Shader
![image](https://user-images.githubusercontent.com/10309346/111250532-e15d7180-85e3-11eb-8625-b77e0808aff0.png)

Second image is ComplimentaryShaders
![image](https://user-images.githubusercontent.com/10309346/111250552-e8847f80-85e3-11eb-82fc-0663a32755ee.png)

**Comment by Nightenom** [comment]
So it still works when you restart mc after shaders change? or it works now without restarting?

**Comment by smmmadden** [comment]
it magically started working.  Could have been fixed between Forge 36.0.28 and 36.0.55 (which is what I'm on) or a change in MineColonies corrected it.  Will need @snipechan to confirm it works in whatever version he/she is running on.
