### ISSUE TITLE
[non-feature request] Shingles and Frames stand-alone

### ISSUE THREAD

**Issue by TheLewtz** [ldtteam/Structurize#325]
### Prerequisites 

- [ see note] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: NA

## Problem description
Enjoy the added blocks, shingles and frames.  Hoping we can get those as their own stand alone mini-mod.

### Notes or related things
Myself and some buddies are working on a large server, while we have removed mine colonies due to pack direction, we really enjoy the shingles and frames.  Was wondering if we could get a mini-mod of just these blocks in a manual crafting mod?

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
You know you can have structurize standalone for this
