### ISSUE TITLE
Cannot register second position for the scan tool if there is an interactable block in the way.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/Structurize#326]
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- Structurize Version:
- MineColonies Version (if related bug):
- Related Mods and their Versions:

## Expected behavior
Scan tool, even when perform right-click on a functional block, will be prioritized over the block interraction.

## Actual behavior
Cannot register a second position, must be replaced with a normal block then right-clicked.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Versions?

**Comment by kihgy** [comment]
Oops sorry I neglect this thread, yeah it is still happening on the latest version, the one with the number 48 on it
