### ISSUE TITLE
Medieval Oak Alternative buildings miss placeholders

### ISSUE THREAD

**Issue by lebanni** [ldtteam/Structurize#329]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: structurize-0.13.148-ALPHA-universal.jar
- MineColonies Version (if related bug): minecolonies-0.14.34-ALPHA-universal.jar
- Related Mods and their Versions:

## Actual behavior

Some of the Medieval Oak Alternative buildings miss placeholders in order for the blocks are replaced with the default biome blocks, at least for the farm, the restaurant and the courier. I haven't checked for others.
This has been for months, even in the 1.15.x versions.

The template : 
![2021-03-19_01 07 03](https://user-images.githubusercontent.com/2799575/111807181-fb909b80-88d2-11eb-9da4-5e53de9082b5.png)

The finished level 1 building, of course 1 block lower : 
![2021-03-19_16 40 38](https://user-images.githubusercontent.com/2799575/111807353-267aef80-88d3-11eb-8d7c-5f6dbd019715.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/issues/5006 This isn't a structurize issue
