### ISSUE TITLE
(Feature Request) Expose structure gen

### ISSUE THREAD

**Issue by sm9cc** [ldtteam/Structurize#33]
What caught my eye in this mod was the buffered structure loading, me and a friend have been looking for a mod which can spawn large structures without lag (Randomly generated), I understand this mod is not about that but if the API to do such stuff was exposed then I would be willing (With my limited Java, but not programming knowledge) to try and make a sub / addon mod which utilizes it.

Thanks.

**Comment by Raycoms** [comment]
Isn't it? All the necessary classes should be public

**Comment by sm9cc** [comment]
Oh? maybe  I am just not knowledgeable enough to be asking for stuff when its already here, I looked through API folder and I did not see anything, I probably looked in the wrong place though and don't properly understand how this mod would be used as a library.

**Comment by Raycoms** [comment]
ohh, yeah, the API folder atm is pretty non existent. In the future we'll
define more interfaces to work on. For now you would just work with the
things in the main folders. They are all exposed so it should work fine.
If you want to know how to use it you can check how we use it in the
minecolonies mod. Minecolonies used structurize for building and pasting.

Am Do., 25. Apr. 2019 um 10:23 Uhr schrieb Michael <notifications@github.com

**Comment by sm9cc** [comment]
Perfect, thanks for all your help :)

**Comment by Raycoms** [comment]
If you need any help you can contact us on the minecolonies discord =)

Am Do., 25. Apr. 2019 um 10:37 Uhr schrieb Michael <notifications@github.com
