### ISSUE TITLE
Cannot

### ISSUE THREAD

**Issue by anakhasilver** [ldtteam/Structurize#331]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Latest
- Structurize Version: 1.13.156 alpha
- MineColonies Version (if related bug): N/A
- Related Mods and their Versions:  Optfine 1.16.5 G7, pam harvestcraft 2 core (1.16.3-1.0.1) and modules (crops 1.16.3-1.0.1, trees 1.16.2-1.0.0, foodextended 1.16.3-1.0.2), WorldEdit 7.2.4, journeymap 1.16.5-5.7.1

## Expected behavior

That I can LAN world with my partner who is sitting next to me
## Actual behavior

I open it to LAN, and we have the exact same everything. However, partner gets an error every time, saying it failed to synchronize.

## Steps to reproduce the issue

1.  Download latest structurize
2.  Open Minecraft LAN world
3.  Person connecting cannot connect no matter what

### Logs

- latest.log:  N/A
- crashlog:  N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
there is a reason why we ask for logs, without them we can't even say if it's our fault or someone else

**Comment by Raycoms** [comment]
We're not supporting LAN mode. However, you can also just launch a local server on your machine without a problem
