### ISSUE TITLE
Fence's connection is identical in builds, result in fences can connect to nothing

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/Structurize#334]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- Structurize Version: structurize-0.13.148-ALPHA-universal.jar
- MineColonies Version (if related bug):
- Related Mods and their Versions:

## Expected behavior
Fences in the new structure shouldn't connect to nothing

## Actual behavior
The scan in the new structure can connect to air block as in the scan it was connecting to something.
May provide some images later

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
I've never managed to replicate this in structurize only world, reports like this one usually comes from mcol worlds

**Comment by kihgy** [comment]
Not sure, I was playing Mcol in creative and after build two farms with fence around and connected to each other, I decided to use the scan tool to just copy the schematic of one farm to speed up the process and got this issue.

So it is still from the scanning feature of Structurize.

**Comment by kihgy** [comment]
Oh btw I just paste the structure instead of having the builder build it

**Comment by Nightenom** [comment]
Please open new issue if you encounter in recent versions, ideally with good repro steps
