### ISSUE TITLE
IncompatibleClassChangeError on server load

### ISSUE THREAD

**Issue by AnthonyHeide** [ldtteam/Structurize#340]
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- Structurize Version: structurize-0.13.160-ALPHA-universal

## Expected behavior
The server loads without crashing.

## Actual behavior

After updating Minecolonies and Structurize to the latest versions my server is crashing on load with the following error.

§7java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/ldtteam/structurize/api/blocks/IBlockCollection. Method 'net.minecraft.block.Block lambda$create$0(com.ldtteam.structurize.api.blocks.BlockType)' at index 147 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef

## Steps to reproduce the issue

1. Add structurize-0.13.160-ALPHA-universal to your mods folder.
2. Start the server.

### Logs

- latest.log: https://gist.github.com/AnthonyHeide/b4ddf808fb74763ad7c1a1f20b2aced9
- crash report: https://gist.github.com/AnthonyHeide/79cd29dee4a63da03fa3bde78957c8e2

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by marchermans** [comment]
Why was this assigned to me?
I did not change anything related to that class.

**Comment by marchermans** [comment]
@AnthonyHeide More details are needed.

Like OS,
JVM Type and version etc.

**Comment by AnthonyHeide** [comment]
OS: Windows 10 Pro 20H2 (Build 19042.906)
Java: OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS) (64-Bit)

Do you need anything else?

**Comment by marchermans** [comment]
@AnthonyHeide Can you please try to run this with an OpenJDK Java version 8 JVM?

**Comment by marchermans** [comment]
Or alternatively an Oracle JDK 8 Version?

**Comment by AnthonyHeide** [comment]
Running OpenJDK 8 works.

**Comment by lebanni** [comment]
Same on Linux Mint 20.1

OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by marchermans** [comment]
This is a problem with openjdk 11 then.

As of now minecraft itself requires java 8 to run. As does forge. And so does structurize. Sadly I can not fix this untill both mc and forge update.

Please use java 8 to run minecraft.

**Comment by lebanni** [comment]
I understand, bust just to let you known, there has not been any update of java, and it was working until now.
