### ISSUE TITLE
Inconsistent constant pool data in classfile

### ISSUE THREAD

**Issue by ARamlall** [ldtteam/Structurize#341]
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge 1.16.4
- Structurize Version: latest (13.160)
- MineColonies Version (if related bug): 14.83
- Related Mods and their Versions: see crash report 

## Expected behavior
 
server starts up, playable

## Actual behavior

server attempts to start, errors out on loading structurize, see gist for more.

## Steps to reproduce the issue

1.  start with structurize 148 and minecolonies 14.73, load server
2.  update straitght to the latest of both mods
3.  upon starting server it will fail to load structurize, see github gist.

### Logs

- latest.log: https://gist.github.com/ARamlall/ce87e9d6c42caef224d7aa82243e7f68
- crashlog: https://gist.github.com/ARamlall/713c80ee845242db39a5560430a965a7
- 

### Notes

previous version of minecolonies and structurize was outdated, upon updating structurize will not load as can be seen in the crashlog, rolling back allows server to start back up.
All packages are up to date on the balena device, this same problem arises when following recreation steps on other hosts. Java version is latest for arm devices. Restarting the server will result in the same error. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
java version?

**Comment by ARamlall** [comment]
root@balenaminecraftserver:/# java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode)

Is there a different version needed to run the latest? It was working with previous versions of minecolonies and structurize

**Comment by Raycoms** [comment]
Yes, switch to java 8, java backported some features recently to java 11, that are incompatible with the newest structurize.

Minecraft requires java 8, so we are either java 8 compatible or java 11+ (we can't choose).

**Comment by Raycoms** [comment]
(This can happen with multiple mods, so it's better to downgrade already).

**Comment by sandalle** [comment]
This wasn't an issue until I updated from structurize-0.13.139-ALPHA-universal to structurize-0.13.163-ALPHA-universal (required by minecolonies-0.14.92-ALPHA-universal) as I was doing my modpack mod update pass today. Also running Java 11 as some other mods (e.g. Modern UI), along with other applications, recommended it. All my other 261 installed mods work fine with Java 11, as well as structurize-0.13.139-ALPHA-universal and minecolonies-0.13.651-ALPHA-universal. Looks like I may need to look at downgrading all my systems to Java 8 for just this one mod.

Seems a duplicate of #340 .
