### ISSUE TITLE
Structurize stacktrace, can't log in. Server is asking to report a bug

### ISSUE THREAD

**Issue by SteadEXE** [ldtteam/Structurize#346]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.163

## Problem description

I can't log back to the server, I am getting kicked with "Internal server error".
![image](https://user-images.githubusercontent.com/1759156/114273267-b109c700-9a19-11eb-9dd8-31c801659d7f.png)

And the server keep outputing this stacktrace:
![image](https://user-images.githubusercontent.com/1759156/114273291-c7178780-9a19-11eb-930b-d30bfa5b278e.png)

### Notes or related things

I disconnected next to a friend which is building birch constructor hut level 1. I don't know if it can help.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
same as https://github.com/ldtteam/Structurize/issues/345
