### ISSUE TITLE
Minecolonies' Guard Tower UI does not show the Job button

### ISSUE THREAD

**Issue by kedamono** [ldtteam/Structurize#347]
### Prerequisites 

- [ x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.163-ALPHA-universal
- MineColonies Version (if related bug): 0.14.93
- Related Mods and their Versions: MacOS Big Sur Version 11.2.3, Screen Resolution 5120 x 2880

## Expected behavior

When I open the guard tower hut block's menu and go to the second page, the Job button is visible and I can select between Archer and Knight for the job assigned to the guard tower.

## Actual behavior

When I open the guard tower hut block menu, I cannot see the Job button on the second page of the menu. 
I've tried changing the Minecraft Video GUI settings from GUI 1, GUI 3, and GUI Auto and the button is not visible for any of those settings.
![GUI1](https://user-images.githubusercontent.com/23420636/114286157-19a07600-9a11-11eb-9eee-2277280f3216.png)
![GUI3](https://user-images.githubusercontent.com/23420636/114286163-1dcc9380-9a11-11eb-9df3-6e76f219505a.png)
![GUIAuto](https://user-images.githubusercontent.com/23420636/114286164-1f965700-9a11-11eb-97ca-9bd4ecf10761.png)

## Steps to reproduce the issue

1. On a Mac computer running MacOS Big Sur, in Minecraft, go to a guard tower and open the menu from the hut block.
2. Click the arrow to go to the second page of the menu.
3. The Job button is not visible.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
can you do the shift/ctrl/alt thing to see if it at least renders that for it?

**Comment by kedamono** [comment]
I'm not in a position to test it right now, I will tomorrow morning.

**Comment by kedamono** [comment]
I tried all three key combinations and no button or functionality.

**Comment by Nightenom** [comment]
Meh, why is this in structurize repo, also @Raycoms does this happen now after all the gui changes you've made?

**Comment by Raycoms** [comment]
No, this can be closed
