### ISSUE TITLE
latest Structurize crashes Dirwolf20 1.16 modpack to a loop

### ISSUE THREAD

**Issue by Mechrior** [ldtteam/Structurize#348]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- Structurize Version:0.13.146-ALPHA-universal.jar
- MineColonies Version (if related bug):0.13.670-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Minecraft server using a slightly modified version of Direwolf20 pack from FTB launcher to load

## Actual behavior
Server goes into load/crash loop with updated version of structurize and minecolonies

## Steps to reproduce the issue

1.  update pack to version of structurize and minecolonies stated above
2.  try to load server version of pack
3.  server throws fatal error and tries to restart entering an endless loop

### Logs

- latest.log: https://gist.github.com/Mechrior/3b46283fc8ed6e68b7188ff6a8387c84 
- crashlog: https://gist.github.com/Mechrior/aa0881259dafceb57dfa290cb9cd2e16 

### Notes

Had updated structurize and minecolonies to try and fix some lag andstrange behaviour in colonists in a large dwarven town.
Changed both MC and structurize to latest versions that work together, and server now crashes.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
use java 8

**Comment by Mechrior** [comment]
> 
> 
> use java 8

Excuse me, but you did read that this is running on a server? I personally dont have control over that, I personally am running on java 8 update 161-b12.

the previous version we were using was minecolonies 0.13.670-ALPHA-universal and structurize 0.13.146-ALPHA-universal.
they worked fine with no issues apart from some silliness with a few villagers.

I have contacted nitrado about the java version they use and will see if I can get them to update it if its not the right one.
Thank you for the quick reply though, and will let you know what happens.

**Comment by Raycoms** [comment]
Yeah, Nitrado should be running their servers on java 8 to start with. Minecraft ships with java 8 for a reason.

**Comment by Raycoms** [comment]
But there is nothing we can do, Java backported backwards incompatible things to java 11 that break with us here.

**Comment by Mechrior** [comment]
> 
> 
> But there is nothing we can do, Java backported backwards incompatible things to java 11 that break with us here.

Fair enough, as I said I have contacted their support to see if I can get them to either sort something or update the SDK they are using for my server.

Paying to use it, and I dont like being failed hehehe.
Worst comes to worst I will cancel with them and either use someone else or buy a cloud service.
Loving the mods though, got a semi large but cramped dwarven settlement going and we have stories for every person as they go about their lives...... really wish I had streamed the forming as its made us laugh, shout, and in one case reassign the names of a few colonists to an NSFW last name if they annoy us.

Will update later if anything happens!

**Comment by Raycoms** [comment]
We've been using Bisect and got a partnership with them with discount code (can be found on our curseforge page) we are hosting our server there and it has been working very well including in the newest version.

**Comment by Rice-SD** [comment]
Did something change with the Alpha? This has been working fine for months on my server with OpenJDK 14.0.2. Latest update now crashes server.

**Comment by Nightenom** [comment]
We know about it, it's probably gonna be fixed somewhen, but it's low priority. Using anything else than the latest jre8 is (always was) your own experiment (while we tend to support newer javas it's nothing we can guarantee)

**Comment by Rice-SD** [comment]
Yea no problem at all, took me 5 mins to install Java 8 and uninstall Java 14. Server is now running. :)
