### ISSUE TITLE
[Regression] Incompatible with Java 9+ on servers

### ISSUE THREAD

**Issue by SharkWipf** [ldtteam/Structurize#349]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: structurize-0.13.164-ALPHA-universal.jar
- MineColonies Version (if related bug): n/a
- Related Mods and their Versions: No other mods installed (for testing), forge-1.16.5-36.1.4.jar

## Expected behavior

The server starts on java versions >= 9, as it did on earlier versions, and as it does on the client.

## Actual behavior

While the client starts fine, the server crashes with the following error:

## Steps to reproduce the issue

1.  Install a Java version Java 9 or later
2.  Install Forge and Structurize
3.  Start the server and watch it crash

### Logs

- latest.log: https://gist.github.com/SharkWipf/f31af579b3851a109b98b75954aa0ee9
- crashlog: https://gist.github.com/SharkWipf/24d146dbd37d9599a86e2040b31120e9

### Notes

Initially ran into this problem in the latest FTB Presents Direwolf20 8.0 pack, which ships with this issue. Removed all other mods and configs to reproduce, installed latest alpha to reproduce.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#348

**Comment by SharkWipf** [comment]
Ah, I only checked the open issues, didn't expect a big regression like this to be closed before being fixed.

**Comment by Raycoms** [comment]
It's because it's not a regression, it worked by chance in java8+, minecraft ships with java 8 for a reason. And java messed up stuff in older version so some things are now code incompatible...

**Comment by SharkWipf** [comment]
Minecraft, maybe, but Forge 1.13+ was completely rewritten primarily to support newer Java versions IIRC.
Even if it worked by chance/unintentionally before, it not working now is still a regression, as it broke something that used to work in previous versions.

Well, either way, I agree Java 8 support is more important than Java 9+ support atm, and if it's an issue with Java 8 unique to Structurize that can't be worked around, I guess it can't be helped.

**Comment by Zorgatone** [comment]
Is this the reason of my error on Java 15?

I'll try running with plain old Java 8

Errors log paste: https://ghostbin.co/paste/bmr6

**Comment by ravenbuilder934** [comment]
Yeah that's your issue
