### ISSUE TITLE
Mod Loading has failed

### ISSUE THREAD

**Issue by sausagemadness** [ldtteam/Structurize#356]
Context

    Minecraft Version: 1.16.5
    Structurize Version: 0.13.163-ALPHA-universal

Structurize mod not loaded.
The crash report is attached.
[crash-2021-04-17_20.04.15-fml.txt](https://github.com/ldtteam/Structurize/files/6329834/crash-2021-04-17_20.04.15-fml.txt)

**Comment by ravenbuilder934** [comment]
Use java 8
