### ISSUE TITLE
Medieval oak alternative guard tower does not connect to fancy wall as it used to and got a bug

### ISSUE THREAD

**Issue by ederlezi29** [ldtteam/Structurize#359]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.166
- MineColonies Version (if related bug):0.14.109
- Related Mods and their Versions:

## Expected behavior
Previous medieval oak alternative guard tower blueprint did not have this issue. Please revert or correct.

## Actual behavior
The medieval oak alternative guard tower does not connect nicely with fancy walls, got extra block on side who are not removed.

Here is the old blueprint and how it did integrates with fancy walls. That design was much better.
![MedievalOakAlternative_GuardTower_L5_3_old_style](https://user-images.githubusercontent.com/82267189/115574145-a8d74480-a2c1-11eb-90cb-eb2519d16bfa.png)

bug :  the 2 cobblestone stairs, 2 oak logs and the fence should not be there
![MedievalOakAlternative_GuardTower_L5](https://user-images.githubusercontent.com/82267189/115574269-c5737c80-a2c1-11eb-8d52-6be6747c7ef8.png)

Cause of the previous bug, it breaks the fancy wall
![MedievalOakAlternative_GuardTower_L5_2](https://user-images.githubusercontent.com/82267189/115574628-197e6100-a2c2-11eb-9ab5-9a51b632a135.png)

## Steps to reproduce the issue

1. Build a fancy wall
2. Level up a medieval oak alternative guard tower to level 5 next to a fancy wall
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/issues/5006

**Comment by ederlezi29** [comment]
It's not a big deal obviously but it's just a pity because it was far better before (espacially the integration with fancy walls)
