### ISSUE TITLE
Crashing after loading into old world with newer versions

### ISSUE THREAD

**Issue by DestroyEarthlings** [ldtteam/Structurize#366]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4-forge-35.1.4
- Structurize Version: Updating from 0.13.148-ALPHA-universal to 0.13.169-ALPHA-universal
- MineColonies Version (if related bug): Updating from 0.14.22-ALPHA-universal to 0.14.133-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Loading world with newer version to be successful.
## Actual behavior

 I have been on this world on the older version and the game crashes when I try to enter it with the new version.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/DestroyEarthlings/5fc9125965e9c8118750b620f06f6d2b   this link has the crash report followed by the latest log
- crashlog: 

### Notes

I have tried two different slightly less recent versions to update to but they had the same issue.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Does a new world work?

**Comment by Nightenom** [comment]
Few things to try:
1) update to the latest java 8 jre (you can get it eg. here https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot)
2) reinstall forge - it may have failed to install one library
3) try without optifine

**Comment by Raycoms** [comment]
Update to newest forge (1.16.5)

**Comment by DestroyEarthlings** [comment]
I updated java and got the newest 1.16.5 forge and it works now
