### ISSUE TITLE
Scan tool crashed as I try to check for resources in a build

### ISSUE THREAD

**Issue by kihgy** [ldtteam/Structurize#368]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version:structurize-0.13.167-ALPHA-universal
- MineColonies Version (if related bug):minecolonies-0.14.129-ALPHA-universal
- Related Mods and their Versions: Provided in the crash log

## Expected behavior

I can check for resources like normal

## Actual behavior

As I right click the resource option in the build menu when registering it, the game crashed, not sure why, but I cannot edit resources in my build, the build only have vanilla blocks

## Steps to reproduce the issue

1. Try to scan a large structure
2. Right click the scan tool after registering both positions to open the register menu
3. click at the "show resource" option
4. game crashes

### Logs

- latest.log: 
- crashlog:  https://pastebin.com/dRyZqBwz

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you try updating?

**Comment by kihgy** [comment]
K you passed

**Comment by ravenbuilder934** [comment]
what? Is it no longer crashing after updating?

**Comment by marchermans** [comment]
This is fixed. It was an issue with vanilla double chests.
