### ISSUE TITLE
Hopper is invisible when pasted into world if it was scanned while powered by a redstone signal

### ISSUE THREAD

**Issue by dupontct** [ldtteam/Structurize#372]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.171-ALPHA
- Related Mods and their Versions: Forge-36.1.17

## Expected behavior

When the schematic is pasted into the world using the creative build tool the hopper should be visible.

## Actual behavior

When the schematic is pasted into the world the hopper is not visible until a adjacent block is right clicked.

## Steps to reproduce the issue

1. Create the combination of blocks shown in the picture ![2021-05-13_19 08 38](https://user-images.githubusercontent.com/29468/118202509-bcd51880-b41f-11eb-949f-c14c008fa15e.png)
2. Using the scan tool create a schematic of the three blocks as shown ![2021-05-13_19 09 39](https://user-images.githubusercontent.com/29468/118202524-c2326300-b41f-11eb-863b-60563db01727.png)
3. Using the build tool place the structure on the surface of the world and Paste it into the world. You should now see this: ![2021-05-13_19 10 13](https://user-images.githubusercontent.com/29468/118202531-c494bd00-b41f-11eb-882d-552ccbbbd515.png)
4. Right click the stone block with a empty hand and the hopper appears. ![2021-05-13_19 10 19](https://user-images.githubusercontent.com/29468/118202534-c65e8080-b41f-11eb-9477-201ef06dc91a.png)

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
There is currently no special handling for redstone circuits, so if you don't place them in a single tick (= you have to use creative mode to paste them) they may behave unexpectedly
But this seems to be a specific problem of hopper
