### ISSUE TITLE
Some blocks (beehives, double chests) do not mirror/rotate correctly (vanilla bug)

### ISSUE THREAD

**Issue by dhouck** [ldtteam/Structurize#377]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.173
- MineColonies Version (if related bug): 0.14.166
- Related Mods and their Versions:

## Expected behavior

When I rotate a schematic containing a beehive, the hive should rotate as well, so the entrance is facing the same way relative to the rest of the structure instead of the same absolute direction.

## Actual behavior
The hive always previews, is placed by the paste tool, and is placed by the builder in the same absolute direction regardless of rotation.  This direction varies between hives in different schematics; presumably it matches the dimension the hive was scanned in, since the unrotated ones make sense in a way rotated ones do not.

This makes many MineColonies schematics unusable when rotated.

## Steps to reproduce the issue

1. Grab an apiary hut block and a build tool
2. Preview a build of the apiary unrotated (eg. fortress/beekeeper5, which has a bunch of beehives in a wall, facing outward)
3. Rotate the preview; observe that the hives themselves don't rotate (eg. in the same schematic, the hives are now facing into a wall and therefore unusable)

### Logs
N/A; this does not show up in logs.

### Notes
I haven't tested bee *nests* but expect they have the same issue.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by dhouck** [comment]
Unfortunately this (along with #374, another bug with changing the structure orientation) are actually vanilla.  The beehive block is missing a `rotate` function entirely; the chest block (subject of #374) does have a mirror function but it doesn't swap LEFT and RIGHT as it should.  I'm going to report this on the Minecraft bug tracker; it hasn't been fixed by 1.17pre4.

In the meantime, is there a good place for us to fix it?  It looks like not; `blueprint.rotateWithMirror` doesn't seem to have a hook for custom rotation or mirroring, and by the time we get to `PlacmenteHandlers` it looks like we've forgotten if things were rotated or mirrored.

**Comment by Nightenom** [comment]
If you are sure that it's vanilla bug, then the common approach is to report to vanilla bug tracker and then create a forge pr with temp fix till mojang fix it in vanilla

**Comment by dhouck** [comment]
Definitely vanilla; happens with structure blocks although the chest issue presents differently. 
 Reported the to Mojang as [MC-227255](https://bugs.mojang.com/browse/MC-227255) and [MC-227260](https://bugs.mojang.com/browse/MC-227260).  If I were a Mojang employee it would have been faster to fix than to report, honestly.

I haven't created a Forge patch before but it looks relatively simple; I'll try to get to it tomorrow.

**Comment by Nightenom** [comment]
Creating such patches is quite simple, fork forge, run `gradlew setup`, apply changes to vanilla in `projects/forge` folder, run `gradlew genPatches`, don't forget to test obviously, see more about contributing at forge docs.
Also for vanilla bugfixes it's common to put a comment with reference to mojang bug tracker

**Comment by dhouck** [comment]
This will be fixed by MinecraftForge/MinecraftForge#7803
