### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by ghost** [ldtteam/Structurize#379]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.100

## Expected behavior

Not crash would be a start...

## Actual behavior

Crashes on Startup

![image](https://user-images.githubusercontent.com/68340265/119362071-8ee6a400-bc69-11eb-8143-68b9af7e8a38.png)

## Steps to reproduce the issue

1. Install Minecraft
2. Install forge 36.1.16
3. Install Structurize Version 0.13.100
4. Crashes on start up

### Logs

- latest.log: https://pastebin.com/m6X7tEA3 
- crashlog: https://pastebin.com/Bkxb6Rak 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Update to the latest alphas, <https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all> and <https://www.curseforge.com/minecraft/mc-mods/structurize/files/all>, note the required structurize version in the minecolonies changelog

**Comment by ghost** [comment]
im not using minecolonie though

**Comment by Raycoms** [comment]
Then you're just using an outdated version for your forge/mc version
