### ISSUE TITLE
schematic size 

### ISSUE THREAD

**Issue by ghost** [ldtteam/Structurize#38]
player own schematic have maximal size as i saw, i were trying to scan a fotress, but it was to big for the scheme limit ( i was forced to cut 4 blocks every direction ) 

minecraft 1.12.2 minecolonies 0,10,63 alpha-universal

### Expected behavior

- make an setting to allow player to configure how big can be scaned area

### Actual behaviour

-  there is a limit ( not sure how big)

### Steps to reproduce the problem

1. add a setting with  ^X^Y^Z  axis 
2. make a text area next to axis setting with number of blocks which can be scaned (X*Y*Z)
3. it should allow players to scan bigger structures 
4. it will give a possibility to copy all districts in colonies to make them visually bigger or to place in colonies big structures from different maps etc. 
second idea 
1. add system of part schematics.
2. if schemat is for example 100x100x40 (lenghtxwidthxheight) cut it inoo 4 parts 50x50x40 or 25 parts 20x20x40, like with barracks where the towers on the corners are placed as separate buildings, 
3. save it as 4 or 25 or more smaller filies with connecting file in folder which describe which part has to be where. that should be easier for computers to work with.
4 it also give a possibility to build massive construction with more than one builder, if one builder would has to build somethin 100x100x40 it could take centuries , but after cuting it into smaller parts whic are separate schematics but are just placed with one central, it give a possibility to build a massive structure with all builders we have in colony and make "team work" beetwen AI

**Comment by Nightenom** [comment]
1.12 is no longer maintained

**Comment by VirtualZer0** [comment]
"Nice" solution

**Comment by ravenbuilder934** [comment]
...you do realize that happened almost a year ago? and there's now a config setting for max schematic size, iirc

**Comment by VirtualZer0** [comment]
`gameplay {
        # Should player made schematics be allowed
        B:allowPlayerSchematics=true

        # Should the default schematics be ignored (from the jar)?
        B:ignoreSchematicsFromJar=false

        # Max amount of blocks checked by a possible worker.
        I:maxBlocksChecked=1000

        # Max amount of changes cached to be able to undo
        I:maxCachedChanges=10

        # Max amount of schematics to be cached on the server
        I:maxCachedSchematics=100

        # Max world operations per tick (Max blocks to place, remove or replace)
        I:maxOperationsPerTick=1000

    }`

I don't see maxSchematicSize

**Comment by ravenbuilder934** [comment]
Are you on the latest version? it was only added relatively recently
