### ISSUE TITLE
Recipe Packet Issue

### ISSUE THREAD

**Issue by Artimba** [ldtteam/Structurize#380]
### Prerequisites 

- [ x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ x] I made sure that **this mod compatibility issue is not a duplicate of any existing mod compatibility issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.173 Alpha
- Related Mods and their Versions: Minecolonies 0.178 Alpha, as well as other mods, the mods themselves aren't at fault as this is possible with any amount of mods as long as they are large enough

## Expected behavior

The ability to connect to a server

## Actual behavior

Once a certain threshold is met for the recipe packet, such as having multiple large magic mods like ars nouvue, blood magic, astral, the player will be unable to connect to a modded forge 36.1.0 server. The issue always goes back to a netty error, complaining about badly compressed packets. I talked about this to the minecolonies people and they said it was due to recipe packets on structurize. I went to the issue board here and didn't see any open issues that talked about this, so I decided to throw this out, sorry if this has already been addressed and is being worked on. 

## Steps to reproduce the issue

1. 
Load specified structurize and minecolonies versions with forge 36.1.0
2. 
Add mods, or use an already built modpack (I haven't tried ones outside my own, but I spent hours swapping mods in and out and I always got this crash around ~60 or so mods. I'm sure this depends on the size of mods used). 
3. 
Attempt to connect to a modded server, I tried both a linux hosted server and windows, both gave the same badly compressed packets error. Sometimes I would get in for a few seconds, and immediately get kicked. 

### Logs

- latest.log: https://gist.github.com/Skyibis/72407e1a8e13c6fdcb0e0d56e682434e#file-2021-05-24-7-log
- crashlog: 

### Notes

The log won't show much detail, but this bug was repeatable on every machine we tried it on. This was also being talked about in the mcol server before I joined. I hoped I provided enough information! Sorry again if this was already being worked on. 
---
## Viewers

* Add a thumbs-up to the mod compatibility issue if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
No it's not a structurize issue, it's a forge issue actually.

**Comment by Raycoms** [comment]
Because of all the blocks all those blocks together add

**Comment by someaddons** [comment]
https://www.curseforge.com/minecraft/mc-mods/connectivity might help you

**Comment by Artimba** [comment]
> https://www.curseforge.com/minecraft/mc-mods/connectivity might help you

This fixed it! Thank you so much, was really depressed not being able to try out minecolonies with the new 1.16 stuff
