### ISSUE TITLE
Structurize build tool not showing other buildings

### ISSUE THREAD

**Issue by starfall18** [ldtteam/Structurize#387]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- Structurize Version:0.13.174-ALPHA-universal
- MineColonies Version (if related bug):0.14.182-ALPHA-universal
- Related Mods and their Versions:ATM6 modpack version 1.6.7

## Expected behavior

When placing down the building the game asks weather i want to just place it or use the tool to see the preview of placing it where and how.

## Actual behavior

When placing down the building and clicking on use the tool, instead of showing the building you wanted to place down, it shows you the supply camp/ship and their versions that you placed down using the free supply camp/ship and you cant seem to choose a different building on any of the bars presented.

## Steps to reproduce the issue

  Pretty much try to build a supply camp from a free supply camp item, then craft a town hall and place that down and select "use the tool" option instead of the "just place it" option. Im not sure if placing the supply camp down first makes any difference but... thats what i did, and thats what it keeps showing me

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by starfall18** [comment]
hey, i also found out how people use the build tool so if you have the structure in your hand and try to use the build tool directly, it then actually shows the right building. Still using the "use the tool" option seems to show either only decorations or no buildings and shows only the building you placed down last time... Adding this comment in case it helps.,

**Comment by Raycoms** [comment]
can't you switch on the top left?

**Comment by Raycoms** [comment]
I just double checked. you can switch on the top left the buildings. It just always displays the last one you did on purpose.

**Comment by starfall18** [comment]
no... it either shows no building there or decorations... its like when place the building down and it asks you if you want to just place it or use the tool... when you click on use the tool, its like the building was still placed and the tool brings up the building you placed before the one you just placed

**Comment by starfall18** [comment]
wow... just close it huh... did you even test it the way i said?

**Comment by Raycoms** [comment]
For support please go to our discord. I tried it through the way you describe it and it works all perfectly as intended for me.
