### ISSUE TITLE
Structurize .177 Alpha Incompatible with Optifine G7 + Most recent MineColonies requiring .177 Alpha, not most recent. 

### ISSUE THREAD

**Issue by AlmightyChan** [ldtteam/Structurize#396]
### Prerequisites 

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [N/A ] I am running the latest version of OptiFine for my Minecraft version.
- [N/A] I am running the latest version of this shader for my Minecraft and OptiFine version.
- [X] I made sure that **this OptiFine issue is not a duplicate of any existing OptiFine issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: structurize-0.13.177-ALPHA-universal
- OptiFine Version: OptiFine HD U G7
- Shaders and their Versions: N/A

## Actual behavior and **screenshots**
 Crash on Start up

## Steps to reproduce the issue

1.  Have Optifine G7 and Structurize .177 Alpha installed and start up game
2.  Wait
3. Structurize fails to load and game crashes without causing client to close (Soft Crash - But can't continue)

### Logs

- latest.log:  https://gist.github.com/AlmightyChan/da74aa906f9583f9f5ca289e2d797bc6

### Notes
 This issue doesn't occur when using Optifine G8 however immersive portals a mod in pack is incompatible with G8 so wanted to see if it was an issue that could be resolved on struturize's end.
Also just curious but why does MineColonies require Structurize .177 Alpha and not the most recent? 

---
## Viewers

* Add a thumbs-up to this OptiFine issue if you are also affected. This helps the issue become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
> Also just curious but why does MineColonies require Structurize .177 Alpha and not the most recent?

The required structurize version is bumped manually in case a structurize update requires changes in mcol, which in this case it does. It'll be bumped soon:tm:

**Comment by Nightenom** [comment]
Report to EntityCulling-1.16.5-2.1.6.jar or just remove the mod, they have faulty coremod
Looking at their curseforge it may your fault that you have wrong version installed <https://www.curseforge.com/minecraft/mc-mods/entity-culling>
