### ISSUE TITLE
Cactus trapdoors "grant" x-ray vision

### ISSUE THREAD

**Issue by Nooska** [ldtteam/Structurize#401]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.194
- MineColonies Version (if related bug): 0.14.236
- Related Mods and their Versions:

## Expected behavior
I would expect to see the block behind/under the cactus trapdoor through the cutouts

## Actual behavior
Through the cutouts I can see through the block immediately behind/below the cactus trapdoor, as well as any connected blocks that are "the same kind" (grass and dirt are together here)

![2021-06-25_19 49 56](https://user-images.githubusercontent.com/36108100/123465694-bde89080-d5ee-11eb-9033-6fbceb38df4b.png)
![2021-06-25_19 50 00](https://user-images.githubusercontent.com/36108100/123465698-bf19bd80-d5ee-11eb-903b-3bf72c50b250.png)
![2021-06-25_19 50 26](https://user-images.githubusercontent.com/36108100/123465699-bf19bd80-d5ee-11eb-8fd8-5ca0101c630a.png)
![2021-06-25_19 50 31](https://user-images.githubusercontent.com/36108100/123465701-bfb25400-d5ee-11eb-8531-a5c3e8da3b38.png)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by WenXin20** [comment]
This also occurs with the cactus door.
![2021-08-02_17 43 47](https://user-images.githubusercontent.com/12000593/127932889-f1ab6365-42d0-43d4-90f1-baf029c96c75.png)

**Comment by leagris** [comment]
To fix this, you need to disable Ambient Occlusion on the Trapdoor and Door models.

The see-through block bug is triggered when the door/trapdoor receive Ambient Occlusion shadow from a connected opaque block.

**Comment by Nightenom** [comment]
If this issue persists, but I've used these blocks recently and haven't encountered described behaviour, please open new issue on [ldtteam/domum-Ornamentum](https://github.com/ldtteam/domum-Ornamentum/) repo
