### ISSUE TITLE
Visitor item count is not displayed on MineColonies recuit GUI

### ISSUE THREAD

**Issue by FesterHead** [ldtteam/Structurize#402]
### Prerequisites 

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: structurize-0.13.195-ALPHA-universal.jar
- MineColonies Version (if related bug): minecolonies-0.14.237-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior

MineColonies visitor requirements item count displayed on recruit GUI.

## Actual behavior

MineColonies visitor requirements item count is not displayed on recruit GUI.

![2021-06-25_16 50 03](https://user-images.githubusercontent.com/1421244/123501381-3005a900-d5e0-11eb-9356-2b9167c0da96.png)

## Steps to reproduce the issue

1. Right-click a visitor from the tavern
2. See item displayed on GUI
3. See count missing from GUI

Last worked on MineColonies 231 and Structurize 177.
Broke at MineColonies 232 and Structurize 191.

### Logs

- latest.log: n/a
- crashlog: n/a

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
should be fixed
