### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by lebanni** [ldtteam/Structurize#407]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.197
- MineColonies Version (if related bug): 0.14.262
- Related Mods and their Versions: see crashlog

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log:  https://gist.github.com/lebanni/c95072859f7f0d460269524432eb3267
- crashlog:  https://gist.github.com/lebanni/42abfdcd4b7d1ff09bcc67b349e3366e

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
use java 8

**Comment by Nightenom** [comment]
Fixed in latest
