### ISSUE TITLE
Red X on Server list due to Structurize mod

### ISSUE THREAD

**Issue by IchigoGames** [ldtteam/Structurize#409]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.1.6.5
- Structurize Version:structurize-0.13.198-ALPHA-universal
- MineColonies Version N/A

## Expected behavior
NO Red x from a mod that is not suppose to be clintside only

## Actual behavior
Red X on server when structurize is added i think it seeing it as a clintside mod

## Steps to reproduce the issue

1. add mod to a modpack or by it self
2. start game and try looking at server with the same mods

### Logs
https://www.dropbox.com/s/ckovo469mu9fj6n/latest.log?dl=0

### Notes
small bug it shows red x on server list due to this mod found out it was this one after lots of testing

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

with mod added 
![image](https://user-images.githubusercontent.com/11888162/124691288-35e17100-dea1-11eb-8519-65f9557b476b.png)

with mod Removed
![image](https://user-images.githubusercontent.com/11888162/124691607-af795f00-dea1-11eb-8f4d-6987927fced4.png)

**Comment by Raycoms** [comment]
That's a forge thing, afaik not a problem on our side at all.
