### ISSUE TITLE
Building Tool Structure Preview Crash with Rockhounding Ore Tiers' Bloomery

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/Structurize#41]
### Minecolonies Version

Version: 0.10.48-ALPHA
### Rockhounding Ore Tiers' Version

Version: 3.08

### Expected behavior

-  To be able to place a schematic containing the bloomery

### Actual behaviour

-  The game crashes as soon as I press the checkmark button to place the schematic containing the bloomery.

[Crash Log](https://paste.dimdev.org/acipigasad.mccrash)
### Steps to reproduce the problem

1.  Create a schematic containing the bloomery using the scan tool.
2.  Place this schematic using the building tool.
3.  Crash.
4. ... Profit

**Comment by marchermans** [comment]
Why are the even writing there?

**Comment by Raycoms** [comment]
We are writing the entity to NBT after rotating it.

Am Sa., 24. Nov. 2018 um 11:17 Uhr schrieb Marc Hermans <
notifications@github.com>:

**Comment by marchermans** [comment]
WHAT !?!?!?!
Why that?

**Comment by marchermans** [comment]
Still do not understand why we save it back.

**Comment by Nightenom** [comment]
1.12 is no longer maintained
