### ISSUE TITLE
Structurize (structurize) has failed to load correctly

### ISSUE THREAD

**Issue by BigEyesOMG** [ldtteam/Structurize#410]
Mod File: structurize-0.13.96-ALPHA-universal.jar
Failure message: Structurize (structurize) has failed to load correctly
		java.lang.RuntimeException: Missing some newest data versions. Please update 
               com/ldtteam/structures/blueprints/v1/DataVersion
Mod Version: 0.13.96-ALPHA

**Comment by Nightenom** [comment]
Fill the template next time.
Update to latest
