### ISSUE TITLE
Major z-fighting with new shingles model

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/Structurize#420]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft v1.16.5
- Structurize v0.13.208-alpha

## Expected behavior

- No z-fighting when different shingles are placed together.

## Actual behavior

- As of v0.13.208-alpha, the new shingle models cause major z-fighting if multiple shingle types are placed next to each other, which many buildings in Minecolonies do.
- The shingles had additional bricks added to the edge of models, which overlap each other when placed. 
- Perhaps have the additional bricks appear only if the shingle block does not have another block next to it, a new blockstate maybe?

https://user-images.githubusercontent.com/12000593/129662951-8274f170-7376-4eb6-a105-f9b307122810.mp4

## Steps to reproduce the issue

1. Place a shingle block down
2. Place a different one next to it
3. Observe

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
@leagris

**Comment by leagris** [comment]
Could not reproduce the issue.
Models especially have offsets to prevent z-fighting on overlapping shingle extensions:

![image](https://user-images.githubusercontent.com/1111474/129725409-611fa148-79ec-4ed5-87a5-870b81b1803e.png)

https://user-images.githubusercontent.com/1111474/129725476-eb182d9b-caa0-4754-9bf2-60d34c662b2d.mp4

Could you give more information on your game setup:

- Do you use a rendering altering mod like Optifine?
- Can you describe your Operating System, Video device and driver version?
- Eventually add information about your screen/window size?

**Comment by WenXin20** [comment]
Oh shoot, looks like this is actually my fault. I was testing adding cullfacing to the shingles block after merging the new update into my dev environment. I must've made a mistake when doing so. I reverted the change I made and doesn't happen anymore. :D
