### ISSUE TITLE
Scan tool Replacement feature -- allow placeholder blocks

### ISSUE THREAD

**Issue by AngleWyrm10** [ldtteam/Structurize#422]
### Prerequisites 

- [x] I am running version 0.13.205 of Structurize
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version:  0.13.205-ALPHA

## Is your feature request related to a problem?
Replacing air blocks with placeholder blocks is cumbersome, and the scan tool replacement feature doesn't list placeholder blocks (any of the three) as options

## Enhancement or Change description
Use scan tool Replacement feature to replace blocks in scanned area with placeholder blocks

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
They **are** in the list, but because it searches on the internal name rather than the translated name, you have to search for "substitution" blocks instead.
