### ISSUE TITLE
Bad local variabl type

### ISSUE THREAD

**Issue by tim20010803** [ldtteam/Structurize#425]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this mod compatibility issue is not a duplicate of any existing mod compatibility issue.**

### Context 

- Minecraft Version:1.16.5
- Structurize Version:0.13.210-ALPHA
- Related Mods and their Versions:minecolonies-0.14.346-ALPHA

## Actual behavior

![image](https://user-images.githubusercontent.com/89471956/130647255-94542eac-dc95-451d-a6bc-8d36fe550645.png)

## Steps to reproduce the issue

1. play minecraft 

### Logs

- latest.log: 
-  https://gist.github.com/tim20010803/053ea4f0f9426925ba0e21eb1a0ae410
- crashlog: 
- https://gist.github.com/tim20010803/df5db8591cd08aec7656ed911589e1da

### Notes

---
## Viewers

* Add a thumbs-up to the mod compatibility issue if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
99% Optifine thing, update yours to the latest version
