### ISSUE TITLE
Double slabs only drop one slab

### ISSUE THREAD

**Issue by IchHabeHunger54** [ldtteam/Structurize#428]
### Prerequisites

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.208-ALPHA
- MineColonies Version (if related bug): N/A
- Related Mods and their Versions: N/A

## Expected behavior
In Minecraft, double slabs (the ones that look like a full block) drop two slabs upon destruction, and so should the Structurize ones.

## Actual behavior
They do not. Double slabs still drop only one slab.

## Steps to reproduce the issue

1. Place two slabs of any kind (cactus, beige/brown/cream brick/stone brick) on top of each other.
2. Break them.

### Logs

Not relevant, as the loot table doing what it is supposed to do.

### Notes
The loot table is simply wrong. It should look like this to cover the double-slab case (this is copied from Minecraft with cactus slab values):
```
{
  "pools": [
    {
      "entries": [
        {
          "functions": [
            {
              "conditions": [
                {
                  "block": "structurize:blockcactusslab",
                  "condition": "minecraft:block_state_property",
                  "properties": {
                    "type": "double"
                  }
                }
              ],
              "count": 2,
              "function": "minecraft:set_count"
            },
            {
              "function": "minecraft:explosion_decay"
            }
          ],
          "name": "structurize:blockcactusslab",
          "type": "minecraft:item"
        }
      ],
      "rolls": 1
    }
  ],
  "type": "minecraft:block"
}
```

This one can be copied, and it'll work. You might need to adjust the datagen as well.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
If this issue persists, but I've used these blocks recently and haven't encountered described behaviour, please open new issue on [ldtteam/domum-Ornamentum](https://github.com/ldtteam/domum-Ornamentum/) repo
