### ISSUE TITLE
Crash when attempting to use build tool after scanning structure with doubleslabs mod blocks

### ISSUE THREAD

**Issue by codec-d** [ldtteam/Structurize#430]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this mod compatibility issue is not a duplicate of any existing mod compatibility issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.173-ALPHA-universal and 0.13.210-ALPHA-universal
- Related Mods and their Versions: DoubleSlabs-1.16-3.5.2 and DoubleSlabs-1.16-3.7.1

## Expected behavior

my scanned structure being built

## Actual behavior

Scan tool saves a blueprint of the structure. Build tool crashes on activation when the blueprint file is present in the scans folder.

## Steps to reproduce the issue

1. have the blueprint in the scans folder
2. right click with the build tool to bring up the interface
3. crash

### Logs

- latest.log: https://gist.github.com/codec-d/eebd3700d30bb2bae569b59f657526ab
- crashlog: https://gist.github.com/codec-d/ba4db836320a3ba75fdb0b93005a0b6e

### Notes

I tried removing optifine and that didn't fix the issue. I tried newer releases, no fix. I tried removing double slab mod and rescanning, I was able to place a version of the structure then, with the double slab blocks missing. my original structure only exists in the blueprint file now so I'm just trying to retrieve it in order to use worldedit or mcedit. I can provide the .blueprint file. 
zipped the blueprint to provide it here.
[Mansion_final.zip](https://github.com/ldtteam/Structurize/files/7107231/Mansion_final.zip)
---

## Viewers

* Add a thumbs-up to the mod compatibility issue if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Can you please test this?
https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Structurize_PullRequests2_BuildAndTest/93962:id/build/libs/structurize-0.13.532-PR.jar

**Comment by codec-d** [comment]
> Can you please test this?
> https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Structurize_PullRequests2_BuildAndTest/93962:id/build/libs/structurize-0.13.532-PR.jar

Yes I'll let you know how it works out

**Comment by codec-d** [comment]
had another crash using the patch, same symptoms as before
https://gist.github.com/codec-d/2de0a4dd82e841c82b7d9f587d91b9eb

**Comment by Nightenom** [comment]
fixed upstream <https://github.com/CJMinecraft01/DoubleSlabs/issues/163>
