### ISSUE TITLE
Unable to use custom schematics in Minecolonies on my server.

### ISSUE THREAD

**Issue by VENNTennison** [ldtteam/Structurize#433]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- Structurize Version:0.13.210-ALPHA

## Problem description

I am trying to use custom huts and supply ship etc for minecolonies in my survival server. This server is mine so I have access to all the files etc. In singleplayer, everything works fine, however, on the server, my custom huts are not available as they should be. Using the wand with a townhall block in my inventory, for example, only allows me to access the townhall build separately from the "townhall" option on the dropdown, and when it is placed it includes the placeholder blocks. The ship would not even show up when using the spawn item.

### Notes or related things

I have added my blueprints with the correct naming scheme into the schematics folder of the server.
The server .toml for structurize has the use player schematics set to true. 
I have rebooted the server multiple times.
I have followed the wiki and videos online to the best of my ability.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Were you able to solve it?
