### ISSUE TITLE
Version compatibility problem

### ISSUE THREAD

**Issue by Shaxcur** [ldtteam/Structurize#434]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:16.5
- Structurize Version: 0.13.96

## Problem description

Hey, so i wanted to have mine colonies on my forge server and everything goes great untill there is need to download structurize because it says for this version it needs version 0.13.96 to play so i add this one instead of the newest and then when starting minecraft it says structurize needs to be updated to the newest version so i download the newest one - 0.13.210 and then it says i need to download 0.13.96 and it goes on and on as i start game with different version back and forth without going anywhere, what am i supposed to do 
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Structurize is tightly bound to exact mc version, you seem to be playing an old mcol version, try looking at the following links (they always contains the latest released versions)
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all
https://www.curseforge.com/minecraft/mc-mods/structurize/files/all
