### ISSUE TITLE
Entity Culling  + Optifine G7 + Structurize = Crash 1.16.5

### ISSUE THREAD

**Issue by Mr-Syntax** [ldtteam/Structurize#437]
On minecraft 1.16.5
forge 36.2.0

If i run this combo structurize will crash preventing the pack from loading

i noticed this when i was searching for a solution for entity lag, and it said on the entity culling mod that it was compatible with optifine G7

so i added it to the pack ran it without any problems without optifine and then when i added optifine G7 it crashed

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by Nightenom** [comment]
Probably not our problem
And secondly, we need crash log

**Comment by Mr-Syntax** [comment]
ahh sorry it turns out im the idiot, its says clearly on the mod page that its not compatible with optifine G7 in later version but earlier are
