### ISSUE TITLE
No framed blocks

### ISSUE THREAD

**Issue by Lester702** [ldtteam/Structurize#444]
1. Load world
2. Try and craft or give yourself a framed oak plank

I'm using 1.17.1 on a server

**Comment by ravenbuilder934** [comment]
Intentional, the blocks have been split up into a different mod called Domum Ornamatum

**Comment by Lester702** [comment]
> Intentional, the blocks have been split up into a different mod called Domum Ornamatum

The blocks aren't there either...
They don't exist

**Comment by ravenbuilder934** [comment]
Are you sure? they're now dynamically generated to save space, so I don't think you can find it by searching "framed oak planks" or whatever. try just looking for blocks from domum ornamatum

**Comment by Lester702** [comment]
> Are you sure? they're now dynamically generated to save space, so I don't think you can find it by searching "framed oak planks" or whatever. try just looking for blocks from domum ornamatum

I went into creative and looked in the Domum Ornamatum tab, but it's just the stone cutter I think? I don't remember the name
The version I'm using for Domum Ornamatum is `1.0.9-ALPHA-universal`

**Comment by ravenbuilder934** [comment]
Stone cutter can be used to make the blocks I'm pretty sure. try placing it down and opening its gui

**Comment by Raycoms** [comment]
Yes, and this architecscutter gives you the blocks.

**Comment by Lester702** [comment]
Is there a new recipe for it?
