### ISSUE TITLE
Racks that are in the basement should be filled last.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/Structurize#450]
### Prerequisites 

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- Structurize Version:

## Is your feature request related to a problem?

I am planning to build a basement with tons of racks for my custom L5 warehouse schematic, and I saw that the basement racks have the same chance to be filled like normal racks
I used the tag tool to classify which level is the basement btw.

## Enhancement or Change description

It would be cool to have it so that after all the racks that is on or above the ground level is completely filled, then the structure would pander to those that are in the basement. This would make it more dynamic and fun for people to prepare a proper basement for storage in their warehouse designing.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
no
