### ISSUE TITLE
Cosmetic construction tape

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/Structurize#451]
### Prerequisites 

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- Structurize Version:

## Is your feature request related to a problem?

Construction tapes are quite nicn and I want to use it for decoration, but I cannot pick up the construction tapes that I manually placed down, even with Silk Touch stuff

## Enhancement or Change description

- [ ] Construction tapes that is placed by a worker will not be obtainable when broken
- [ ] Tapes (normal) that are crafted and placed by the player will drop itself when broke.

### Notes or related things

You might want to increase the output for the crafting recipes, 4 outputs instead of just one, this will save materials, they are quite common anyway.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not a structurize issue. Put it on the minecolonies feature request repo.
