### ISSUE TITLE
Can't change max schematic size

### ISSUE THREAD

**Issue by CosmicGlowsticks** [ldtteam/Structurize#453]
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.254-ALPHA-universal

## Problem description
When I try to save a large scan, it always says the max size is 100,000 blocks. I tried to change the config (Structurize-client), but that doesn't seem to be working. I'm not all that familiar with doing it in the files manually, so I might not be doing it right. The file changes back to default whenever I launch a world. 

Default in this case looks like this: 

#Sets the maximum number of parsed GUI window files to be stored for quick loading.
#Range: 0 ~ 100
windowCacheCap = 12

I assume range is what I'm looking for. I added an extra 0 on the end, but it reverted back when I launched the world. (Yes, I saved it.)
Prior to that I copied and pasted the following below that, seeing as it was on the mod page and I assumed that would do it:

#Max world operations per tick (max blocks to place, remove, or replace).

#Range: 0 ~ 100000

maxOperationsPerTick = 1000

I also tried getting rid of the spaces between the lines.
Either way, it reverted back. 

### Notes or related things
As I said I'm not all that familiar with these things, so I could be doing it wrong. If I am, please tell me. 
I also looked at past issues, but the only one I found that would relate didn't give me any relevant information. If there is another with this same issue, I missed it. In that case, my apologies.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's a forge problem. You have to shut down, change the config value, restart.

**Comment by uecasm** [comment]
It will also change back if you try to set a value out of range.  For example, adding a 0 on the end of `windowCacheCap = 12` would make it 120, which is above the max allowed value.

It's also completely the wrong setting, as is the other one (read the comments above them, and that should be obvious).  If you really want to increase the max schematic size, the setting you want is `schematicBlockLimit`.

You also want the structurize-server.toml file, which is in the serverconfig folder of your world.  The client config is the wrong place.

**Comment by CosmicGlowsticks** [comment]
> 
> 
> It will also change back if you try to set a value out of range. For example, adding a 0 on the end of `windowCacheCap = 12` would make it 120, which is above the max allowed value.
> 
> It's also completely the wrong setting, as is the other one (read the comments above them, and that should be obvious). If you really want to increase the max schematic size, the setting you want is `schematicBlockLimit`.
> 
> You also want the structurize-server.toml file, which is in the serverconfig folder of your world. The client config is the wrong place.

Thank you so much, I never would've gotten that on my own. I owe you my life
