### ISSUE TITLE
1.17.1 Famed Timber Blocks not craftable

### ISSUE THREAD

**Issue by ChaoChild** [ldtteam/Structurize#455]
- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.17.1
- Structurize Version: 1.17.1-0.13.253-ALPHA
- MineColonies Version (if related bug): 1.17.1-1.0.95-ALPHA
- Related Mods and their Versions: blockui-1.17.1-0.0.20-ALPHA, domum_ornamentum-1.17.1-1.0.13-ALPHA, jei-1.17.1-8.1.0.31, multi-piston-1.17.1-1.2.1-ALPHA

## Expected behavior
-When placing the build tool and either two wood planks or a wood plank and paper into the crafting table to result in getting a type of framed timber wood.

## Actual behavior
-Nothing shows up in the crafting box. Tested in creative, survival, and with and without JEI.
-Due to this my builder won't continue building until I have these blocks which I can't craft, so they just stand there and do nothing.

## Steps to reproduce the issue
1. Go to the crafting table and try to craft a framed timber block of any kind.
2. No crafted result will show.

### Logs
-I do not have any logs.

### Notes
-No notes.

---
## Viewers
-

**Comment by Raycoms** [comment]
This is now done in Donum Ornamentum 

https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum

**Comment by ChaoChild** [comment]
I changed the version of Domum Ornamentum I was using and it still not working.

**Comment by uecasm** [comment]
The crafting method is entirely different in 1.17.  You need to make the Architect's Cutter and use that to make the blocks (as is mentioned at that link); they can't be made in a regular crafting grid any more.  If you need further help, join the Discord and ask there.
