### ISSUE TITLE
I don't have the timber frame blocks

### ISSUE THREAD

**Issue by Farfi8** [ldtteam/Structurize#456]
Hello,
I just downloaded all the mods that I need, but I was surprised to not be able to build the timber frame blocks, I don't even have those blocks in my creative list. I play in 1.17. Is it something that wasn't added to this version of the mod (even if I can ordered to my builders to build buildings with those blocks) ?

**Comment by Justen-N** [comment]
Not a bug. the 1.17 version of the mod uses Domum Ornamentum, a module. This Module uses the Architect's Cutter block to create the 'timber' blocks, as well as lots of other blocks. The reason that these blocks no longer show up in creative or JEI is that they are generated differently now, and would cover, I believe, about 50,000 blocks, causing it to be unwieldy to search.

**Comment by marchermans** [comment]
The 50000 is a wide understatement it generates an order of magnitude bigger

**Comment by Justen-N** [comment]
My bad on the estimate.
