### ISSUE TITLE
Add "Keep placeholder blocks" creative paste button to Shape Tool

### ISSUE THREAD

**Issue by SaintWacko** [ldtteam/Structurize#465]
### Prerequisites

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version. (the newest beta seems to be newer?)
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context
- Minecraft Version: 1.18
- Structurize Version: 1.18.1-1.0.319-BETA

## Is your feature request related to a problem?
When using the shape tool to place a shape made of placeholder blocks in creative mode, what is instead placed is what a builder would use were they building a structure containing placeholder blocks. e.g. Placing Liquid placeholder blocks instead places water source blocks.

## Enhancement or Change description
The Build tool currently has two creative paste buttons: One which places blocks as though a builder had placed them, and one which places blocks as they are, including placeholders. I would like the Shape tool to also have the creative paste button which places blocks as they are.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is implemented in 1.19.2.
