### ISSUE TITLE
I can't find the Structurize mod that is needed.

### ISSUE THREAD

**Issue by Maurony17** [ldtteam/Structurize#467]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this mod compatibility issue is not a duplicate of any existing mod compatibility issue.**

### Context 

- Minecraft Version:
- Structurize Version:
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes
I can only find the Structurize version 0.13.254-ALPHA but I can't find a trace of 0.13.252-ALPHA. It would be aa big help if someone showed it to me or sent a link to the download page.

---
## Viewers

* Add a thumbs-up to the mod compatibility issue if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
https://www.curseforge.com/minecraft/mc-mods/structurize/files/all
also might want to update to newer version
