### ISSUE TITLE
Crash when trying to use the mod in CaveFactory 1.1

### ISSUE THREAD

**Issue by e30Birdy** [ldtteam/Structurize#470]
- Minecraft Version: 1.16.5
- Structurize Version: structurize-0.13.252-ALPHA-universal.jar
- MineColonies Version (if related bug): minecolonies-1.16.5-1.0.327-ALPHA.jar originally minecolonies-1.16.5-1.0.309-RELEASE.jar was in the pack I am playing
- Related Mods and their Versions:

So basically I am just trying to use the mod in CaveFactory 1.1 beta and getting a crash when using the want from Structurize or even trying to place anything MineColonies related like the hut or supply cart.

https://pastebin.com/VQ40udsU

**Comment by Nightenom** [comment]
My honest guess would be some mod using unsafe mixin, hard to say which mod. Someone more mixin-educated could tell you more.

**Comment by Nightenom** [comment]
Same cause as ldtteam/minecolonies#7882
