### ISSUE TITLE
noSuchFieldError: DIRT crash | 1.18.1 Forge 39.0.18 with Latest Alpha

### ISSUE THREAD

**Issue by ghost** [ldtteam/Structurize#473]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- Structurize Version: structurize-1.18.1-1.0.320-ALPHA
- MineColonies Version: minecolonies-1.18.1-1.0.347-ALPHA (used to create the crash)
- Related Mods and their Versions: 
 Dependencies installed with the 1.18.1 version of minecolonies:
- BlockUI: blockui-1.18-0.0.34-ALPHA
- Domum Ornamentum: domum_ornamentum-1.18-1.0.32-ALPHA-universal
- Multi-Piston: multi-piston-1.18-1.2.2-ALPHA

## Expected behavior
When using the instant place feature (no placeholder blocks), the minecolony building would be placed instead of resulting in a noSuchFieldError: DIRT crash.

## Actual behavior
The v39.0.18 release of Forge 1.18.1 made changes to their tags, which included the removal of the tag forge:dirt. While trying to instantly place down a minecolony builder's hut using the instant place (no placeholder blocks) feature, a noSuchFieldError: DIRT crash occurs, most likely from the usage of the removed forge:dirt tag.

## Steps to reproduce the issue
1. Obtain build tool and a builders hut in creative.
2. Use the instant place (no placeholder blocks) feature to place a level one acacia builder hut.
3. Watch a noSuchFieldError: DIRT crash occur.

### Logs
- latest.log: https://gist.github.com/switchnlade/dad67aad1100dfc215ba44cd93d43b1c
- crashlog: https://gist.github.com/switchnlade/609c07b333f889db43bdadb9b54c6362

### Notes
Link to the removal of forge:dirt tag commit: https://github.com/MinecraftForge/MinecraftForge/pull/7891/commits/38c91607ecdac1e43c88db7790a0a00e49a6d60f
This occurs only on 39.0.18, while using 39.0.17 or earlier, it works as intended.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by NicksCraft2007** [comment]
I am having the EXACT same problem, and my log is going crazy with the amount of crashes occurring because of this. I just wanted to use this mod as an improved version of TekTopia. By the way, which version of Structurize does not cause this crash.

**Comment by ghost** [comment]
> I am having the EXACT same problem, and my log is going crazy with the amount of crashes occurring because of this. I just wanted to use this mod as an improved version of TekTopia. By the way, which version of Structurize does not cause this crash.

It's actually which version of Forge from my knowledge at the moment until it's fixed up, use version 39.0.17. I had a user test this for me over on the Medieval MC modpack's discord and it worked.

**Comment by NicksCraft2007** [comment]
Ok sorry I forgot to read the bottom of the description. I am installing Forge 39.0.17(I was using 39.0.18). I will reply again if it works or does not work.

**Comment by NicksCraft2007** [comment]
It works

**Comment by NicksCraft2007** [comment]
Can you check to see if this has been fixed in forge 39.0.19 with all mods at the newest version(they all have been updated recently)?

**Comment by uecasm** [comment]
This was an intentional break on Forge's side; they're not going to "fix" it.  This PR did fix it for MineColonies and Structurize, however, so just update those to the latest version.

**Comment by NicksCraft2007** [comment]
This issue has been fixed in the latest version of Forge and the mine colonies as well as all other dependency mods of mine colonies.
