### ISSUE TITLE
Crashing on scantool "Show Resources"

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/Structurize#475]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- Structurize Version: .321
- MineColonies Version (if related bug): .349
- Related Mods and their Versions:

## Expected behavior

the resource list

## Actual behavior

scan item, hit show resources, crash

## Steps to reproduce the issue

1. scan building
2. hit show resource button
3. crash

### Logs

- latest.log: 
- crashlog: (https://gist.github.com/SivartMcDorf/22dddcd43b26a2cce82e03f55c27fb9d)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Log

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by uecasm** [comment]
Looks like this was caused by a merge error in dcdbf244e08e2c9e9 removing the entity list icon.
