### ISSUE TITLE
My Schemactics  not showing MyScematics

### ISSUE THREAD

**Issue by Howman** [ldtteam/Structurize#481]
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- Structurize Version: structurize-1.18.1-1.0.326-ALPHA
- MineColonies Version (if related bug): minecolonies-1.18.1-1.0.356-ALPHA
- Forge Version:  forge-1.18.1-39.0.58
- Related Mods and their Versions:

## Expected behavior
My Schematics to show  My Schematics but not show decorations 
I was using news alpha of structurize structurize-1.18.1-1.0.326-ALPHA but would crash game to desk top

## Actual behavior
shows same as decorations 

## Steps to reproduce the issue

just go to my schematics 

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
There was change in loading of packs in August of 22, reopen if issue persists
