### ISSUE TITLE
Using internal or any optifine shaders breaks structurize building preview render

### ISSUE THREAD

**Issue by Z4X4R0FF** [ldtteam/Structurize#482]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I am running the latest version of OptiFine for my Minecraft version.
- [ ] I am running the latest version of this shader for my Minecraft and OptiFine version.
- [ ] I made sure that **this OptiFine issue is not a duplicate of any existing OptiFine issue.**

### Context 

- Minecraft Version: 1.18.1
- Structurize Version: 1.0.326-ALPHA
- OptiFine Version: HD U H4
- Shaders and their Versions:  BSL or internal or any other shaders

## Actual behavior and **screenshots**

![2022-01-30_11 39 08](https://user-images.githubusercontent.com/32410396/151692770-1c2a1ea0-b989-4eb7-b970-4a323c4b8dba.png)
![2022-01-19_10 20 50](https://user-images.githubusercontent.com/32410396/151692774-628f1b10-e8f9-4ad2-90b0-a722958dd61e.png)

## Steps to reproduce the issue

1. Create any world
2. Pick some structure block from Minecolonies (e.g. supply ship)
3. Place it
4. Press Esc and look around

### Logs

- latest.log: https://gist.github.com/Z4X4R0FF/701e82175cc928ff32d796ea20851f40)
- crashlog: 

### Notes
Also i spotted almost equal bug when i turn shaders off completely, leaving only optifne. When placing supply ship with shaders turned off, the water blocks preview teleports away and stands somewhere above the ship preview. 
Also i ve tried to tick on/off some optifine options but this didn't solve issue.
The wrongly placed preview blocks start following player if you press ESC from structurize preview

---
## Viewers

* Add a thumbs-up to this OptiFine issue if you are also affected. This helps the issue become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
1.17 or 1.18 doesn't work with shaders yet, known issue, will get fixed once I have time (cca two weeks from now)

**Comment by Z4X4R0FF** [comment]
Thanks!
