### ISSUE TITLE
[1.18.2] mc bug tracker

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/Structurize#483]
- [ ] [MC-248225](https://bugs.mojang.com/browse/MC-248225) - blockpos euclid distance `Blockpos#getSquaredDistance()` had wrong calculation for ages - especially calliper iirc has fix for that, other mods like pvi/mcol may suffer from this too

- [ ] [MC-105317](https://bugs.mojang.com/browse/MC-105317) - check entities rotation

**Comment by Raycoms** [comment]
Yeah I remember this. I adjusted a few things to our own calc for that. But not everywhere.
