### ISSUE TITLE
No warehouse data

### ISSUE THREAD

**Issue by Derjinjon** [ldtteam/Structurize#484]
### Prerequisites 

- [x ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x ] I made sure that **this mod compatibility issue is not a duplicate of any existing mod compatibility issue.**

### Context  

- Minecraft Version:1.18.1
- Structurize Version: structurize-1.18.1-1.0.341-ALPHA
- Related Mods and their Versions: minecolonies-1.18.1-1.0.402-ALPHA

## Expected behavior
 Use the "Build Tool" to place the "Warehouse" and the  hologram will appear.

## Actual behavior
 Use the "Build Tool" to place the "Warehouse" but nothing appear und you can´t select the warehouse.

]
![warehousebug screenshot](https://user-images.githubusercontent.com/99098485/152661221-119e3f7f-5be9-4a04-9039-958c07fba6f9.png)

## Steps to reproduce the issue

 

1.  use the same combination of mods?
2.  use Building tool with warehous in inventory
3.  no warehouse will appear

### Logs

- latest.log: 
- crashlog: 

### Notes
 I think the data oft the warehouse is missing 

---
## Viewers

* Add a thumbs-up to the mod compatibility issue if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
What versions of the other dependencies are you using? Cos I am using those same minecol and structurize and it shows fine for me.
make sure you don't have duplicates of any mods in your mods folder too

**Comment by Raycoms** [comment]
Are you sure you are on the above versions and you don't have accidentally older versions installed.

**Comment by Derjinjon** [comment]
Yea i solve the Problem...
At first I used (minecolonies-1.18.1-1.0.278-RELEASE) and than installed
(minecolonies-1.18.1-1.0.402-ALPHA) and inadvertently used both versiones...

So maby the data is just missing in (minecolonies-1.18.1-1.0.278-RELEASE) ?

Thank you ;)

Am So., 6. Feb. 2022 um 02:13 Uhr schrieb Talyda ***@***.***>:

**Comment by Derjinjon** [comment]
But the is another bug... You can see it in the picture bellow

I just tried to place the guard tower and there appear strange buildings
and the roof is flying in the air?

same versions I wrote above

Am So., 6. Feb. 2022 um 02:16 Uhr schrieb Raycoms ***@***.***

**Comment by Raycoms** [comment]
roof floating and stuff seems like optifine
