### ISSUE TITLE
Latest Structurize, forge, optifine tested with and without shaders, With shaders only the preview of builds will not stay put and instead follow the player around on the screen until preview is canceled 

### ISSUE THREAD

**Issue by Grimmspecter** [ldtteam/Structurize#488]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I am running the latest version of OptiFine for my Minecraft version.
- [x] I am running the latest version of this shader for my Minecraft and OptiFine version.
- [x] I made sure that **this OptiFine issue is not a duplicate of any existing OptiFine issue.**

### Context 

- Minecraft Version:
- Structurize Version:
- OptiFine Version:
- Shaders and their Versions:

## Steps to reproduce the issue

Latest Structurize, forge, optifine tested with and without shaders, With shaders only the preview of builds will not stay put and instead follow the player around on the screen until preview is canceled only step realy is 
1 turn on shaders
2 try to place structure

### Logs

Latest Structurize, forge, optifine tested with and without shaders, With shaders only the preview of builds will not stay put and instead follow the player around on the screen until preview is canceled

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to this OptiFine issue if you are also affected. This helps the issue become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
please fill in the template - what actual version numbers of each of the mods are you using?

**Comment by Nightenom** [comment]
Update to the latest versions
https://www.curseforge.com/minecraft/mc-mods/structurize/files/all
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all
https://www.curseforge.com/minecraft/mc-mods/blockui/files/all

**Comment by Grimmspecter** [comment]
Cant use latest structurize (1.0.347) with latest minecolonies (1.0.463)

**Comment by Grimmspecter** [comment]
that bein said latest version alpha versions did fix it structurize-1.18.1-1.0.346-ALPHA so yes thank you.
