### ISSUE TITLE
Supply Camps crash to launcher when placed

### ISSUE THREAD

**Issue by DarQuing** [ldtteam/Structurize#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

1.0.361-Alpha

### Current Behavior

Supply camps and ships crash to the launcher when placed. Re-logging in the camps are there.

### Expected Behavior

I expect the game to continue as normal, maybe with a brief freeze since a bunch of blocks are being placed all of a sudden.

### Reproduction Steps

1. Acquire a supply camp or ship (either crafted or in Creative mode)
2. Select any style
3. Position and place it down
4. The game will crash to whatever launcher you're using (I use GDLauncher).

### Logs

https://gist.githubusercontent.com/DarQuing/78aa4d6c9b52df687d7d513213e386b7/raw/23039df5e425b0f5482b9f1e6cd8ce60d687d053/gistfile1.txt

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
