### ISSUE TITLE
Client crashes placing decoration building

### ISSUE THREAD

**Issue by lebanni** [ldtteam/Structurize#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

1.0.362

### MineColonies Version (if related bug)

1.0.521

### Related Mods and their Versions

forge 1.18.2-40.0.19
domum_ornamentum-1.18.2-1.0.41-ALPHA-universal.jar (latest 1.0.44 crashes)
blockui-1.18.2-0.0.47-ALPHA.jar
multi-piston-1.18.2-1.2.3-ALPHA.jar

### Current Behavior

Placing Decoration>Fields/Fortress>Treefarm crashes the client. I play connected to a server.

### Expected Behavior

Client doesn't crash when placing this building.

### Reproduction Steps

Place this buiding in the colony.

### Logs

https://gist.github.com/lebanni/33921c67253274fc585ac87e1bdd0097

### Anything else?

I provided the crashlog. The latest log is too big to fit on gist.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Update Minecolonies it was fixed a few hours ago

**Comment by lebanni** [comment]
1.0.521 seems to be the latest for MC 1.18.2.

**Comment by Talyda** [comment]
Oh! D'oh! You are the second person I did that to today - sorry!

**Comment by lebanni** [comment]
Seems to crash for other buidings also, I tried a house and crashed. Reverting to minecolonies 1.0.519 and structurize 1.0.353 wprks.

**Comment by Talyda** [comment]
You could try downgrading forge to .17 too - there's an open issue on minecolonies github for that

**Comment by Raycoms** [comment]
build failed,  new build incoming
