### ISSUE TITLE
Using forge tags instead of minecraft:stick to support a variant of wooden stick for recipes. 

### ISSUE THREAD

**Issue by MarkusBordihn** [ldtteam/Structurize#497]
### Is there an existing change request for this?

- [X] I have searched the existing change requests.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

ALL

### Related Mods and their Versions

Example mod with additional type of wooden sticks: https://www.curseforge.com/minecraft/mc-mods/material-elements

### Current Behavior

The recipes are restricted to `minecraft:stick` only and not supporting other wooden sticks types.
Which could confuse users if they have different types of wooden sticks and not able to craft the recipes.

### Enhancement or Change description

Replacing `"item": "minecraft:stick"` with `"tag": "forge:rods/wooden"` inside recipes.

See for additional details: https://mcforge.readthedocs.io/en/latest/utilities/tags/#conventions

### Anything else?

Keep up the good work. ;)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
You could make a pull request with that.

**Comment by MarkusBordihn** [comment]
That's fine with me, only want to make sure a PR get's accepted.
