### ISSUE TITLE
Cant craft any structurize block/item MC1.16.5

### ISSUE THREAD

**Issue by jackmish** [ldtteam/Structurize#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.16

### Structurize Version

structurize-1.16.5-1.0.343-RELEASE/BETA

### Related Mods and their Versions

Disabling all mods except jei-1.16.5-7.7.1.127 is not helping
Forge 36.2.20

### Current Behavior

Cant craft any additional block/item from structurize library. JEI is showing them. Need survival mode working. Creative mode is ok, searching items working.

Is there any special crafting table? Maybe wrong tutorials or instruction videos. I dont understand why almost every video is showing creative mode (maybe same reason). Supply camp from 

Minecolonies hasnt any special crafting table.
Suspicious: Maybe "Create" mod has created some configuration with same items. Disabling every mod except structurize and JEI is not helping.

![CantCraftBug](https://user-images.githubusercontent.com/102487903/160450597-697c8152-07f7-433a-afa3-596e727c5d3e.jpg)

### Expected Behavior

I want to play one of the greatest Minecraft mods.

### Reproduction Steps

1. Disabled all mods except structurize and jei or not
2. Go to crafting table for example in supply camp from minecolonies
3. Use crafting table and search recipe with JEI or without JEI
4. Recipe is showing in JEI, but crafting table doesnt show any product. Empty product not clickable.

### Logs

https://gist.github.com/jackplackjack/200bd5a3ce5883f2f00bfe6d9f9b486a

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Start with updating minecolonies to the latest alpha, and the correct version of structurize for that version - the versions you are using are well out of date =)

**Comment by jackmish** [comment]
[Solved] Thanks a lot.

Few minor sub-problems:
1. I need to update few other mods, but it could be fine or ill find some previous structurize version.
2. Minecolonies are registering automaticly recipes. Structurize is ok by default only with new game.
With my old saves ill rather use console /recipe give <player> *
3. I dont know how i didnt saw newer version of structurize and minecolonies. Maybe button "show all" in curseforge should works by default.

**Comment by jackmish** [comment]
[Final solution]
1. Many backups
2. Update Structurize, Minecolonies, Forge (latest alpha versions of mods with CurseForge are hidden by default, or at right of homepage of mod)
3. My saves were corrupted with new versions. (conflict with PokeCube mod blocks)
a) with this solution u'll lose Structurize/Minecolonies progress
b) disable mods, and run game/save without Structurize/Minecolonies (u can disable mod by moving to other folder)
c) enable mods and all should be ok
