### ISSUE TITLE
Blockout renders item icons with durability bars weirdly

### ISSUE THREAD

**Issue by uecasm** [ldtteam/Structurize#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.16

### Structurize Version

1.0.392-RELEASE

### Current Behavior

![image](https://user-images.githubusercontent.com/539951/169553153-b94b5da6-0071-4d5b-88bf-50204612eb69.png)

The durability bar appears to be rendered almost full height.

### Expected Behavior

The durability bar should only be at the bottom of the icon, same as vanilla.

### Reproduction Steps

1. Put some items with non-full durability in the Warehouse.
2. Click on the search button.

### Logs

n/a

### Anything else?

It displays as expected in 1.18.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
There's also the other long-standing problem where the item counts are rendered above everything else, including the hover tooltips (which is very weird).  I haven't checked if this happens in 1.18 too or not.

**Comment by Nightenom** [comment]
I have fixed item count in 1.18 iirc, there was rendering change between 1.16-18 that makes the change not backportable. Might want to look into that one again..
