### ISSUE TITLE
Upgradable deco items not recognized in server folder

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/Structurize#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

401

### MineColonies Version (if related bug)

751

### Related Mods and their Versions

1. forge 39.1.2

### Current Behavior

any deco item or custom item to overwrite an existing item in the server folder isn't recognized properly.  (in single play works as expected)

Built a 2 level sheep farm will build level 1 but not 2
Built a custom 5th level to the fortress greenhouse deco, and rescanned 1st 4 levels with minor tweaks, when built only builds originals from the server
Built a level 1 hallstone from cavern/infrastructure it is not upgradable to level 2

### Expected Behavior

described above

### Reproduction Steps

Upload custom upgradable deco's to server and it won't upgrade past initial level, though all are listed in the list

### Logs

https://gist.github.com/SivartMcDorf/9c03bebf433c4711d241111589374611

### Anything else?

have been working with discord for days trying to figure this out.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SivartMcDorf** [comment]
This came up again in chat so I thought I would share the original convo with all the supporting info where motionless train helped check it out
https://discord.com/channels/139070364159311872/724810019928801290/982174390009618482

**Comment by SivartMcDorf** [comment]
2nd person reporting similar
https://discord.com/channels/139070364159311872/724810019928801290/982173800617611294

**Comment by SivartMcDorf** [comment]
3rd person 
https://discord.com/channels/139070364159311872/724810019928801290/982169238628335626

**Comment by Moobien** [comment]
Had McDorf test it with some alternate schematics, also tested with some adjusted and rescanned cavern schematics.  same results.

**Comment by uecasm** [comment]
Can you still preview all the different levels successfully?  Can you creative-paste each level?

If those work, and it's only the upgrade via the decoration controller that's not working, then this may be a Minecolonies issue rather than a Structurize issue...

**Comment by SivartMcDorf** [comment]
If I replace standard designs which I did with the fortress deco for greenhouse 1-4 the preview shows the original and not the new design and build normally.  However, I can still see the 5th level I added.  If I try to build the 5th level it will only build level 1, though I can paste it in.

When it comes to designs not replacing a standard design then I can only build the first level and can't upgrade, but either can be pasted in.  These preview as expected.

**Comment by SivartMcDorf** [comment]
Any chance this is being looked at?  I am having to rescan things in single player to be able to put them on the server
without using creative to paste in top level

**Comment by Nightenom** [comment]
Absolutely blind guess, correct folder/file permissions on server (assuming it's linux server)? Also both logs doesn't contain anything from play time, just loading phase, and if possible debug logs would be better. Generally speaking, did u try to reproduce in isolated setup = only our mods? (Other mods can change vanilla code in insane ways)

Side note for us: it seems this needs to debugged on mcol side

**Comment by SivartMcDorf** [comment]
It's bisect hosting the server.  I don't know anything about folder perms I
am the owner of the server and have admin access on the computer.   I only
have one server and quite a few playing it so no way to test in an isolated
setup that I would know how to do.   Never seen debug logs wouldn't know
how to get them.

**Comment by Nightenom** [comment]
>  so no way to test in an isolated setup

well, in case of future requests - isolated setup is as simple as that:
a) pick latest version of forge and install it for both client and server
b) add mods to both client and server mods folder
c) test the issue you have

> Never seen debug logs wouldn't know
how to get them.

same as logs/latest.log but logs/debug.log
if bisect doesnt provide them then message their support

**Comment by SivartMcDorf** [comment]
I've spent a lot of time on this already.  So if you don't think it's a bug
then I will deal with it but not going to jump through more hoops.  I will
try to upgrade on on the server then download the debug log if I can find
it but then I'm done. I don't mine helping but I've gone way farther than
normally would have to help test this out already.  Isolated tests are
great but only if you have the resources which I don't without unconvincing
a lot of others and possibly screwing up my server.

**Comment by Raycoms** [comment]
I am reworking the entire backend handling, that's why I haven't looked into the issue. It will probably solve itself with the new system entirely

**Comment by SivartMcDorf** [comment]
Ok thanks Ray.

**Comment by SivartMcDorf** [comment]
Pretty sure this is resolved in the new tool
