### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Moobien** [ldtteam/Structurize#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

411

### MineColonies Version (if related bug)

1.18.2 - 798

### Related Mods and their Versions

Forge: 40.1.48
DO: 50
BlockUI: 48

### Current Behavior

Just had a random crash. Pasted in a building wrong, went into scan tool and used the undo option. then went to replace the building and the game froze and crashed when activating the build tool.

Orion if you are aware of this already then feel free to close this issue.

### Expected Behavior

not to crash?

### Reproduction Steps

as per current behaviour section

### Logs

https://gist.github.com/Moobien/a0e691fd012ce4442983d2068bf59c6e

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Need the specific blueprint, ie. discord message me the file or something like that

Issue: some random CampfireBlockEntity has wrong position set -> wrong backing blockstate is grabbed -> crash

**Comment by Moobien** [comment]
it was the caledonia citizen 4 i was pasting

**Comment by Nightenom** [comment]
Was fixed somewhen in past
