### ISSUE TITLE
Structurize Crash on mod Loading with optifine

### ISSUE THREAD

**Issue by DefaultUSERNAME9** [ldtteam/Structurize#513]
### Is there an existing OptiFine issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize, OptiFine and shader Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods and shaders that are part of my problem.

### Did you ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.16

### Structurize Version

structurize-1.16.5-1.0.392-RELEASE

### OptiFine Version

HD U G8

### Shader Names and Versions

None

### Related Mods and their Versions

1.Forge Version 36.2.33
2.Minecolonies version minecolonies-1.16.5-1.0.830-BETA

### Current Behavior

Crashed during mod loading

### Expected Behavior

Load during mod loading

### Reproduction Steps

1.Installed Optifne
2.Crashed during loading

### Logs

https://gist.github.com/DefaultUSERNAME9/7370d090139a9b512295317aade631e0

### Anything else?

Crash Log
https://pastebin.com/VvMiDy6Z

### Footer

Need help in fixing this issue

**Comment by Nightenom** [comment]
Not us, unfortunately we are just calling some optifine method, which was changed by some other mod, there is no sign of which mod though. Your only possibility is to perform binary search to find the problematic mod.
