### ISSUE TITLE
[Crash] Crash on Forge server 1.19

### ISSUE THREAD

**Issue by Zano1999** [ldtteam/Structurize#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

1.19-1.0.417-ALPHA

### Related Mods and their Versions

Forge: 41.0.98
BlockUI: 1.19-0.0.52

### Current Behavior

Server crash with the mod installed

### Expected Behavior

Server start

### Reproduction Steps

1. Install the mod into the server
2. Start the server
3. Crash

### Logs

https://pastebin.com/nh4SKwB5

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not a bug. We didn't update to the latest forge yet
