### ISSUE TITLE
Crash by starting the game.

### ISSUE THREAD

**Issue by Taknax** [ldtteam/Structurize#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

1.0.424-ALPHA

### Related Mods and their Versions

1. Forge Version: 40.1.68

### Current Behavior

After i update Structurize from 1.0.411-ALPHA to 1.0.424-ALPHA, then my game crash by starting directly. It gives no crashlog, so maybe it is a clientsided issue. I use Minecraft 1.18.2, Forge 40.1.68 and +130 mods, but with the 1.0.411-ALPHA it was running well. I send my latestlog and debuglog and hope you can identify the issue.

### Expected Behavior

No crash by game star.

### Reproduction Steps

Combine the modlist and start the game.

### Logs

https://github.com/ldtteam/Structurize/issues/new?assignees=Nightenom&labels=Bug&template=10-bug-report.yaml

### Anything else?

[debug.log](https://github.com/ldtteam/Structurize/files/9238175/debug.log)
[latest.log](https://github.com/ldtteam/Structurize/files/9238176/latest.log)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Looking at the logs, are you sure u use correct latest versions of ur mods? And this is 99% not us, try binary search to locate offending mod
