### ISSUE TITLE
Structurize Incombatibility With DoubleSlabs (1.16.5)

### ISSUE THREAD

**Issue by HeraMain** [ldtteam/Structurize#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.16

### Structurize Version

1.0.418-ALPHA

### MineColonies Version (if related bug)

N/A

### Related Mods and their Versions

DoubleSlabs 1.16-3.7.3.jar

### Current Behavior

When selecting blueprints from the dropdown menu (using the build tool) that use DoubleSlabs entity slabs the game hangs and then crashes. Blueprints using vanilla blocks or a combo of vanilla and modded blocks (not DoubleSlabs) work as intended. 

### Expected Behavior

Use build tool to place blueprints in creative mode by selecting the blueprint (rendering the preview) and then the green check mark (which will load it into the world).

### Reproduction Steps

1. Scan a build (with the scan tool) that utilizes DoubleSlab blocks (two unlike slabs put together). 
2. Attempt to place this new blueprint with the build tool. 
3. The game will freeze and then crash.

### Logs

https://pastebin.com/804VxBZ8

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
1.16 is EOL
anyway, this seems to be bug in DoubleSlabs, where they did not adapt to forge API change properly
