### ISSUE TITLE
[BUG] Hilbert build mode

### ISSUE THREAD

**Issue by ethansyy** [ldtteam/Structurize#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.984

### Structurize Version

1.18.2-1.0.424

### Current Behavior

Sometimes builders miss a whole column of a building.
Repairing the building does not fix the problem.

### Expected Behavior

Buildings should be intact

### Reproduction Steps

It just happens sometimes with Hilbert build mode.
Not sure if other build modes have the same problem.

### Logs

https://gist.github.com/ethansyy/d8358bdcb4aacf82fbe603517390b30a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by dupontct** [comment]
I have found that when creative pasting in the Fortress Style moatsmallgate.blueprint while using the hilbert build mode it always skips a column of the build. 

![hilbert missing column](https://user-images.githubusercontent.com/29468/192159158-50b229da-9b08-47a9-91d3-4360f7cf9dcc.png)
The picture shows the 2 moatsmallgate pasted into the world the one on the left was using the default build mode, on the left the hilbert build mode.

The build tool rendering before pasting is correct.

Attached is the .blueprint file in case it gets changed,
[moatsmallgate.zip](https://github.com/ldtteam/Structurize/files/9641489/moatsmallgate.zip)

This is tested with:
1. minecolonies-1.19.2-1.0.1046-ALPHA.jar
2. structurize-1.19.2-1.0.446-ALPHA.jar
3. blockui-1.19-0.0.61-ALPHA.jar
4. domum_ornamentum-1.19-1.0.60-ALPHA-universal.jar
