### ISSUE TITLE
Add BlockUI to dependencies

### ISSUE THREAD

**Issue by ghost** [ldtteam/Structurize#531]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

structurize-1.19.2-1.0.443-ALPHA

### Is your feature request related to a problem?

Yes, I had to search my console log to find out that I required BlockUI.

### Feature description

I am just requesting a simple addition of BlockUI to the CurseForge page under dependencies to notify people that they need BlockUI for structurize.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Done
