### ISSUE TITLE
Build tool not rotating width and length

### ISSUE THREAD

**Issue by Jinotad** [ldtteam/Structurize#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

structurize-1.19.2-1.0.446-ALPHA.jar

### MineColonies Version (if related bug)

minecolonies-1.19.2-1.0.1039-ALPHA.jar

### Current Behavior

When I hit the rotate option on the build tool's preview. It visually displays the rotated shape; however, the width and length values are not changed.  Upon hitting Build, it build's the shape according to the numbers displayed, rather than what is visually displayed.

![2022-09-23_10 49 07](https://user-images.githubusercontent.com/85356635/191997376-efb19dc0-708c-4d70-99aa-60ee656bd476.png)
![2022-09-23_10 49 11](https://user-images.githubusercontent.com/85356635/191997387-f033411c-204d-4a28-b6df-4c25688ce829.png)

### Expected Behavior

When hitting the rotate, the values for length and width switch.

### Reproduction Steps

Use the build tool, set width to 10 and length to 1.  Hit the rotate button, click build.

### Logs

https://gist.github.com/Jinotad/1cd6ea05ffea8382f9e529a911e3e39f

### Anything else?

I performed the build just before pulling the log

Minecraft 1.19.2

The hub forced me to select minecraft version between 1.16 or 1.18, had no option for selecting 1.19

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
The width/length values not swapping when rotating is intended; you're defining the original shape and the rotation is applied afterwards.  Placing differently from the preview is a bug, however.
