### ISSUE TITLE
Add pt_br support in crowdin

### ISSUE THREAD

**Issue by FITFC** [ldtteam/Structurize#547]
### Is there an existing change request for this?

- [X] I have searched the existing change requests.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.0.348-ALPHA

### Current Behavior

Improve consistency with the Portuguese-Brazilian language

### Enhancement or Change description

Add pt_br support in crowdin

Order placed on Crowdin
https://crowdin.com/project/structurize/discussions/2

I want to start translating to Structurize, the Minecolonies translation has already been completed, but it's weird to have a part of the mod in Portuguese and the other dependency in English... to improve the coherence between the mods and the language I want to make a structurize translation, good that I'm reviewing it at the same time I do (For the structurize translation, respect the official pt_BR translation)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
done
