### ISSUE TITLE
[1.14.4] Sidedness issue launching on a dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/Structurize#55]
Sidedness changed in 1.14

structurize-0.10.115-ALPHA.jar

https://gist.github.com/ProsperCraft/589dc4756633020efa7eee2215f989bd

**Comment by marchermans** [comment]
@Raycoms some event handler is loading the client side class in the Structurize constructor.

**Comment by ProsperCraft** [comment]
This is not fixed in 

structurize-0.10.121-ALPHA

https://gist.github.com/ProsperCraft/fefde846e6fb9217bee74e6a2605b09b

**Comment by marchermans** [comment]
I know was an accident

**Comment by Nightenom** [comment]
Probably needs to be solved using OnlyIn(Dist.CLIENT)

**Comment by Raycoms** [comment]
Fixed
