### ISSUE TITLE
Curseforge doesn't list dependancies anywhere

### ISSUE THREAD

**Issue by PurpleHel** [ldtteam/Structurize#557]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

structurize-1.19.2-1.0.462-ALPHA.jar

### Problem description

The curseforge listing doesn't list ANYWHERE that blockui is a required dependency. Not in the mod description, not on the relations page, and not on the individual file page.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Minecolonies Changelog
Version: 1.19.2-1.0.1129-ALPHA
Required Dependencies:
Structurize: 1.19.2-1.0.452-ALPHA (or above)
Multi-Piston: 1.19-1.2.14-ALPHA (or above)
BlockUI: 1.19-0.0.64-ALPHA (or above)
Domum Ornamentum: 1.19-1.0.58-ALPHA (or above)

From curseforge

**Comment by PurpleHel** [comment]
It's not listed on the structurize page. Being listed on the minecolonies page doesn't help when just looking at structurize.

**Comment by Raycoms** [comment]
Weird curseforge glitch, I opened structurize and it shows this first, anyway, pushed the changelog to 1.19 structurize too
