### ISSUE TITLE
Rubidium visual glitch

### ISSUE THREAD

**Issue by arijmogh** [ldtteam/Structurize#559]
### Is there an existing compatibility issue for this mod?

- [X] I have searched the existing issues.

### Are you using the latest Structurize and your mod Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-1.0.468-ALPHA

### Your Mod Name and Version

rubidium-0.6.2

### Related Mods and their Versions

forge: 43.1.23
minecolonies: 1.19.2-1.0.1137-ALPHA
domum_ornamentum: 1.19-1.0.64-ALPHA-universal

### Current Behavior

![2022-12-11_19 04 24](https://user-images.githubusercontent.com/120334856/206924043-19621124-4caa-4299-ae8f-64f5c1d692ae.png)
![2022-12-11_19 26 24](https://user-images.githubusercontent.com/120334856/206924046-5c747c4e-7ecb-4f91-8ed5-eef63913c784.png)

when previewing a building or a shape a visual glitch happens

### Expected Behavior

the visual glitch doesnt happen

### Reproduction Steps

1.get build or shape tool
2.right click and try to preview a building or a shape
3.a visual glitch happens

### Logs

https://pastebin.com/d8hG3jkx

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by marchermans** [comment]
Report this to Rubidium we use vanilla features to render these structures.
