### ISSUE TITLE
Unable to have more than 9 building categories in build tool.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/Structurize#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

470

### Current Behavior

Build tool appears limited to 9 folders/categories in the build tool. -refer to screenshots.
as you can see there is 10 folders in that style.  the storage folder showed fine until the littlelogistics folder was added at which point the storage folder was no longer showing.

### Expected Behavior

I expect all the folder icons to show.

### Reproduction Steps

n/a

### Logs

n/a

### Anything else?

![image](https://user-images.githubusercontent.com/17806806/207989351-1ec37f06-a12e-486f-807d-42a026133bd1.png)
![image](https://user-images.githubusercontent.com/17806806/207989509-d30fe261-16cd-48da-be8a-33fe37749e7f.png)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is currently intended. Length is on the same level as the hotbar

**Comment by Moobien** [comment]
> That is currently intended. Length is on the same level as the hotbar

I figured that much but can you expand it, maybe a 2nd row.

**Comment by uecasm** [comment]
The number of subcategories is not limited; it just gets a scrollbar.  So figure out which of the existing categories it best fits into and put it there.  Or make a new parent category for both.
