### ISSUE TITLE
Schematic Cannot Paste Successfully

### ISSUE THREAD

**Issue by cclee1103** [ldtteam/Structurize#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-1.0.472-BETA

### Problem description

When a blueprint was being pasted, after clicking the "paste schematic" button, the game will just freeze and crash to desktop. Sometimes, large blueprints will cause the crash even when it is done in a superflat world.

### Anything else?

[crash-2023-01-03_21.31.25-server.txt](https://github.com/ldtteam/Structurize/files/10336976/crash-2023-01-03_21.31.25-server.txt)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
You have not installed the Domum Ornamentum mod, which is also a dependency of Structurize.  Though it's strange you didn't get an FML error about that.
