### ISSUE TITLE
Old preview stays when switching to a new one on server

### ISSUE THREAD

**Issue by YogoGeeButch** [ldtteam/Structurize#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.0.484-ALPHA

### MineColonies Version (if related bug)

1.0.1270-ALPHA

### Related Mods and their Versions

domum_ornamentum-1.19.3-1.0.84-ALPHA
blockui-1.19.3-0.0.70-ALPHA
Forge 44.1.0

### Current Behavior

Old preview will stay when cycling through previews. The new preview can be X'ed out, but the old one cannot, leaving a permanent preview unless I leave the server and come back in. This also causes minecraft to crash for the other players in the server. Issue is not re-creatable unless both players have the option to view each others preview placements.
![2023-03-07_18 16 13](https://user-images.githubusercontent.com/46230199/223586247-0e72e897-44e9-4a74-a055-d86b39614179.png)
![2023-03-07_18 16 18](https://user-images.githubusercontent.com/46230199/223586250-813e8160-e2f0-421b-8d4d-119cb35e9d09.png)

### Expected Behavior

Get rid of preview when switching through them, don't crash minecraft.

### Reproduction Steps

join a server
allow others to see your preview, and allow seeing others previews for 2 people.
while looking at one building preview, swap to another one.
It will stay, attempt to X out the old one.
New one will disappear, old one will not, other player viewing your preview will crash so hard it closes out discord somehow.

### Logs

https://gist.github.com/YogoGeeButch/fe4e61b38c711b0646170bdfac2b9cf2

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
hi, we need crash log if sth crashes

**Comment by Nightenom** [comment]
Fixed in 1.21 because of "blueprint instance <-> server" pinning
