### ISSUE TITLE
Crash to desktop when viewing blueprints

### ISSUE THREAD

**Issue by v-lkyrie** [ldtteam/Structurize#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

structurize-1.19.2-1.0.491-ALPHA.jar

### MineColonies Version (if related bug)

minecolonies-1.19.2-1.0.1391-BETA.jar

### Related Mods and their Versions

1. Modpack didn't specify forge version
2. blockui-1.19-0.0.69-ALPHA.jar
3. domum_ornamentum-1.19-1.0.76-ALPHA-universal.jar
4. Issue persists with Oculus and Rubidium (and its associated mods) turned OFF

### Current Behavior

The client will render the blueprint and crash after a few seconds or instantly.

### Expected Behavior

Blueprints to render without crashing

### Reproduction Steps

1. Claim abandoned colony
2. Change theme (I used arcane and shire)
3. Attempt to build a builders hut
4. Render blueprint
5. Crash

### Logs

https://gist.github.com/v-lkyrie/2bcebf27e3e6afe44222fc6f88d72e63

### Anything else?

I am using the Medieval MC modpack, I have updated everything associated with minecolonies to their newest build.

Client crash: https://gist.github.com/v-lkyrie/b62600f7cded0900a2b7f4dba9952e99

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Issue indentified, fix not easy, what kind of blueprint is that (ours/yours)? if it yours you can mitigate by not putting things in item frames, if its ours just tell us what's the name/path of blueprint

**Comment by v-lkyrie** [comment]
The crash persists whether or not I'm using the high magic or shire theme, also works with antique. I'm just trying to place a builders hut to repair the colony, I got it to place down but crashed immediately afterwards and when I loaded back in it didn't exist.
I don't know how to use custom themes so I'm using themes provided with the minecolonies.

**Comment by Raycoms** [comment]
Can you try without: 		DramaticDoors-Forge-1.19.2-2.3.3.jar              |Dramatic Doors                |dramaticdoors                 |1.19.2-2.3.3        |DONE      |Manifest: NOSIGNATURE
 ?

**Comment by v-lkyrie** [comment]
Tried it, still crashed my game. 
Latest log: https://gist.github.com/v-lkyrie/9a444c0bea4261c77c3ee69fecb5240e

**Comment by Raycoms** [comment]
Uploaded a fixed version
