### ISSUE TITLE
Vision breaks

### ISSUE THREAD

**Issue by Psychoren** [ldtteam/Structurize#584]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-1.0.491

### Related Mods and their Versions

Forge 43.2.0
BlockUI 1.19-0.0.69
Domum ornamentum 1.19-1.0.79

### Current Behavior

![image](https://github.com/ldtteam/Structurize/assets/135843524/02e5a1d7-3099-4f74-ada9-1a90d037ae4d)
![image](https://github.com/ldtteam/Structurize/assets/135843524/199f1e89-95d5-4bf1-934b-3c69a5d43620)

### Expected Behavior

Normal vision

### Reproduction Steps

Anything related to using tools and placing buildings which came from structurize

### Logs

https://gist.github.com/Psychoren/55e6e0b76140e6fad9cd4eb923e4aa4e/revisions#diff-6eb5aa2af122281945d8d42cc285a04af319c927fec0b2e03ce47987c39985a2

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
hi, try different shader mod, optifine is not recommended due to stability issues

**Comment by Psychoren** [comment]
> hi, try different shader mod, optifine is not recommended due to stability issues

Thx i turned off complementary and its solved. Can you advice any shaders tho its would be great

**Comment by Nightenom** [comment]
Rubidium (Sodium based for forge) / Oculus (Iris based for forge)
complemetary should work with above mentioned (i was told so, no disclaimer)

**Comment by Psychoren** [comment]
> Rubidium (Sodium based for forge) / Oculus (Iris based for forge) complemetary should work with above mentioned (i was told so, no disclaimer)

You are great thanks
