### ISSUE TITLE
Minecolonies on minecraft 1.18.2 needs directly Structurize-1.0.424-ALPHA  to run. But no packed release can be found, and code version cannot be packed.

### ISSUE THREAD

**Issue by Nyagguar** [ldtteam/Structurize#586]
### Is there an existing compatibility issue for this mod?

- [X] I have searched the existing issues.

### Are you using the latest Structurize and your mod Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you ask on Discord?

- [ ] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

1.0.424-ALPHA

### Your Mod Name and Version

Minecolonies, any version released on Curseforge for 1.18.2

### Related Mods and their Versions

minecraft 1.18.2 with Forge 40.2.0
Any versions of either Minecolonies or Structurize released on forge for minecraft1.18.2 is tested, but none could work.

### Current Behavior

When packing the Structurize-1.0.424-ALPHA code, the report noted:

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for LetSDevTogether_Structurize:LetSDevTogether_Structurize_dsl:1.0-SNAPSHOT: The following artifacts could not be resolved: org.jetbrains.teamcity:configs-dsl-kotlin-parent:pom:1.0-SNAPSHOT (absent): org.jetbrains.teamcity:configs-dsl-kotlin-parent:pom:1.0-20230611.083536-1 was not found in https://buildsystem.ldtteam.com/app/dsl-plugins-repository during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of teamcity-server has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 9, column 11

Which might mean I cannot reach the related plugins from the adress written in pom. Not sure if those pages were working or not.

### Expected Behavior

It would be appreciated if a packed Structurize-1.0.424-ALPHA could be seen on forge.

### Reproduction Steps

A packed release of 1.0.424-ALPHA is desired, or the expectation from Minecolonies  releases for  1.18.2 adapted to the latest available version of  Structurize.

### Logs

https://pastebin.com/6F8KbX7B

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Make sure to enable alphas on Curseforge

**Comment by Nyagguar** [comment]
> Make sure to enable alphas on Curseforge

thx，I will inform my friends of likely issues.
