### ISSUE TITLE
Bug in PlacementHandlers

### ISSUE THREAD

**Issue by deVDem** [ldtteam/Structurize#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

1.20-1.0.590-BETA

### MineColonies Version (if related bug)

1.20.1-1.1.28-RELEASE

### Related Mods and their Versions

1. Forge: 47.1.3
2. BlockUI: 1.20-0.0.84-ALPHA
3. Donum: 1.20-1.0.110-RELEASE-universal=

### Current Behavior

When improving the building, as far as I understand, the required blocks are being received, with a check for a block in Worldgen in the file PlacementHandlers.java on line 229. In theory, he should get a block that is under the structure, but it does not work.

### Expected Behavior

In my case, the height between the structure and the lower block is more than 10 blocks, which makes possibleSupport (248 line) null. This is solved, I think, by increasing the iterations of the for loop or changing the algorithm or exception handling.

### Reproduction Steps

Just check a screenshoot. I tried upgrade my warehouse (yes, in the air xD)
![image](https://github.com/ldtteam/Structurize/assets/39949986/ff49da92-8210-47ad-81f1-de399c5cb8bb)

### Logs

https://pastebin.com/4sftSZmU

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Builders dont build support structures for building you have placed unless they are specifically in the schematics (which there isnt in this one here. The check you are talking about is for falling blocks like gravel etc. We place support under gravel. Either a worldgen block, or if we cant find a suitable one, then dirt.
Its the players job to make sure the buildings are built on suitable ground.

**Comment by deVDem** [comment]
Okay, I understand what this function is for. The problem is that if the block is not found, then an exception is thrown, which causes the server to crash. This is what I wanted to fix :)

**Comment by deVDem** [comment]
Oh, and I also sent the wrong logs. I'll send a little later.

**Comment by Raycoms** [comment]
Ah, please send the logs then so that I can fix it.

**Comment by deVDem** [comment]
Required log: https://pastebin.com/UGmCAGpC

I had to delete a couple of duplicate lines, due to the limitations of Pastebin, the essence has not changed.

**Comment by deVDem** [comment]
I compiled jar-file with your fix, it works great, I can continue playing on my server! Waiting for the release. Thank you! :)
