### ISSUE TITLE
Event Launcher Error from Structurize

### ISSUE THREAD

**Issue by DSMister** [ldtteam/Structurize#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

 structurize-1.19.2-1.0.603-RELEASE.jar

### MineColonies Version (if related bug)

 minecolonies-1.19.2-1.1.50-BETA.jar

### Related Mods and their Versions

1. Forge version: 43.2.14 (this cannot be upgraded as this is from Kinetic Hosting)
2. BlockUI: blockui-1.19-0.0.69-ALPHA.jar
3. Domum Ornamentum: domum_ornamentum-1.19-1.0.114-BETA-universal.jar

### Current Behavior

Most times when a raid is expected to occur, a tick error occurs, causing the server to crash.

### Expected Behavior

Raids should go by smoothly without any tick issue.

### Reproduction Steps

1. Start a raid on a multiplayer server
2. Tick error occurs

### Logs

https://gist.github.com/DSMister/cea217fb8949fbdce8346b0e3d0d8753

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
