### ISSUE TITLE
Build tool shows nothing

### ISSUE THREAD

**Issue by Jinotad** [ldtteam/Structurize#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

structurize-1.19.2-1.0.629-RELEASE.jar

### MineColonies Version (if related bug)

minecolonies-1.19.2-1.1.93-BETA.jar

### Related Mods and their Versions

Forge - 43.2.13

Modpack: MineColonies Official - ColonyVenture-2.7

### Current Behavior

Using the build tool shows an empty screen. If I click Switch Pack, nothing shows up and I'm unable to click Cancel (Hovering over Cancel and the text changes colors, but unable to click. Can hit Esc to back out of Switch Pack)

If I open up the build menu on a hut, the resources needed field stays blank. But I can tell the hut to upgrade.

Wearing the builders goggles, no upgrade previews are shown. 

This happens both in multiplayer and single player, in the nether and over world. (Tested in a newly created Flat World.)

![2023-08-15_15 31 12](https://github.com/ldtteam/Structurize/assets/85356635/a6f624e6-9472-4611-8235-17e81053425f)
![2023-08-15_15 31 13](https://github.com/ldtteam/Structurize/assets/85356635/3c5d8e81-6808-4a94-aa85-4240c1e6c4e1)
![2023-08-15_15 37 01](https://github.com/ldtteam/Structurize/assets/85356635/71a67be3-e857-4eda-8bdd-41ecea6dda13)

### Expected Behavior

Working as expected

### Reproduction Steps

I don't know how it could be reproduced.

### Logs

https://pastebin.com/fUgE6sxR

### Anything else?

This happened after ColonyVenture updated from 2.6 to 2.7

I have tried repairing the modpack, installing a fresh modpack, removing the Minecraft folder from curseforge itself and did a fresh reinstall of minecraft + Modpack. Updated Java, restarted the computer. No changes. 

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Jinotad** [comment]
The most bizarre thing,  It is now working properly again.

**Comment by Jinotad** [comment]
Update:  It looks like if I start the modpack, log onto the Patron Server.  The build tool doesn't work properly, even if I switch to a single player world.

If I start the modpack, and launch the single player world.  The build tool works properly, then log onto the server, the tool works properly on the server.

**Comment by Raycoms** [comment]
Should be fixed now I believe

**Comment by Raycoms** [comment]
Can you check if this is fixed?
