### ISSUE TITLE
[1.19.2] Mirrored Buildings Previews Roated 180

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/Structurize#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-1.0.630-RELEASE

### MineColonies Version (if related bug)

1.19.2-1.1.158-BETA

### Current Behavior

When the preview is displayed for a mirrored building, the preview is showing up rotated 180 degrees. This only appears to apply to buildings that are mirrored.

Building built mirrored:
![2023-09-18_22 23 48](https://github.com/ldtteam/Structurize/assets/10704907/cb007ad5-bdb1-47cb-abec-6d6ae7410bcb)

180 degree rotated preview:
![2023-09-18_22 24 09](https://github.com/ldtteam/Structurize/assets/10704907/a254cc25-5de4-48e2-82a2-198f6db843b0)

### Expected Behavior

Buildings to preview as placed/built.

### Reproduction Steps

Build any Minecolonies building mirrored.
Building another building near it.
Preview of existing, mirrored building is rotated 180.

### Logs

N/A

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ansaruman** [comment]
I have the same problem, I tried to install all possible versions of mods (both releases and betas) needed to run the MineColonies on version 1.20, but it didn’t help. Licensed version of Minecraft, no third-party mods are installed except MineColonies, blockui, structurize, domum ornamentum, OptiFine. Don't even know what to do. :(

**Comment by ansaruman** [comment]
I downloaded the mods I needed from this modpack for version 1.20 and my problem was solved
https://www.curseforge.com/minecraft/modpacks/minecolonies/files/4638316

**Comment by Talyda** [comment]
> , OptiFine. 
that is probably part of your problem BTW, and you are probably going to run into more problems later - optifine messes with stuff. Use Rubidium and Oculus

**Comment by ansaruman** [comment]
> > , OptiFine.
> > that is probably part of your problem BTW, and you are probably going to run into more problems later - optifine messes with stuff. Use Rubidium and Oculus

Well, in my case, the problem was not in Optifine, since I removed Optifine and tried to run mods without it, but the problem still remained. Most likely the problem was with the modification versions. But thanks for the advice.

**Comment by Sandriell** [comment]
I am not using Optifine. Instead using Rubidium and Oculus.

**Comment by Jinotad** [comment]
Having this issue on the Minecolonies Special Event: Raid King-1.4.zip 

structurize-1.20.1-1.0.647-BETA.jar on 
minecolonies-1.20.1-1.1.185-BETA.jar

Effects both preview with the build tool near structures. In addition while wearing Minecolonies Builder's Goggles.

Not using any 

![2023-09-29_14 16 24](https://github.com/ldtteam/Structurize/assets/85356635/1fda6e58-8311-4b7e-b63c-537d8554d501)
![2023-09-21_19 37 54](https://github.com/ldtteam/Structurize/assets/85356635/4583c717-d150-4f97-8ffc-5f09f8d2b451)

**Comment by Talyda** [comment]
> I am not using Optifine. Instead using Rubidium and Oculus.

Sorry that was more to let them know that optifine was gonna cause them more problems =)

**Comment by Nightenom** [comment]
I'm really not sure why is this happening (must be mcol bug imho), tho it shouldn't happen after neoforge port (because of porting changes that will come with it)

**Comment by Nightenom** [comment]
Please comment if this is still happening, we have been fixing this issue for ages and in recent year there was certain huge shift in code, so it's probably already fixed
