### ISSUE TITLE
1.14.4: Naturally generated trees decay without being touched

### ISSUE THREAD

**Issue by DoggoBoi** [ldtteam/Structurize#61]
### copy_paste version

release 1.14.4-forge-28.0.17

### Expected behavior

- Tree leaves keep existing

### Actual behaviour

- Tree leaves decay for no reason

### Steps to reproduce the problem

1. Use like 10 other mods
2. Also use this mod
3. That's literally it

**Comment by Raycoms** [comment]
Are you sure that's our mods fault?

Am Mo., 29. Juli 2019 um 16:37 Uhr schrieb DoggoBoi <
notifications@github.com>:

**Comment by DoggoBoi** [comment]
I disabled the mod and the trees went back to normal.

**Comment by Raycoms** [comment]
should be fixed
