### ISSUE TITLE
game crash when trying to render in abuilding with a armour stand 

### ISSUE THREAD

**Issue by Xirnbruaddict** [ldtteam/Structurize#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

1.0.653

### MineColonies Version (if related bug)

1.20.1-1.1.227

### Related Mods and their Versions

forge version 47.1.76

### Current Behavior

game crashs when trying to render in a building with a armour stand some are ok until level 3 

### Expected Behavior

building should render and be useable 

### Reproduction Steps

try and load in medvail oak building with a armour stand 

### Logs

https://gist.github.com/Xirnbruaddict/ba493448e55c225e15cf06496095da53

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nullzee** [comment]
Getting this same issue, though my world doesn't have any armor stands in it (I have /kill @e'd all of them). Seems to be related instead to a bugged chunk of some sort. Haven't had any problems for over 20 hours, but now when trying to preview a building in a certain chunk area the game will crash. Logs show an armor stand render error, but there aren't any alive. Currently happening when I try to preview any structure, have tested roads, decorations etc.

Running Better MC 1.20.1 with minecolonies and dependencies installed.
structurize-1.20.1-1.0.648-BETA
minecolonies-1.20.1-1.1.227-BETA
blockui-1.20-0.0.84-ALPHA

Logs:
https://gist.github.com/Nullzee/1ee71c91600d05d91cb69a9c2f5b575a

**Comment by MotionlessTrain** [comment]
Could you perhaps try without Canary?

**Comment by Sovreighn** [comment]
Confirmed the removal of CANARY fixes this issue, I tested it with DW20 1.20 pack after adding Minecolonies and its dependencies UTD. I was crashing anytime I would try and preview a building that had an armor stand.

**Comment by Raycoms** [comment]
Report to canary please then

**Comment by Nightenom** [comment]
> Report to canary please then

Don't
