### ISSUE TITLE
1.20.1 - Structurize wants wrong version multipiston.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/Structurize#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

structurize-1.20.1-1.0.659-BETA.jar

### Related Mods and their Versions

NA

### Current Behavior

structurize-1.20.1-1.0.659-BETA.jar wants multipiston 1.19.2

### Expected Behavior

wants the correct version for 1.20.1

### Reproduction Steps

Get mod use mod.

### Logs

https://gist.github.com/P3rf3ctXZer0/fa8fe404e51f7e847d06ae4dd5625ee4

### Anything else?

Shin told me to make this.
If you go back to ``structurize-1.20.1-1.0.656-BETA.jar`` this issue does not exist.

::Thoughts::
I believe its a simple typo. Check 1.20.1 code.

### Footer

Yep this is the end. PS I didn't want to make this I spent 72 hours coding for Cobblemon.

**Comment by MotionlessTrain** [comment]
Multipiston doesn't seem to be a dependency of Structurize at all

**Comment by Talyda** [comment]
I didn't realise he didn't put all the info
This was error:
![image](https://github.com/ldtteam/Structurize/assets/17323101/359995f6-3df4-44b7-88ee-c4f242d12ac3)

These were versions he was using 
![image](https://github.com/ldtteam/Structurize/assets/17323101/a06e0513-7c3b-4392-906b-591118fff4b7)

Dropping one version down of structurize (no other changes) apparently fixed it

**Comment by MotionlessTrain** [comment]
Structurize looks to be a dependency of Multipiston, so it is strange that downgrading structurize solves this (at least satisfies multipiston's requirement)

**Comment by MotionlessTrain** [comment]
I could indeed see that multipiston asks for a 1.19 structurize (but apparently doesn't mind the minecraft version), so the real bug in this case is that minecolonies and Multipiston don't recognise structurize at all

**Comment by Raycoms** [comment]
The structurize jar is def not only 38kb, sth went wrong there.

**Comment by Talyda** [comment]
Oh, that is not even information I thought to look at, will try and keep that in mind

**Comment by MotionlessTrain** [comment]
Looks indeed like something went wrong downloading the mod

**Comment by P3rf3ctXZer0** [comment]
Apologies I was really tired and I had been working for hours ...

**Comment by Raycoms** [comment]
No problem =D
