### ISSUE TITLE
[CTD] Crash with Minecolonies Supply camp preview with L2Hostility

### ISSUE THREAD

**Issue by drakray** [ldtteam/Structurize#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

1.0.659-BETA

### MineColonies Version (if related bug)

1.1.274-BETA

### Related Mods and their Versions

Neoforge 47.1.79
L2 Hostility 2.4.10

### Current Behavior

Trying to see a Fortress Supply Camp crashes the game.
Medieval Birch crashes also, with same log mentionning Armor Stand and L2 Hostility
Preview of supply camp that do not have Armor Stand don't crash

### Expected Behavior

Not to crash XD

### Reproduction Steps

Install mods
Try to preview Supply camp containing Armor stand (Fortress or Medieval Birch are confirmed to use Armor Stand)
Crash

### Logs

https://pastebin.com/WMQCnFbb

### Anything else?

Reported to L2 Hostility here https://github.com/Minecraft-LightLand/L2Hostility/issues/2

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Will get fixed in #623
