### ISSUE TITLE
Beds and signs do not show up in build preview

### ISSUE THREAD

**Issue by FatesTimelines1337** [ldtteam/Structurize#626]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

structurize-1.19.2-1.0.661-RELEASE

### MineColonies Version (if related bug)

minecolonies-1.19.2-1.1.299-BETA

### Related Mods and their Versions

Forge: 43.3.0
BlockUI: 1.19.2-1.0.117-BETA
Domum Ornamentum: 1.19-1.0.146-BETA-universal
Multipiston: 1.19.2-1.2.25-ALPHA

### Current Behavior

Beds and signs do not show up in the build preview

### Expected Behavior

Beds and signs show up in the build preview

### Reproduction Steps

1. Use the build tool to select a building that has beds or signs
2. Observe that beds or signs are not visible in the build preview

### Logs

https://gist.github.com/FatesTimelines1337/f91c70676d7c7f70256c5329ffc3b2ed

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
They work for me, few questions: looks like you're using just our mods, is that correct? check if you're using fancy/fast graphics, fabulous is not fully supported
edit: found yours conversation on discord, apart from fabulous i'm unfortunately not aware of anything which would cause the issue

**Comment by FatesTimelines1337** [comment]
I'm not using Fabulous, getting the same result on fancy and fast. Only occurs with me with version 1.19.2, 1.20.1 works just fine

**Comment by Nightenom** [comment]
Weird, wait for merge of #623, that might change something, or at least hopefully produce some logs

**Comment by Moobien** [comment]
confirmed happening in a clean instance using structurize 676-release.

https://gist.github.com/Moobien/f1ec0bc8db831e325ab818eaa7165516 - logs

**Comment by bakuscout** [comment]
currently running:
Minecolonies - 1.19.2-1.1.421-BETA
structurize - 1.19.2-1.0.676-RELEASE

and all other dependencies at there latest Beta/Release versions
i am also running several other mods, and am also encountering the issue, haven't noticed it with signs, but i have seen it with beds.

**Comment by Nightenom** [comment]
Porting blunder, should be working now
