### ISSUE TITLE
Big bug with minecraft 1.20.1 (with shaders) 

### ISSUE THREAD

**Issue by MediaFoxxx** [ldtteam/Structurize#627]
### Is there an existing OptiFine issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize, OptiFine and shader Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods and shaders that are part of my problem.

### Did you ask on Discord?

- [ ] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

1.0.662-BETA

### OptiFine Version

HD_U_I6_pre6

### Shader Names and Versions

I`ve tried every of those:
BSL_v8.2.05
ComplementaryReimagined_r5.0.1
ComplementaryUnbound_r5.0.1
MakeUp-UltraFast-8.8e

### Related Mods and their Versions

blockui-1.20-0.0.84-ALPHA
domum_ornamentum-1.20-1.0.136-BETA-universal
minecolonies-1.20.1-1.1.240-RELEASE
preview_OptiFine_1.20.1_HD_U_I6_pre6
structurize-1.20.1-1.0.648-BETA
tl_skin_cape_forge_1.20_1.20.1-1.32
Forge: 47.2.0

### Current Behavior

I can`t understand what is going on, all is moving togather
![image](https://github.com/ldtteam/Structurize/assets/95166381/c44c842e-246b-4040-b453-349e5d9abe3a)
![image](https://github.com/ldtteam/Structurize/assets/95166381/0d3a18c8-5ea1-45a8-bda3-56f5cf6bb8eb)

### Expected Behavior

I tried to place any of preview of building in Minecolonies with BuildTool

### Reproduction Steps

1. Get BoildTool
2. Righ click on the ground, choose the building
3. Confirm building

### Logs

<script src="https://gist.github.com/MediaFoxxx/abcbd120d8eb42ae787dbb02cb770249.js"></script>

### Anything else?

![image](https://github.com/ldtteam/Structurize/assets/95166381/89893c51-5b5d-4e09-ba1c-3e406ac6980d)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Try using oculus and rubidium instead of optifine

**Comment by MediaFoxxx** [comment]
> Try using oculus and rubidium instead of optifine

I`ll try it now

**Comment by MediaFoxxx** [comment]
You`re the best! Thank you so much!

**Comment by Nightenom** [comment]
Optifine is not supported beyond 1.20
