### ISSUE TITLE
[1.19.2] Crash to Desktop when using Schematic Paste

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/Structurize#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-1.0.661-RELEASE

### MineColonies Version (if related bug)

1.19.2-1.1.315-BETA

### Related Mods and their Versions

Forge: 43.2.21

### Current Behavior

In single player, while in creative mode and using the "Schematic Paste" option to paste in a schematic, the game crashes to desktop.

Upon reloading, the schematic has only been partially pasted in.

### Expected Behavior

Not to crash

### Reproduction Steps

Paste in a schematic using "Schematic Paste"

### Logs

https://gist.github.com/Sandriell/599f3c1468c9d62745f5fdbd32c5f520

### Anything else?

If it matters, this is a schematic that was created on a 1.16.5 world, and I am attempting to place it in 1.19.2 so I can update/rescan it. Have not had issues with this so far with other similar schematics.

I can provide the schematic if needed, it is a slightly modified version of the Medieval Spruce Archery Academy.

Finally, this is a "blueprintbuildmode = true" world.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Update to latest

**Comment by Raycoms** [comment]
Buildsystem derp, releasing latest now
