### ISSUE TITLE
Bug: Crash to desktop for scan tool showing resources when floating items are in the zone

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/Structurize#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-1.0.661-RELEASE

### MineColonies Version (if related bug)

1.19.2-1.1.323-BETA

### Related Mods and their Versions

blockui-1.19.2-1.0.122-BETA
domum_ornamentum-1.19-1.0.146-BETA-universal
Forge 43.2.14

### Current Behavior

Crash to desktop as soon as you click Show Resources

### Expected Behavior

No crash, and to be able to 'remove' the floating entities

### Reproduction Steps

Repro:
* I had a line of the 5 Urban Birch library huts 1-5 for reference from ages ago for the contest.
* Using scan tool select all 5.
* Show resources and remove things (starting with gravity blocks, item frames, torches/etc. (falling things)), but save the solid placeholders for absolute last and DON'T remove them yet.
* Exit the scan mode. Re initiate right away by right clicking.
* Click Show Resources, and crash immediately (client only crash)
* Start client again; when going to confirm only solid placeholders are in the area impacted I found that there were actually some books (empty) and books+quill (some empty, some with contents) from lecterns, floating on the solid placeholders in the area.
I picked them up
No more crash

### Logs

https://gist.github.com/Shadizar/e8a9e5172970d0d85ee5257818d0aa87

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Shadizar** [comment]
some discord comments 

Thodor12 — Yesterday at 9:35 AM
It's known that the resources list crashes instantly the moment there is a floating item entity
Any item entity floating in the scan area will crash it, not specifically books and what
Shadizar — Yesterday at 9:47 AM
Huh; it must be recent? It didn't used to do that for me (for torches, lanterns, and assorted other things) when I was doing schem work and cleanup last summer
I'd have lots of floaters back then 🙂 and could even remove them via resource list at the time
that would have been mid-July ish

**Comment by Raycoms** [comment]
update blockui =)
