### ISSUE TITLE
[1.14.4] Adding Structurize to a modpack wipes all crafting, loot and droptables.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/Structurize#64]
### copy_paste version

	structurize-0.10.123-ALPHA.jar

### Actual behaviour

- Having this mod onboard wipes all loot tables, drop tables, and crafting recipies.

**Comment by Asherslab** [comment]
It's because we've got bad names in it. i've fixed that in my PR

Capital letters in a datapack invalidates all data packs. kinda stupid how non-resilient that is, but whatever

**Comment by Raycoms** [comment]
Should be fixed now
