### ISSUE TITLE
Pointed Dripstone adds dirt beneath

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/Structurize#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

1.0.680-BETA

### MineColonies Version (if related bug)

1.1.428-BETA

### Current Behavior

Pointed Dripstone adds dirt beneath when built or pasted in.

Nethermine lvl3 preview
![2024-01-16_13 10 34](https://github.com/ldtteam/Structurize/assets/120763436/01a819d2-8e6a-4e4d-95dd-a9a60aa71cfe)
Nethermine lvl 3 when pasted/built
![2024-01-16_13 10 47](https://github.com/ldtteam/Structurize/assets/120763436/8a5773d6-2969-455f-8623-2aaae4e104d4)

Preview lvl5
![2024-01-16_13 14 20](https://github.com/ldtteam/Structurize/assets/120763436/0b9961b6-849d-475e-b429-310e9ce71aa8)
Pasted/Built lvl5
![2024-01-16_13 11 37](https://github.com/ldtteam/Structurize/assets/120763436/e17d8b2a-1562-4120-b450-03869fb270c1)

Preview
![2024-01-16_13 14 10](https://github.com/ldtteam/Structurize/assets/120763436/ac06183b-7216-410a-8c1c-a2a2c1a3e92c)
Pasted/Built
![2024-01-16_13 12 24](https://github.com/ldtteam/Structurize/assets/120763436/35c8e099-8ccc-4f77-acc7-bfba68e0228d)

### Expected Behavior

To have pointed dripstone there instead of dirt.

### Reproduction Steps

Paste or build any build that has pointed dripstone in the schematic. There will be dirt.

### Logs

Don't have one

### Anything else?

Shadizar mentioned today on Patreon Discord: https://discord.com/channels/472875599422291968/486940969737125922/1196623289641095220
Jinotad reported there in November: https://discord.com/channels/472875599422291968/486940969737125922/1169411026631012462
mbacon on main discord: https://discord.com/channels/139070364159311872/724810019928801290/1156713547577970768
Jino suggested someone needed to make an issue here to make it more visible.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Closed in https://github.com/ldtteam/Structurize/pull/648
