### ISSUE TITLE
[1.14.4] Crash when loading Structurize with Forge .45 (needs update)

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/Structurize#65]
### copy_paste version

	structurize-0.10.130-ALPHA.jar

Crash report - https://gist.github.com/ProsperCraft/f2658eaa27fa6cf0128d888167058451
[debug.log](https://github.com/ldtteam/Structurize/files/3485209/debug.log)
[latest.log](https://github.com/ldtteam/Structurize/files/3485210/latest.log)

**Comment by Nightenom** [comment]
That's really weird one, but I'm probably gonna blame your pr @Asherslab 
I'm not able to fix that now but can you try removing every mod event bus subscription annotation?
Especially the one in Structurize.java
But if it's running well in ide then it can be buildsystem problem, really dunno here

**Comment by Raycoms** [comment]
@nightenom it should be fixed by just upgrading to forge .45 and rebuilding
it.

Am Fr., 9. Aug. 2019 um 15:24 Uhr schrieb Nightenom <
notifications@github.com>:

**Comment by Asherslab** [comment]
@Nightenom my PR was tested by 4 people, on 8 occasions. wasn't me

**Comment by Raycoms** [comment]
Not related to the pr. I check it tomorrow

Am Fr., 9. Aug. 2019 um 23:41 Uhr schrieb AshersLab <
notifications@github.com>:

**Comment by ProsperCraft** [comment]
This is resolved.
