### ISSUE TITLE
Crash - MousePressed event for BO screen

### ISSUE THREAD

**Issue by Moobien** [ldtteam/Structurize#661]
Getting this crash on numerous mincolonies/structurize/blockui versions.

First encountered on the schematic server, went to a testing instance with most recent versions of minecolonies and depenancies and getting it there.

Logs reference BlockUi

https://gist.github.com/Moobien/c273a18c4898f2c4ba40342f33b1e6f4

**Comment by Talyda** [comment]
Did you try without oculus and embeddium as well? There was recently I think versions of them that were wonky?

**Comment by Moobien** [comment]
> Did you try without oculus and embeddium as well? There was recently I think versions of them that were wonky?

testing now.

**Comment by Moobien** [comment]
confirmed happens without embeddium/oculus.

Reproduction steps:

Paste in schematic from a built in style.
Scan with scan tool (I named it 1)
Open build tool and go to your personal scans folder and click the scan you just scanned
CRAAAAAAAAAAAAAAAAASH


Seems to happen when selecting a scan in your personal scan folder. loading that scan after a restart, and loading new scans has no issues. seems related to changing style packs.
