### ISSUE TITLE
Decoration rotated 90 degrees on upgrade

### ISSUE THREAD

**Issue by FatesTimelines1337** [ldtteam/Structurize#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

structurize-1.20.1-1.0.731-RELEASE

### MineColonies Version (if related bug)

minecolonies-1.20.1-1.1.566-BETA

### Current Behavior

When upgrading a Aquatica connector, the preview is rotated 90 degrees

### Expected Behavior

The preview is not rotated

### Reproduction Steps

1. Start an Aquatica colony
2. Build an Aquatica connector
3. Upgrade the connector

### Logs

https://gist.github.com/FatesTimelines1337/a6c53949d12bf1ca19c4f35225fd87e6

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
I manually passed this to building designers, but please next time use <https://github.com/ldtteam/minecolonies/issues/5006> or our discord. Thank you
