### ISSUE TITLE
[1.14.4] Server crash on load with update

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/Structurize#67]
### copy_paste version

structurize-0.10.138-ALPHA

Stacktrace
https://gist.github.com/ProsperCraft/73699e2b547913ccef2c1dccf6cd3bb4

Crash log-
https://gist.github.com/ProsperCraft/16e45e2a2fa3311808e5d29f9dce6866

**Comment by Raycoms** [comment]
Fixed
