### ISSUE TITLE
About a language pack

### ISSUE THREAD

**Issue by Flying-Jerry** [ldtteam/Structurize#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

1.16.5-1.0.418-alpha

### Problem description

Despite choosing minecraft version 1.18, the question I actually asked was about 1.16 (because it's not available).

I made a language pack and tried to put it in a.jar file, but there were four language files inside.
![5e8de38d95824c0392ca5a96fe9a333d](https://github.com/ldtteam/Structurize/assets/106455290/3651ef79-c994-4fe4-95fc-59cb21e3b242)
Then I put my language pack in there.
![image](https://github.com/ldtteam/Structurize/assets/106455290/15f588bd-0c44-472d-a48c-71f7214b73b8)
When I opened the game, I received this error.
![image](https://github.com/ldtteam/Structurize/assets/106455290/609f556b-0003-498c-9f74-5ccd4e5e9fec)
What I want to know is, what can I do to open the game and see my translation in the game.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Hi, 1.16 is EOL, you have to translate en_us.json, if you're modifying jar then ensure you do it right, investigate the logs, you should also try resource pack.
That's being said we won't provide more support here, you may try [our discord - unsupported versions channel](https://discord.com/invite/hvwFcfP5)
