### ISSUE TITLE
Create mod mechnical belts cause crash on blueprint

### ISSUE THREAD

**Issue by panskdev** [ldtteam/Structurize#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

structurize-1.20.1-1.0.737-BETA.jar

### Current Behavior

Attempting to "Show resources" or assigning a builder to build a structure containing mechnical belts from create mod crashes the game.

### Expected Behavior

Structurize scanning and loading mechanical belts from create mod correctly

### Reproduction Steps

1. Make a small structure that contains at least 2 shafts from create 
2. use 1 mechanical belt to connect the shafts. 
3. While using the scan tool, click on "Show Resources" OR assign structure to a minecolonies builder
4. Game instantly crashes

### Logs

https://gist.github.com/panskdev/6bc4c20a9199a52bd5ed79678aac3477

### Anything else?

I was informed by someone that mechnical belts did use to work in the past, although I couldn't verify the integrity of such claim.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
We don't have to take into account that we would be able to place every single block that's out there, we have no official compact for Create

**Comment by Nightenom** [comment]
According to crash log provided: this can't be our issue <https://github.com/ldtteam/BlockUI/blob/version/1.20.1/src/main/java/com/ldtteam/blockui/BOScreen.java#L305>
Is probably caused by some mixin/coremod (in vanilla crash reporting) of someone's else mod
