### ISSUE TITLE
[1.14.4] Single player crash on load -IllegalArgumentException: Illegal character in opaque part at index 11:

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/Structurize#68]
### copy_paste version

structurize-0.10.145-ALPHA.jar

https://gist.github.com/ProsperCraft/a75425f514c462e6fcc3f856fa4d1dee

**Comment by ProsperCraft** [comment]
It loads to the main menu without issue, this crash happens when you start a new world.

**Comment by ravenbuilder934** [comment]
Is this reproducible on newer versions?

**Comment by Raycoms** [comment]
@ravenbuilder934 digging out graves today? =D

**Comment by ravenbuilder934** [comment]
Yup
The top was still open and i wanted to close them before someone stepped in it :P
