### ISSUE TITLE
Holographic Display of Minecolonies Buildings not working on newer versions

### ISSUE THREAD

**Issue by zukatotokime** [ldtteam/Structurize#691]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

Anything above "structurize-1.20.1-1.0.742-RELEASE"

### MineColonies Version (if related bug)

minecolonies-1.20.1-1.1.603-RELEASE

### Related Mods and their Versions

All Minecolonies depencies on any version do NOT affect the issue

### Current Behavior

When loaded into the world and trying to view the holographic display of MC houses with the builders goggles, they do not show up, while other actions still do

### Expected Behavior

When loading in and wearing the goggles, the holographic display of the buildings should show up

### Reproduction Steps

1. download the entire minecolonies pack on the newest version each
2. ensure structurize above the version mentioned earlier
3. launch the game and attempt to see placed & build activated structures

### Logs

unable to provide logs, partially due to the multitude of tested mod versions

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
For me this seems to be minecolonies issue, but to be sure: can you provide us logs from session where this is happening? also are you using any rendering related mods or fabulous mode? (if so, try without it/them)

**Comment by zukatotokime** [comment]
> For me this seems to be minecolonies issue, but to be sure: can you provide us logs from session where this is happening? also are you using any rendering related mods or fabulous mode? (if so, try without it/them)

I dont know how to log, otherwise I would have done so already, but I am not using any render mods or fancy mode. I can say for sure though that it is structurize, as every other mod variation (brute force confirmed) works, just not structurize above the given version

**Comment by Talyda** [comment]
To properly diagnose your issue we need access to your logs please. 
You can generally find these logs in your game or server directory under the logs folder. The file latest.log is most likely required.
Once you've found this file please post it on a paste site. As a team we recommend https://gist.github.com/.

----------

In order to make a gist, follow these steps:
You go to https://gist.github.com/
You sign up or in
There should be a button to make a gist somewhere. If not, go to https://gist.github.com/ again
Drag the file on the big text area
Click "Create secret gist"
Copy the url out of the address bar and paste it in the chat the log was requested

**Comment by kedamono** [comment]
I've also run into this problem, both with placing new buildings and with the Builder's Goggles. I get the bounding box, but no preview of the Level 5 building.

**Comment by Nightenom** [comment]
Please try structurize-1.20.1-1.0.754-beta.jar

**Comment by kedamono** [comment]
Tried structurize-1.20.1-1.0.754-beta and still had the same problem. No preview showed up.

**Comment by Nightenom** [comment]
Should be fixed in 1.20.1-1.0.755-beta via https://github.com/ldtteam/Structurize/commit/cadab910f36d1c2184715397142dd515c75cbda5
