### ISSUE TITLE
[1.21.1} Structurize is requesitng a wrong depency

### ISSUE THREAD

**Issue by Periam** [ldtteam/Structurize#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

structurize-1.0.750-1.21.1

### MineColonies Version (if related bug)

na

### Related Mods and their Versions

MC 1.21.1
neoforge-21.1.28
blockui-1.0.184-1.21.1-beta
domun_ornamentum-1.21.1-1.0.200-beta
jei-1.21.1-neoforge-19.11.0.128
l2library-3.0.2+2
multipiston-1.21-1.2.47-Beta
structurize-1.0.750-1.21.1

### Current Behavior

After installing the mods and the requested dependencies the game does not launch since is request a different version of the depency

### Expected Behavior

That the game launch normally

### Reproduction Steps

1-Installing Mod
2-Installing mods dependency
3-Launch Game

### Logs

https://pastebin.com/Ki7YVH04

### Anything else?

After installing the mods and the requested dependencies the game does not launch since is request a different version of the depency

MC 1.21.1
neoforge-21.1.28
blockui-1.0.184-1.21.1-beta
domun_ornamentum-1.21.1-1.0.200-beta
jei-1.21.1-neoforge-19.11.0.128
l2library-3.0.2+2
multipiston-1.21-1.2.47-Beta
structurize-1.0.750-1.21.1

![image](https://github.com/user-attachments/assets/1c79516e-686d-4be7-9a8c-e6b6ecf1cc12)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
This will be fixed hopefully this week, we're aware and fully working on it. Will close now

**Comment by Periam** [comment]
hey, it is happening the same with other mod
![image](https://github.com/user-attachments/assets/6d6178ec-2680-4baf-8769-9a8858337c4f)
