### ISSUE TITLE
crash picking tag block or tag tool (server, creative menu)

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/Structurize#697]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

1.0.751

### MineColonies Version (if related bug)

1.1.703

### Current Behavior

Note, the actual MC version is 1.21, which is not available in the dropdown
I needed a tag block in creative for schematic work. Opened creative, searched 'tag' and left clicked the tag block. The client immediately crashed. Reproduced once, same behavior.

### Expected Behavior

No crash, and tag block on the cursor so I can place it in my inventory

### Reproduction Steps

Opened creative, searched 'tag' and left clicked the tag block.

### Logs

https://gist.github.com/Shadizar/f6a032a2360af4e73125a610590ce335

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Shadizar** [comment]
Does it with the tag tool too, so 1.21 schematic work may be ...
interesting

I am afraid to /give them because I am afraid I may then be in a crashloop situation

**Comment by Nightenom** [comment]
~~Cannot replicate, also the error looks like some other mod is tampering with ServerLifecycleHooks#currentServer which is internally handled by neoforge~~
Can replicate, thought that this method work for dist connection too :shrug:

**Comment by Shadizar** [comment]
I used /give to give myself a tag anchor block, because when I got myself a tag tool it had worked ok.
For the tag anchor block, I crashed when I made it the active slot in my hotbar (so now I crash on world load, on the server)

Was directed on discord to add the info and log to this issue. 

https://gist.github.com/Shadizar/4abdc6988b302fde500e890779865345
Minecol 1.1.719
struct 1.0.752

**Comment by Shadizar** [comment]
In case it is a unique permutation or requires handling beyond the original
