### ISSUE TITLE
using middle click (pickblock) with tagblock does not 'chameleon' it properly in 1.21

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/Structurize#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

1.0.751

### MineColonies Version (if related bug)

1.1.703

### Current Behavior

Tag block does not obtain the visual appearance of the block you are middle clicking

### Expected Behavior

Tag block will obtain the visual appearance of the block you are middle clicking as in previous version (and as it does currently on latest 1.19)

### Reproduction Steps

Obtain tagblock (currently be in single player; server will crash the client, filed separately)
middle click it on stone, gravel, etc.
<bug occurs>

### Logs

not applicable

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Closing in favor of #697
