### ISSUE TITLE
Building bug

### ISSUE THREAD

**Issue by emilyxwardx** [ldtteam/Structurize#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **beta/release** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

1.1.707-snapshot

### Current Behavior

when building the PAGODA barracks to level 5, the last 2 barrack towers are incorrectly placed, they get vbuilt wrong, the workers cant even access the buildings due to this.

### Expected Behavior

I excpected it to be built properly and workers be able to use the barrack towers as inteded.

### Reproduction Steps

Build baracks to level 5 a long with the towers.
yuo can see the issue once fully built

### Logs

no log

### Anything else?

![2024-10-02_14 57 23](https://github.com/user-attachments/assets/8eeb42bb-48b1-4634-896e-8ab068a2ee08)
![2024-10-02_14 57 29](https://github.com/user-attachments/assets/d2f3854e-4158-4a66-9729-3718e7f05c27)
![2024-10-02_14 57 46](https://github.com/user-attachments/assets/1f92cc86-ed38-4bff-ae83-d5309771e258)
![2024-10-02_14 57 56](https://github.com/user-attachments/assets/e54e4456-0577-4bf8-9b46-e878aa777d8d)
![2024-10-02_14 58 00](https://github.com/user-attachments/assets/2d0eab24-4465-4e3f-9e2e-139f523d1ffe)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by emilyxwardx** [comment]
LOG 
[2024-10-01-1.log.gz](https://github.com/user-attachments/files/17232806/2024-10-01-1.log.gz)

**Comment by Nightenom** [comment]
Sounds like an issue for ldtteam/minecolonies#5006

**Comment by MotionlessTrain** [comment]
The building builds correctly in 1.20, though. So there is something changed regarding to child buildings

This has been reported with multiple child building and decorations in 1.21

**Comment by Nightenom** [comment]
Might be the guessing system for rot/mir which might have changed logic-wise during porting, but that would be mcol issue then

**Comment by Raycoms** [comment]
yes, it's a minecol issue and I think we have several open ones already. Something is off.

**Comment by emilyxwardx** [comment]
apologies i must not have searched a specific word! glad its been caught out cuz its been winding me up for days XD
