### ISSUE TITLE
Client crash when hovering over anchor block

### ISSUE THREAD

**Issue by Gaz492** [ldtteam/Structurize#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **beta/release** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

1.0.752-1.21.1-snapshot

### MineColonies Version (if related bug)

1.1.726-1.21.1-snapshot

### Current Behavior

While on a server, open up your inventory screen to look at jei/the vanilla creative inventory, search for `tag anchor` then hover over the item.
The game will now crash

This only happens while on a multiplayer server

### Expected Behavior

The game not to crash on hovering over the item

### Reproduction Steps

1. Open inventory
2. Search for `tag anchor` in either the vanilla creative inventory or jei
3. Hover over the tag anchor item
4. Crash

### Logs

https://pste.me/@bBDH5J-c34Y

### Anything else?

This issue only happens while connected to a server

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Dupe #697 see #704
