### ISSUE TITLE
Error sending packet clientbound/minecraft:custom_payload

### ISSUE THREAD

**Issue by 5cript** [ldtteam/Structurize#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **beta/release** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

structurize-1.0.754-1.21.1-snapshot

### MineColonies Version (if related bug)

minecolonies-1.1.773-1.21.1-snapshot

### Related Mods and their Versions

```
--fml.neoForgeVersion, 21.1.62, --fml.fmlVersion, 4.0.24, --fml.mcVersion, 1.21.1, --fml.neoFormVersion, 20240808.144430

netty-0.1.4.jar [parent: owo-lib-neoforge-0.12.15-beta.9+1.21.jar...
fabric-networking-api-v1-4.2.2+a92978fd19.jar" [parent: owo-lib-neoforge...
```
**EDIT: I have removed Accessories, and owo because it seemed to bring some networking related libraries and the above listed jars disappeared. The issue persisted though.**

### Current Behavior

Others cannot join the server as long as structurize is part of the modlist, removing the mod solves the issue.
Whereas I myself have no issues joining, but the server is on my clients premise.

I have added the Connectivity mod AFTER encountering this issue in order to perhaps get more information about it, but it was not very useful and has not changed the outcome.

I have also taken the pack that I share, installed it back for myself, ran it and joined and it again worked for me, making sure everything is identical.

### Expected Behavior

Any client could join without issue

### Reproduction Steps

Unfortunately nothing spectacular.

1. Put the given mods together
2. Add the server **redacted**
3. Try to join and then encounter "Failed to encode packet 'clientbound/minecraft:custom_payload'"

### Logs

https://gist.github.com/5cript/5148313f9f032b58955c8a6de3ba5799

### Anything else?

Link to a modrinth mrpack file useable with the modrinth launcher: http://nuicpp.org:8081/Onwards%201.2.0.mrpack

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
The true error seems to be `java.lang.NoSuchMethodException: net.minecraft.network.protocol.common.ClientboundCustomPayloadPacket.packetName()` at https://gist.github.com/5cript/5148313f9f032b58955c8a6de3ba5799#file-gistfile1-txt-L3293
This usually means coremodding/mixins/corrupted forge jar, tho entire stacktrace is weird
Try removing `connectivity@5.8/com.connectivity.logging.PacketLogging.logPacket`

**Comment by Thodor12** [comment]
Remove all your fabric mods, I've seen one called fabric networking api. We don't support using the forgified fabric api anyway.
