### ISSUE TITLE
No Recipe for "Plain Oak Paper Timber"

### ISSUE THREAD

**Issue by Bunker-Kenyon** [ldtteam/Structurize#74]
There is no recipe for  "Plain Oak Paper Timber". it one of the build requirements for medieval builder hut.

**Comment by Bunker-Kenyon** [comment]
I'm not entirely sure as I can't find the recipes and none of the combinations I tried worked. https://www.wiki.minecolonies.com/source/misc/recipes. Its down at the bottom. There is no combination for Paper Timber Framed Blocks. I tried using paper on paper, paper on wood and a whole host of other combinations. BTW I think you guys have great mod!

**Comment by Asherslab** [comment]
oh, please use JEI for recipes, 1.14.4 introduced a tonne of new recipes

**Comment by Bunker-Kenyon** [comment]
That did the trick. Thank you!
