### ISSUE TITLE
[request] ability to specify blocks to be placed after others

### ISSUE THREAD

**Issue by nephatrine** [ldtteam/Structurize#75]
Currently (at least in 1.12), the mod seems to have special handling for some items like torches so they are placed in a final step and don't pop off everywhere during the build. This even seems to be the case for some mod-added torches. Unfortunately, ATLCraft candles and lanterns are not handled like this and so half of them inevitably are sitting on the floor as items when the build is done. Can we get a config option like Millenaire has to add more blocks to the post-build step?

**Comment by Nightenom** [comment]
someone might add this sooner, but ask your mod authors to make those items/blocks "material not solid"

**Comment by Raycoms** [comment]
Yeah, I think they should definitely not be marked as solid blocks.
