### ISSUE TITLE
Scan tool GUI buttons missing

### ISSUE THREAD

**Issue by Bucketsmith** [ldtteam/Structurize#78]
### copy_paste version

version 0.10.193 or curse 28.1.45

### Expected behavior
https://wiki.minecolonies.com/assets/images/tutorial/scan_tool_gui.png
- Scan tool GUI to have buttons to remove or replace certain blocks

### Actual behaviour
[![Image from Gyazo](https://i.gyazo.com/ae1ea0a65d8abba28b6abb0e54605cfa.png)](https://gyazo.com/ae1ea0a65d8abba28b6abb0e54605cfa)
- Scan tool GUI is not showing the buttons

### Steps to reproduce the problem

1. Scan schematic
2. Open scan GUI
3. ...
4. Profit

**Comment by Raycoms** [comment]
you only have the buttons when you are in creative mode.

**Comment by Bucketsmith** [comment]
> you only have the buttons when you are in creative mode.

How come not in survival?

**Comment by Raycoms** [comment]
Because that could cause issues with cheating on the servers

**Comment by Bucketsmith** [comment]
Then please allow it to be a config option. It's just two friends on our server and the default blueprint of the farm fields isn't the correct size. We want (in this case) to easily duplicate a farm layout that we made for expansion.
Trouble is, it picks up existing plants because the farmer is already using the field. With the buttons, we'd be able to simply remove those from the schematic.
Same with unwanted leaves from a tree that overhangs the area, or water tiles. (They translate to buckets of water and instead of having to supply a ton of buckets of water into the colony system, I'd rather take one bucket and do all the water on my own.)
Much simpler to just press the button to disregard these tiles rather than them being in there, having to supply all that stuff and then having to remove them by hand again...

**Comment by Raycoms** [comment]
oh, the button click doesn't disregard them, it actively removes it from the world.

**Comment by Bucketsmith** [comment]
Then I understand why you would consider it a cheat.
Is another way possible? That it only disregards the hypothetical blocks in the to-be-created schematic, rather than the real thing you're scanning?

**Comment by Raycoms** [comment]
Yeah we got a plan for an editor for survival of schematics

**Comment by Bucketsmith** [comment]
Alright, sounds cool!
