### ISSUE TITLE
[1.14.4] Duplicate Bug Cactusdoor

### ISSUE THREAD

**Issue by kaffeekirsche** [ldtteam/Structurize#80]
### copy_paste version

version structurize-0.10.194-ALPHA

### Expected behavior

- Brake Door give 2 doors back

### Steps to reproduce the problem

1. Place the door
2. Destroy the door
3. U get 2 doors

**Comment by PowerSchill** [comment]
I've duplicated the issue in the most recent version of structurize but haven't been able to find the source of the issue in the code.

**Comment by Strohtaler** [comment]
Still in current commit.

**Comment by Strohtaler** [comment]
_probably_ missing a LootTable entry like done for standard doors in `net.minecraft.data.lootBlockLootTables.addTables()`
```
      this.registerLootTable(Blocks.ACACIA_DOOR, (p_218483_0_) -> {
         return droppingWhen(p_218483_0_, DoorBlock.HALF, DoubleBlockHalf.LOWER);
      });
````

**Comment by PowerSchill** [comment]
I've determined the correct loot table syntax. However the loot table is automatically generated so the JAVA generator has to be updated to be able to support this. 

```json
{
  "type": "minecraft:block",
  "pools": [
    {
      "conditions": [
        {
          "condition": "minecraft:survives_explosion"
        }
      ],
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "conditions": [
            {
              "condition": "minecraft:block_state_property",
              "block": "structurize:blockcactusdoor",
              "properties": {
                "half": "lower"
              }
            }
          ],
          "name": "structurize:blockcactusdoor"
        }
      ]
    }
  ],
  "READ ME!!!": "DO NOT EDIT THIS FILE. DON'T TOUCH IT, TOUCH IT AND YOU WILL REGRET IT ~~ AshersLab (Use the Data Generators!"
}
```

**Comment by PowerSchill** [comment]
@Asherslab Does the DataGenerator support this format or will that project need to be updated first?

**Comment by Strohtaler** [comment]
no more free cactus door... #166   [: -)
