### ISSUE TITLE
Scan tool not working - point1 0,0,0

### ISSUE THREAD

**Issue by April25th-mc** [ldtteam/Structurize#84]
### copy_paste version

structurize-0.10.201-ALPHA.jar
minecolonies-0.10.576-ALPHA-universal.jar

### Expected behavior

- The scan tool should define a point 1 then a point 2 when right clicking

### Actual behaviour

- Point 1 seems to already be defined as 0, 0, 0. Whatever I right click on becomes point 2. Then my scan stretches way off to 0,0,0. I can't seem to find a way to delete point 1 and re-define it.

### Steps to reproduce the problem

1. Right click at lower left point of intended scan. Get message point 2 defined.
2. Right click at upper right point of intended scan. Get message point 2 defined.
3. Shift right click to try to view scan or save scan. Point 1 is 0,0,0 and scan is much too big to save.
4. Didn't profit :(

Note this is happening on the 1.14.4 schematics server, but I also tried creating a new profile with only the latest minecolonies/structurize alpha, created a single player test world, and tried to create an incredibly simple scan. Same behavior.

**Comment by Raycoms** [comment]
Left click pos1, right click pos2 -> profit =D

**Comment by April25th-mc** [comment]
haha thank you
