### ISSUE TITLE
crash launcher minecraft

### ISSUE THREAD

**Issue by tiphilou17** [ldtteam/Structurize#86]
### copy_paste version

0.10.201-ALPHA, minecraft forge 1.14.4 - 28.1.107

### Expected behavior

- starting game, loading mods

### Actual behaviour

- starting game, crash load mod structurize

### Steps to reproduce the problem

1. start launcher with 10giga ram 

"The game crashed whilst initializing game
Error: java.lang.IllegalStateException: GLFW error 65539: Invalid key 3"

**Comment by Asherslab** [comment]
Full logs in a gist thanks

**Comment by tiphilou17** [comment]
https://gist.github.com/tiphilou17/6ed8e9eeb00357b31b4cdc96cdf2f342

**Comment by someaddons** [comment]
`at com.direwolf20.mininggadgets.common.items.MiningGadget.func_77624_a(MiningGadget.java:107)`
seems that mod caused the issue, not structurize.

**Comment by tiphilou17** [comment]
ho sorry, thx so much
