### ISSUE TITLE
Model/Texture invisible part

### ISSUE THREAD

**Issue by Matthysse** [ldtteam/Structurize#88]
version "structurize-1.12.2-0.10.198-ALPHA"

### Expected behavior

Proper rendered shingles

### Actual behaviour

Texture/Model invisible part that acts like X-Ray.

### Steps to reproduce the problem

1. Place shingles
2. See underground
![2020-01-31_20 37 24](https://user-images.githubusercontent.com/32510957/73591938-1187a500-44f5-11ea-828f-1aaea73ecd0f.png)

**Comment by Nightenom** [comment]
1.12 is no longer maintained, if this issue persists in 1.15 or 1.16 feel free reopen
