### ISSUE TITLE
[1.15.2] Scan tool doesn't recognize cactus pot.

### ISSUE THREAD

**Issue by lordSeaworth** [ldtteam/Structurize#97]
**Versions:**
- MineCraft: 1.15.2
- Structurize: 0.10.252-ALPHA

**What would you expect to see if this feature was working as intended?**
minecraft:flower_pots, _minecraft:potted_cactus_ block being able to be detected by the scan tool for removal.

**Actual behaviour**
- The scan tool won't detect the cactus block.
![2020-02-14_04 21 47](https://user-images.githubusercontent.com/20868357/74498995-ae2d4800-4ee2-11ea-8292-eedb37e8e550.png)

**Comment by Nightenom** [comment]
Stale, probably fixed, if not please reopen
